[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci --omit=dev --ignore-scripts"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "echo '=== DATABASE_URL CHECK ===' && echo 'DATABASE_URL='$DATABASE_URL && echo '=== END CHECK ===' && npx prisma migrate reset --force && npm run db:deploy && npm start"

[variables]
NODE_ENV = "production"

[detectors]
playwright = false
puppeteer = false
canvas = false
jsdom = false

[providers]
node = "nixpacks"
