export default [
  "walking", "talking", "running", "jumping", "reading", "writing", "singing", 
  "dancing", "cooking", "painting", "driving", "flying", "swimming", "climbing", 
  "fishing", "hiking", "biking", "gardening", "shopping", "playing", "listening", 
  "watching", "drawing", "throwing", "catching", "kicking", "screaming", "laughing", 
  "crying", "exploring", "building", "inventing", "designing", "creating", "dreaming", 
  "planning", "analyzing", "solving", "calculating", "measuring", "studying", "teaching", 
  "training", "guiding", "advising", "coaching", "leading", "managing", "organizing", 
  "cleaning", "washing", "polishing", "decorating", "repairing", "adjusting", "testing", 
  "improving", "programming", "developing", "encoding", "encrypting", "decoding", "compiling", 
  "debugging", "sketching", "tracing", "copying", "pasting", "cutting", "highlighting", 
  "undoing", "redoing", "zooming", "scrolling", "clicking", "tapping", "dragging", 
  "dropping", "selecting", "typing", "printing", "scanning", "faxing", "emailing", 
  "chatting", "tweeting", "blogging", "streaming", "broadcasting", "announcing", "explaining", 
  "describing", "presenting", "negotiating", "persuading", "debating", "arguing", "questioning", 
  "answering", "replying", "confirming", "denying", "suggesting", "recommending",
  "accelerating", "accepting", "accomplishing", "accounting", "achieving", "acknowledging", 
  "acquiring", "acting", "adapting", "adding", "addressing", "administering", "admiring", 
  "admitting", "adopting", "advising", "advocating", "affecting", "affirming", "aiding", 
  "alerting", "aligning", "allocating", "allowing", "altering", "amending", "analyzing", 
  "anchoring", "announcing", "answering", "anticipating", "apologizing", "appealing", 
  "appearing", "applying", "appointing", "appraising", "appreciating", "approaching", 
  "approving", "archiving", "arguing", "arranging", "arresting", "arriving", "articulating", 
  "assembling", "asserting", "assessing", "assigning", "assisting", "assuring", "attaching", 
  "attacking", "attaining", "attempting", "attending", "attracting", "auditing", "authoring", 
  "authorizing", "automating", "avoiding", "awakening", "balancing", "banning", "bargaining", 
  "bathing", "battling", "bearing", "beating", "becoming", "befriending", "begging", "behaving", 
  "believing", "belonging", "benefiting", "betting", "billing", "binding", "biting", "blaming", 
  "blending", "blessing", "blinking", "blowing", "blurring", "boarding", "boasting", "boiling", 
  "bolstering", "bombarding", "booking", "boosting", "borrowing", "bouncing", "bowing", "boxing", 
  "bracing", "braiding", "branding", "breaking", "breathing", "breeding", "brewing", "bridging", 
  "briefing", "brightening", "broadcasting", "browsing", "brushing", "budding", "budgeting", 
  "buffering", "building", "bulking", "bumping", "bundling", "burning", "bursting", "burying", 
  "bussing", "busting", "butchering", "buttoning", "buzzing", "calculating", "calibrating", 
  "calling", "calming", "campaigning", "cancelling", "canning", "capturing", "caring", "carrying", 
  "carving", "cascading", "cashing", "casting", "cataloging", "catching", "categorizing", 
  "causing", "cautioning", "ceasing", "celebrating", "censoring", "centering", "certifying", 
  "challenging", "changing", "channeling", "charting", "chasing", "chatting", "checking", 
  "cheering", "cherishing", "chewing", "chilling", "chiseling", "choosing", "chopping", 
  "chronicling", "circling", "citing", "civilizing", "claiming", "clarifying", "classifying", 
  "cleaning", "clearing", "climbing", "clinching", "clipping", "clocking", "closing", "clothing", 
  "clustering", "coaching", "coasting", "coding", "collaborating", "collapsing", "collecting", 
  "coloring", "combating", "combining", "comforting", "commanding", "commemorating", "commencing", 
  "commenting", "commissioning", "committing", "communicating", "comparing", "compelling", 
  "compensating", "competing", "compiling", "complaining", "complementing", "completing", 
  "composing", "comprehending", "compressing", "compromising", "computing", "concealing", 
  "conceiving", "concentrating", "conceptualizing", "concerning", "concluding", "conducting", 
  "confessing", "confiding", "configuring", "confirming", "conflicting", "conforming", 
  "confronting", "confusing", "congratulating", "connecting", "conquering", "consenting",
"thinking intensely", 
"waiting for death", 
"staring at camera", 
"attacking", 
"drinking",
"fighting",
"spitting fire",
"experimenting",
"hallucinating",
"snarling", 
"laughing", 
"lazer blasting",
"doing telekenesis",
"hunting", 
"wearing hoodie", 
"with glowing eyes", 
"smoking a joint", 
"wearing a t-shirt", 
"screeching loudly", 
"wearing beanie and goggles", 
"wearing short shorts", 
"wearing sunglasses", 
"salivating", 
"growing", 
"working at drive-thru", 
"exploring", 
"tripping on lsd", 
"with cool hair and cheap clothes", 
"discovering ancient gold", 
"surrounded by money", 
"dressed in cheap ragged clothes", 
"looking at me", 
"working on laptop", 
"talking on phone", 
"dance passionately",
"dressing up in costume",
"drinking and getting drunk",
"playing the guidar",
"singing loudly",
'playing harmonica',
'juggling flaming pins',
'getting married',
'being born',
'riding a horse',
'sitting at the bar',
'sleeping on the bus',
'sleep walking',
"eating good food", 
"watching tv", 
"in bathtub",
"praying",
"finding treasure",
"being baptized",
"Pogonotomizing",
"Pluviophiling",
"Philematology",
"Crapulence",
"Cacoethes",
"Obnubilating",
"tattooed",
"dressed fancy",
"smoking marijuana",
"passing joint",
"smoking bong",
"surfing",
"skateboarding",
"skiing",
"snowboarding",
"dreaming",
"driving racecar",
"rising from the earth",
"Eleutheromania",
"Pluviophagous",
"Somnambulating",
"Heterodoxing",
"Apodyopsis",
"Odylic",
"Quomodocunquizing",
"Chucklefying",
"Gigglefying",
"Hilarifying",
"typing on laptop",
"Laughterizing",
"Amusementating",
"Jokifying",
"Snickeringly",
"Lollipopping",
"Chortlingly",
"Grinningly",
"Smirkingly",
"Sniggering",
"Wittyfying",
"Humorizing",
"Comedifying",
"Terrifying",
"Menacing",
"Horrifying",
"Petrifying",
"Intimidating",
"Frightening",
"Haunting",
"Chilling",
"Creeping",
"Shivering",
"Quivering",
"Trembling",
"Spooking",
"Startling",
"Dance",
  "Sing karaoke",
  "Play beer pong",
  "Socialize with friends",
  "Drink cocktails",
  "Play party games",
  "Take group photos",
  "Eat appetizers",
  "Listen to music",
  "Watch movies",
  "Make new friends",
  "Play video games",
  "Eat dinner",
  "Have a BBQ",
  "Play card games",
  "Play board games",
  "Watch sports",
  "Watch a live band",
  "Go swimming",
  "Go to the beach",
  "Go on a hike",
  "Have a bonfire",
  "Tell stories",
  "Have a costume party",
  "Have a themed party",
  "Have a murder mystery party",
  "Play truth or dare",
  "Play spin the bottle",
  "Have a scavenger hunt",
  "Have a talent show",
  "Make cocktails",
  "Make mocktails",
  "Eat cake",
  "Have a potluck",
  "Have a bake-off",
  "Have a cook-off",
  "Have a chili cook-off",
  "Have a BBQ cook-off",
  "Have a cocktail competition",
  "Have a dance competition",
  "Have a karaoke competition",
  "Have a costume contest",
  "Have a beauty contest",
  "Have a trivia competition",
  "Have a spelling bee",
  "Have a poetry slam",
  "Have a stand-up comedy night",
  "Have a game show night",
  "Have a movie night",
  "Have a board game night",
  "Have a card game night",
  "Have a sports night",
  "Have a video game tournament",
  "Have a pool tournament",
  "Have a poker tournament",
  "Have a beer tasting",
  "Have a wine tasting",
  "Have a cocktail tasting",
  "Have a chocolate tasting",
  "Have a cheese tasting",
  "Have a fondue party",
  "Have a sushi party",
  "Have a taco bar",
  "Have a pizza party",
  "Have a burger bar",
  "Have a hot dog bar",
  "Have a fondue party",
  "Have a brunch party",
  "Have a breakfast for dinner party",
  "Have a dessert bar",
  "Have a candy bar",
  "Have a chocolate fountain",
  "Have a popcorn bar",
  "Have a nacho bar",
  "Have a guacamole bar",
  "Have a salsa bar",
  "Have a beer and cheese pairing party",
  "Have a wine and cheese pairing party",
  "Have a cheese fondue party",
  "Have a cocktail party",
  "Have a garden party",
  "Have a tea party",
  "Have a coffee tasting",
  "Have a craft beer tasting",
  "Have a Scotch tasting",
  "Have a bourbon tasting",
  "Have a whiskey tasting",
  "Have a rum tasting",
  "Have a gin tasting",
  "Have a vodka tasting",
  "Have a tequila tasting",
  "Have a sake tasting",
  "Have a margarita party",
  "Have a mojito party",
  "Have a martini party",
  "Have a sangria party",
  "Have a beer and pizza party",
  "Have a wine and cheese party",
  "Have a hot tub party",
  "Have a spa party",
  "Have a nail party",
  "Have a makeup party",
  "Have a hair styling party",
  "Have a massage party",
  "Selfie at the Grand Canyon: 'Did you even see it?'",
  "Wine tasting: 'Suddenly, you're a sommelier.'",
  "Clubbing till 4 am: 'Sleep is for the weak.'",
  "Skydiving: 'Because jumping off cliffs is too 1600s.'",
  "Vegan potluck: 'Tofu, anyone?'",
  "Hot yoga: 'Sweating in unison, how fun.'",
  "Karaoke: 'Everyone’s a star, especially you, Karen.'",
  "Netflix binge: 'Because outside is overrated.'",
  "Artisanal coffee: 'Ten bucks a sip.'",
  "Museum selfies: 'Van Gogh would’ve Instagrammed, too.'",
  "Farmers' market: 'Overpay for authenticity.'",
  "Virtual reality: 'Fake worlds, real nausea.'",
  "Camping: 'Who needs a 5-star hotel?'",
  "Paintball: 'War games but make it colorful.'",
  "Pub crawl: 'Because one regret isn’t enough.'",
  "Pumpkin spice latte: 'It’s fall somewhere.'",
  "Couples' cooking class: 'Arguing, but with knives.'",
  "Meditation retreat: 'Pay to sit and think.'",
  "Crossfit: 'Where pain meets cult.'",
  "Escape room: 'Simulated stress for kicks.'",
  "Scavenger hunt: 'You too can be Sherlock.'",
  "Food trucks: 'Gourmet comes on wheels now.'",
  "Dog yoga: 'Because Fido needs inner peace.'",
  "Indoor trampolining: 'Childhood, but with waivers.'",
  "Rollercoasters: 'Nothing says fun like nausea.'",
  "Costume parties: 'Identity crisis as entertainment.'",
  "Rock climbing: 'Defy gravity, embrace emergency rooms.'",
  "Silent disco: 'Awkwardness, now with headphones.'",
  "Go-karting: 'Because road rage isn’t enough.'",
  "Adult coloring books: 'Stay within the lines.'",
  "Murder mystery dinner: 'Eat, drink, be suspicious.'",
  "Arcade games: 'Where quarters go to die.'",
  "DIY crafts: 'Pinterest fails are a genre.'",
  "Glow-in-the-dark bowling: 'Miss pins, but make it rave.'",
  "LARPing: 'Your mom’s basement, but epic.'",
  "Flash mob: 'Sudden dance epidemic strikes city.'",
  "SoulCycle: 'A cult with better music.'",
  "Fishing: 'For people who like wet boredom.'",
  "Lawn games: 'Cornhole, the sport of kings.'",
  "Extreme ironing: 'Pressing clothes on mountaintops.'",
  "Mixology class: 'Because you’re too fancy for beer.'",
  "Beach volleyball: 'Sunburns and spikes.'",
  "Pottery class: 'Ghost, but without Patrick Swayze.'",
  "Ice sculpture: 'Art, but with a timer.'",
  "Charades: 'A mime’s paradise.'",
  "Geocaching: 'Treasure hunting for the GPS era.'",
  "Ballroom dancing: 'Footwork and forced smiles.'",
  "Sushi-making class: 'Play with your food.'",
  "Ziplining: 'Because walking is too mainstream.'",
  "Gardening: 'It’s like FarmVille, but sweaty.'",
  "Parasailing: 'Flying, but make it risky.'",
  "Origami: 'How to weaponize paper.'",
  "Candle-making: 'Wax poetic.'",
  "Hula hooping: 'The circle of life.'",
  "Astronomy: 'Stars, but no red carpet.'",
  "Photo booth: 'Narcissism, now in strips.'",
  "Metal detecting: 'Beep, beep, it’s a bottle cap.'",
  "Adult dodgeball: 'Elementary school, but with grudges.'",
  "Whale watching: 'SeaWorld, but ethical.'",
  "Segway tours: 'Walking’s for peasants.'",
  "Slacklining: 'Tightrope for millennials.'",
  "Parkour: 'Because walking is too simple.'",
  "Indoor skiing: 'Climate change, but fun.'",
  "Laser tag: 'Pew pew, you’re dead.'",
  "Foodie tour: 'Instagram with a side of fries.'",
  "Underwater basket weaving: 'As useful as it sounds.'",
  "Calligraphy: 'Fancy handwriting, plain errors.'",
  "Antiquing: 'One man’s trash.'",
  "Quidditch: 'Harry Potter, but more concussions.'",
  "Kite flying: 'Hope it doesn’t fly away.'",
  "Petting zoo: 'Sanitized fur, pure joy.'",
  "Speed dating: 'Quick hellos, quicker goodbyes.'",
  "River rafting: 'Splashes and liabilities.'",
  "Mini golf: 'Less skill, more windmills.'",
  "Juice cleanse party: 'Starvation’s more fun with friends.'",
  "Sandcastle building: 'Architect dreams, tide’s nightmare.'",
  "Barista course: 'Foam art, steep price.'",
  "Comedy club: 'Laughter or awkward silence.'",
  "Snorkeling: 'Aquarium, but you’re the fish.'",
  "Mime class: 'Say nothing, express everything.'",
  "Improv: 'Make it up as you fail.'",
  "Fire twirling: 'Pyromania, but make it an art.'",
  "Drone racing: 'The sky’s the limit, sort of.'",
  "Slamming doors",
  "Yelling at inanimate objects",
  "Kicking a wall",
  "Stomping feet",
  "Sarcastic clapping",
  "Throwing a phone",
  "Fuming in silence",
  "Punching a pillow",
  "Muting everyone on a Zoom call",
  "Unfriending on social media",
  "Speeding while driving",
  "Snapping a pencil",
  "Aggressively doing dishes",
  "Passive-aggressive texting",
  "Blaring angry music",
  "Swearing under breath",
  "Venting on Twitter",
  "Rolling eyes dramatically",
  "Over-exercising",
  "Rapid-fire keyboard typing",
  "Smashing a vase",
  "Giving the silent treatment",
  "Storming out of a room",
  "Tearing up a photo",
  "Canceling plans last minute",
  "Burning old letters",
  "Dramatic sighing",
  "Aggressively swiping on dating apps",
  "Angrily clicking a pen",
  "Cutting off conversations",
  "Eating junk food",
  "Pacing back and forth",
  "Flicking lights on and off",
  "Ignoring calls",
  "Hitting 'unsubscribe' on emails",
  "Blocking numbers",
  "Staring intensely",
  "Ranting to a pet",
  "Sudden cleaning spree",
  "Huffing and puffing",
  "Slapping a table",
  "Angrily doing push-ups",
  "Gritting teeth",
  "Shaking a fist",
  "Rehearsing confrontations",
  "Stomping away",
  "Impatiently tapping feet",
  "Crumpling papers",
  "Shutting down a computer",
  "Yanking out earphones",
  "Roughly zipping a bag",
  "Impulsively shopping online",
  "Screaming into a pillow",
  "Hitting the gym",
  "Ripping a book",
  "Scratching a surface",
  "Aggressively brushing teeth",
  "Unplugging devices",
  "Ignoring texts",
  "Crushing a soda can",
  "Flipping a table",
  "Scowling at everyone",
  "Sudden urge to rearrange furniture",
  "Deleting contacts",
  "Banging on a desk",
  "Walking out of a meeting",
  "Hanging up mid-call",
  "Speed-walking",
  "Tossing clothes around",
  "Swearing at a video game",
  "Revving a car engine",
  "Leaving a nasty review",
  "Rapid channel-changing",
  "Pouring a stiff drink",
  "Snubbing someone",
  "Hurling a baseball",
  "Switching off the TV",
  "Eyerolling at emails",
  "Throwing hands in the air",
  "Storming off a sports field",
  "Jamming a door shut",
  "Sarcastically laughing",
  "Kicking up dust",
  "Rapidly exiting an app",
  "Stubbing out a cigarette",
  "Drowning out noise with earbuds",
  "Angrily jotting notes",
  "Snapping a rubber band",
  "Shredding documents",
  "Scrubbing a floor",
  "Smacking a punching bag",
  "Aggressively scrolling",
  "Quickly swiping credit cards",
  "Chopping vegetables hard",
  "Disconnecting Wi-Fi",
  "Revoking shared access",
  "Erasing a chalkboard",
  "Striking a match",
  "Logging out of social accounts",
  "Closing all tabs",
    "Writing love letters",
  "Staring into each other's eyes",
  "Planning surprise dates",
  "Cooking favorite meals",
  "Holding hands",
  "Sharing playlists",
  "Kissing in the rain",
  "Watching sunsets together",
  "Buying meaningful gifts",
  "Midnight phone calls",
  "Taking couple selfies",
  "Saying 'I love you'",
  "Posting 'in a relationship'",
  "Introducing to family",
  "Walking the dog together",
  "Random acts of kindness",
  "Sharing secrets",
  "Dreaming about the future",
  "Writing poetry",
  "Traveling together",
  "Constant texting",
  "Watching romantic movies",
  "Celebrating anniversaries",
  "Getting jealous",
  "Singing love songs",
  "Building a fort",
  "Saving mementos",
  "Taking a bubble bath",
  "Creating couple traditions",
  "Getting matching tattoos",
  "Dancing in the kitchen",
  "Planning picnics",
  "Crying happy tears",
  "Volunteering together",
  "Stargazing",
  "Hugging for long periods",
  "Finding constellations",
  "Discussing baby names",
  "Cuddling on the couch",
  "Reading together",
  "Leaving love notes",
  "Kissing goodnight",
  "Sleeping in each other’s arms",
  "Being protective",
  "Complimenting regularly",
  "Making sacrifices",
  "Creating art together",
  "Going for hikes",
  "Listening intently",
  "Feeling butterflies",
  "Saying 'I miss you'",
  "Embracing flaws",
  "Doing household chores",
  "Nervous first meetings",
  "Capturing candid photos",
  "Ignoring distractions",
  "Discussing deepest fears",
  "Expressing vulnerability",
  "Getting lost together",
  "Synchronizing schedules",
  "Enjoying silence",
  "Making funny faces",
  "Reminiscing about the past",
  "Acting like teenagers",
  "Feeding each other",
  "Helping with work",
  "Getting over arguments",
  "Locking pinkies",
  "Memorizing preferences",
  "Sharing clothes",
  "Celebrating small wins",
  "Taking care when sick",
  "Exchanging glances",
  "Making nicknames",
  "Keeping promises",
  "Planting a garden",
  "Giggling uncontrollably",
  "Setting couple goals",
  "Buying a pet",
  "Adventurous escapades",
  "Carrying each other’s bags",
  "Dedicating songs",
  "Attending events",
  "Rearranging plans",
  "Building a home",
  "Leaning on each other",
  "Making compromises",
  "Saying sorry",
  "Waking up early",
  "Staying up late",
  "Watching each other sleep",
  "Giving space",
  "Feeling complete",
  "Saying ‘us’ and ‘we’",
  "Trying new things",
  "Comforting during grief",
  "Painting a picture",
  "Renewing vows",
  "Ending calls reluctantly",
  "Praying together"
  ]