export default [  
"Wide-angle",  
"Very Wide-angle",  
"webcam",  
"ceiling-cam",  
"Medium-angle",  
"Medium Close-Up",  
"Close-Up",  
"Close-Up",  
"Over-The-Shoulder",  
"Point of View",  
"Low-Angle",  
"High Angle",  
"Dutch Angle",  
"Bird's Eye View",  
"Aerial",  
"Tracking-shot",  
"Crane-shot",  
"Steadicam",  
"Handheld",  
"Zoomshot"]
