export default [
"Adrian Alphona",
"Adrian Piper",
"Agnes Martin",
"Ai Weiwei",
"Al Hirschfeld",
"Alberto Giacometti",
"Albrecht Durer",
"Alex Katz",
"Alex Ross",
"Alex Toth",
"Amedeo Modigliani",
"Andy Goldsworthy",
"Andy Kubert",
"Andy Warhol",
"Anish Kapoor",
"Ansel Adams",
"Anselm Kiefer",
"Antony Gormley",
"Arnold Bocklin",
"Art Spiegelman",
"Ashley Wood",
"Balthus",
"Banksy",
"Barbara Hepworth",
"Basquiat",
"Beatrix Potter",
"Benoy Sarkar",
"Berthe Morisot",
"Bill Sienkiewicz",
"Brian Bolland",
"Brian K. Vaughan",
"Brice Marden",
"Bridget Riley",
"Cai Guo-Qiang",
"Camille Claudel",
"Caravaggio",
"Carrie Mae Weems",
"Caspar David Friedrich",
"Catherine Opie",
"Charles Burns",
"Chen Chengbo",
"Chris Ware",
"Christo and Jeanne-Claude",
"Chu Teh-Chun",
"Chuck Close",
"Cindy Sherman",
"Claes Oldenburg",
"Claude Cahun",
"Claude Monet",
"Cliff Chiang",
"Cy Twombly",
"Damien Hirst",
"Daniel Arsham",
"Daniel Buren",
"Dave Gibbons",
"Dave McKean",
"David Aja",
"David Hockney",
"David Mazzucchelli",
"David Smith",
"Dean Ormston",
"Diego Rivera",
"Diego Velazquez",
"Don Rosa",
"Donald Judd",
"Dr. Seuss",
"Dustin Nguyen",
"Ed Brubaker",
"Ed Ruscha",
"Edgar Degas",
"Edvard Munch",
"Edward Hopper",
"Egon Schiele",
"El Anatsui",
"Ellsworth Kelly",
"Eric Powell",
"Esad Ribic",
"Eugene Delacroix",
"Eva Hesse",
"Faith Ringgold",
"Fang Lijun",
"Fiona Staples",
"Francisco de Zurbaran",
"Frank Gehry",
"Frank Miller",
"Frank Stella",
"Frans Hals",
"Frederic Remington",
"Frida Kahlo",
"Frédéric Bazille",
"Fu Baoshi",
"Gabriel Ba",
"Geof Darrow",
"George Grosz",
"George Perez",
"Georges Braque",
"Georges Seurat",
"Georgia O'Keeffe",
"Georgia O’Keeffe",
"Gerhard Richter",
"Gilbert Hernandez",
"Giovanni Bellini",
"Goya",
"Grant Morrison",
"Greg Capullo",
"Gu Wenda",
"Gustav Klimt",
"Hans Bellmer",
"Hans Holbein the Younger",
"Hayao Miyazaki",
"Helen Frankenthaler",
"Henri Cartier-Bresson",
"Henri de Toulouse-Lautrec",
"Henri Matisse",
"Hergé",
"Hokusai",
"Horace Pippin",
"Howard Hodgkin",
"Huang Rui",
"Huang Yongping",
"Humberto Ramos",
"Ida Applebroog",
"Isamu Noguchi",
"J.H. Williams III",
"J.M.W. Turner",
"Jack Kirby",
"Jackson Pollock",
"James Jean",
"James Rosenquist",
"James Turrell",
"Jamie Hewlett",
"Jan Vermeer",
"Jason Aaron",
"Jasper Johns",
"Jean Arp",
"Jean Dubuffet",
"Jean-Michel Basquiat",
"Jeff Koons",
"Jeff Lemire",
"Jenny Holzer",
"Jenny Holzer",
"Jessica Walsh",
"Jim Dine",
"Jim Lee",
"Joan Miro",
"Joan Miró",
"Joan Mitchell",
"Joe Madureira",
"Johannes Vermeer",
"John Baldessari",
"John Byrne",
"John Cage",
"John Constable",
"John Heartfield",
"John Romita Jr.",
"John Singer Sargent",
"Jordi Bernet",
"Jorge Jimenez",
"Joseph Beuys",
"Joseph Cornell",
"Judy Chicago",
"Jules Feiffer",
"Julie Mehretu",
"Kara Walker",
"Kathe Kollwitz",
"Kehinde Wiley",
"Keith Giffen",
"Keith Haring",
"Kerry James Marshall",
"Kieron Gillen",
"Kiki Smith",
"Kurt Busiek",
"Lee Bermejo",
"Lee Krasner",
"Leonardo da Vinci",
"Li Keran",
"Li Shan",
"Lin Fengmian",
"Liu Bolin",
"Liu Wei",
"Liu Xiaodong",
"Louise Bourgeois",
"Louise Nevelson",
"Lucian Freud",
"Luo Zhongli",
"Man Ray",
"Marc Chagall",
"Marcel Duchamp",
"Marina Abramovic",
"Mark Millar",
"Mark Rothko",
"Mary Cassatt",
"Max Ernst",
"Max Fleisher",
"Meret Oppenheim",
"Michael Bierut",
"Michelangelo",
"Mike Mignola",
"Molly McCoy",
"Nam June Paik",
"Nan Goldin",
"Neal Adams",
"Neil Gaiman",
"Niki de Saint Phalle",
"Norman Rockwell",
"Olafur Eliasson",
"Olivier Coipel",
"Oscar Claude Monet",
"Otomo Katsuhiro",
"P. Craig Russell",
"Pablo Picasso",
"Paul Cezanne",
"Paul Cézanne",
"Paul Gauguin",
"Paul Klee",
"Paul Pope",
"Peter Paul Rubens",
"Phil Noto",
"Philip Guston",
"Pierre Bonnard",
"Piet Mondrian",
"Qi Baishi",
"Qiu Zhijie",
"Quentin Blake",
"Rachel Harrison",
"Rachel Whiteread",
"Rafael Albuquerque",
"Raymond Pettibon",
"Rembrandt",
"Ren Bonian",
"Ren Xiong",
"Rene Magritte",
"René Magritte",
"Richard Diebenkorn",
"Richard Hamilton",
"Richard Serra",
"Robert Gober",
"Robert Indiana",
"Robert Morris",
"Robert Motherwell",
"Robert Rauschenberg",
"Robert Ryman",
"Romare Bearden",
"Rosalba Carriera",
"Rosalyn Drexler",
"Roy Lichtenstein",
"Rumiko Takahashi",
"Ryan Ottley",
"Salvador Dali",
"Salvadore Dali",
"Sanford Biggers",
"Sanyu",
"Sara Pichelli",
"Sarah Sze",
"Scott McCloud",
"Sean Phillips",
"Shi Guorui",
"Skottie Young",
"Sol LeWitt",
"Sonia Delaunay",
"Sophie Calle",
"Stan Lee",
"Stuart Immonen",
"Takashi Murakami",
"Terry Adkins",
"Terry Moore",
"Thomas Eakins",
"Thomas Hart Benton",
"Tina Modotti",
"Titian",
"Todd McFarlane",
"Tom Wesselmann",
"Tracey Emin",
"Trina Robbins",
"Urs Fischer",
"Vermeer",
"Vija Celmins",
"Vincent van Gogh",
"Vito Acconci",
"Walt Simonson",
"Wang Guangyi",
"Wang Meng",
"Wassily Kandinsky",
"Will Eisner",
"Willem de Kooning",
"William Blake",
"William Eggleston",
"Winslow Homer",
"Wolfgang Tillmans",
"Wu Changshuo",
"Wu Guanzhong",
"Xu Beihong",
"Xu Bing",
"Xu Shiqi",
"Xu Zhen",
"Yan Pei-Ming",
"Yang Fudong",
"Yayoi Kusama",
"Yinka Shonibare",
"Yoko Ono",
"Yoshihiro Togashi",
"Yue Minjun",
"Yukito Kishiro",
"Yusuke Murata",
"Zaha Hadid",
"Zander Cannon",
"Zao Wou-Ki",
"Zarina Hashmi",
"Zeng Fanzhi",
"Zhan Wang",
"Zhang Huan",
"Zhang Xiaogang",
"Zhou Chunya",
"Zhu Jinshi"
];
