export default [
  "Toni Morrison",
  "Ernest Hemingway",
  "F. Scott Fitzgerald",
  "William Faulkner",
  "Sylvia Plath",
  "T.S. Eliot",
  "James Baldwin",
  "Langston Hughes",
  "J.D. Salinger",
  "Flannery O'Connor",
  "John Steinbeck",
  "Arthur Miller",
  "E.E. Cummings",
  "Gertrude Stein",
  "Robert Frost",
  "Wallace Stevens",
  "Richard Wright",
  "Zora Neale Hurston",
  "Ralph Ellison",
  "Raymond Carver",
  "Jack Kerouac",
  "Allen Ginsberg",
  "Truman Capote",
  "John Updike",
  "Philip Roth",
  "James Dickey",
  "Joyce Carol Oates",
  "Norman Mailer",
  "William S. Burroughs",
  "Gwendolyn Brooks",
  "Maya Angelou",
  "Richard Yates",
  "Edward Albee",
  "Eudora Welty",
  "Carson McCullers",
  "Kurt Vonnegut",
  "Saul Bellow",
  "Florine Stettheimer",
  "Amy Tan",
  "Donald Barthelme",
  "Robert Penn Warren",
  "Tennessee Williams",
  "S.E. Hinton",
  "John Cheever",
  "John Dos Passos",
  "William Styron",
  "Upton Sinclair",
  "John Ashbery",
  "Robert Lowell",
  "Allen Tate",
  "Frank O'Hara",
  "Elizabeth Bishop",
  "Willa Cather",
  "Edith Wharton",
  "Marjorie Kinnan Rawlings",
  "Thornton Wilder",
  "Gore Vidal",
  "Henry Miller",
  "William Gaddis",
  "John Gardner",
  "Richard Brautigan",
  "Thomas Pynchon",
  "William Carlos Williams",
  "Charles Bukowski",
  "Joseph Heller",
  "Lillian Hellman",
  "Edna St. Vincent Millay",
  "Ken Kesey",
  "Ralph Waldo Ellison",
  "Annie Dillard",
  "Joy Williams",
  "Ursula K. Le Guin",
  "Tom Wolfe",
  "John Irving",
  "Don DeLillo",
  "Alice Walker",
  "Marilynne Robinson",
  "David Foster Wallace",
  "Jhumpa Lahiri",
  "Junot Diaz",
  "Tobias Wolff",
  "Michael Chabon",
  "Jonathan Franzen",
  "T.C. Boyle",
  "Jennifer Egan",
  "Chimamanda Ngozi Adichie",
  "Zadie Smith",
  "Cormac McCarthy",
  "Denis Johnson",
  "Junot Díaz",
  "Sandra Cisneros",
  "Edward Abbey",
  "Joy Harjo",
  "Toni Cade Bambara",
   "Jamaica Kincaid",
  "Philip K. Dick",
  "Katherine Anne Porter",
  "Dorothy Parker",
  "Ralph Ellison",
  "Isaac Bashevis Singer",
  "Robert A. Heinlein",
  "Flannery O'Connor",
  "Susan Sontag",
  "William Gibson",
  "Cormac McCarthy",
  "Ray Bradbury",
  "Ursula K. Le Guin",
  "John Steinbeck",
  "Ernest Gaines",
  "Tennessee Williams",
  "James Baldwin",
  "Gabriel Garcia Marquez",
  "Jack Kerouac",
  "Gary Snyder",
  "Joyce Carol Oates",
  "Saul Bellow",
  "Alice Walker",
  "Gore Vidal",
  "James Michener",
  "Stephen King",
  "Richard Ford",
  "J.D. Salinger",
  "Paul Auster",
  "Samuel Beckett",
  "William Burroughs",
  "Norman Mailer",
  "Arthur Miller",
  "August Wilson",
  "E.L. Doctorow",
  "Philip Roth",
  "John Cheever",
  "Elmore Leonard",
  "Edward Abbey",
  "Tom Robbins",
  "Joseph Heller",
  "Toni Morrison",
  "Eudora Welty",
  "Edgar Allan Poe",
  "Vladimir Nabokov",
  "Ken Kesey",
  "Truman Capote",
  "John Updike",
  "Bernard Malamud",
  "Robert Penn Warren",
  "N. Scott Momaday",
  "William Kennedy",
  "Dorothy Allison",
  "James T. Farrell",
  "Robert Coover",
  "Jorie Graham",
  "Denis Johnson",
  "Lorrie Moore",
  "David Foster Wallace",
  "Junot Díaz",
  "Tom Wolfe",
  "Anne Tyler",
  "Michael Cunningham",
  "Jennifer Egan",
  "Rick Moody",
  "Richard Powers",
  "Jonathan Franzen",
  "Jonathan Lethem",
  "Don DeLillo",
  "Joy Harjo",
  "Edwidge Danticat",
  "Tobias Wolff",
  "Marilynne Robinson",
  "Anthony Burgess",
  "William Gass",
  "Vonnegut",
  "Russell Banks",
  "Thomas Pynchon",
  "William H. Gass",
  "Flannery O'Connor",
  "Hunter S. Thompson",
  "Nelson Algren",
  "William Faulkner",
  "Kate Chopin",
  "Robert Frost",
  "Gwendolyn Brooks",
  "Rita Dove",
  "James Welch",
  "Octavia Butler",
  "Sherman Alexie",
  "Louise Erdrich",
  "Sandra Cisneros",
  "David Mamet",
  "Adrienne Rich",
  "Raymond Carver",
  "Carl Sandburg",
  "James Agee",
  "Sylvia Plath",
  "Allen Ginsberg",
  "Langston Hughes",
  "Amiri Baraka",
  "Bob Dylan",
  "Walt Whitman"
]