export default [ "The Beatles",
  "The Rolling Stones",
  "The Who",
  "The Beach Boys",
  "The Doors",
  "The Kinks",
  "The Byrds",
  "The Mamas & the Papas",
  "The Jimi Hendrix Experience",
  "Led Zeppelin",
  "The Grateful Dead",
  "The Velvet Underground",
  "Cream",
  "The Yardbirds",
  "The Animals",
  "The Monkees",
  "The Turtles",
  "The Hollies",
  "The Zombies",
  "The Spencer Davis Group",
  "The Small Faces",
  "The Pretty Things",
  "The Creation",
  "The Shadows",
  "The Searchers",
  "The Dave Clark Five",
  "The Merseybeats",
  "The Four Tops",
  "The Supremes",
  "The Temptations",
  "The Miracles",
  "Marvin Gaye",
  "The Isley Brothers",
  "The Impressions",
  "The Drifters",
  "The Coasters",
  "The Chiffons",
  "The Ronettes",
  "The Shirelles",
  "The Crystals",
  "The Dixie Cups",
  "The Marvelettes",
  "The Chantels",
  "The Platters",
  "The Four Seasons",
  "The Righteous Brothers",
  "The Association",
  "The Rascals",
  "The Buckinghams",
  "The Grass Roots",
  "The Box Tops",
  "The Strawberry Alarm Clock",
  "The Electric Prunes",
  "The 13th Floor Elevators",
  "The Seeds",
  "The Standells",
  "The Music Machine",
  "The Count Five",
  "The Sonics",
  "The Wailers",
  "The Paul Butterfield Blues Band",
  "The Electric Flag",
  "Big Brother and the Holding Company",
  "Jefferson Airplane",
  "The Grateful Dead",
  "The Quicksilver Messenger Service",
  "The Charlatans",
  "The Mothers of Invention",
  "The Beau Brummels",
  "The Youngbloods",
  "The Lovin' Spoonful",
  "The Butterfield Blues Band",
  "The Blues Project",
  "The Fugs",
  "The Holy Modal Rounders",
  "The Incredible String Band",
  "The Byrds",
  "The Flying Burrito Brothers",
  "The International Submarine Band",
  "The Dillards",
  "The Country Gentlemen",
  "The Kentucky Colonels",
  "The New Lost City Ramblers",
  "The Jim Kweskin Jug Band",
  "The Rooftop Singers",
  "The Kingston Trio",
  "The Limeliters",
  "The Chad Mitchell Trio",
  "Peter, Paul and Mary",
  "Joan Baez",
  "Bob Dylan",
  "The Band",
  "The Allman Brothers Band",
  "The Grateful Dead",
  "The Doors",
  "Cream",
  "Jimi Hendrix",
  "The Who",
  "Led Zeppelin",
  "The Rolling Stones",
  "The Beatles",
  "The Kinks",
  "The Byrds",
  "The Mamas & the Papas",
  "Simon & Garfunkel",
  "The Beach Boys",
  "The Turtles",
  "The Hollies",
  "The Zombies",
  "The Animals",
  "Led Zeppelin",
  "Pink Floyd",
  "The Rolling Stones",
  "The Who",
  "Black Sabbath",
  "Deep Purple",
  "AC/DC",
  "Queen",
  "The Eagles",
  "Lynyrd Skynyrd",
  "ZZ Top",
  "Fleetwood Mac",
  "The Allman Brothers Band",
  "The Doors",
  "Jimi Hendrix",
  "The Kinks",
  "The Clash",
  "Ramones",
  "Sex Pistols",
  "The Buzzcocks",
  "The Damned",
  "The Jam",
  "The Police",
  "Talking Heads",
  "Blondie",
  "The New York Dolls",
  "Television",
  "Iggy Pop and the Stooges",
  "MC5",
  "The Velvet Underground",
  "The Modern Lovers",
  "Patti Smith Group",
  "The Runaways",
  "The B-52's",
  "The Cars",
  "Boston",
  "Foreigner",
  "Journey",
  "Kansas",
  "Styx",
  "Van Halen",
  "Alice Cooper",
  "Kiss",
  "The Sweet",
  "Thin Lizzy",
  "UFO",
  "Yes",
  "Genesis",
  "Emerson, Lake & Palmer",
  "Jethro Tull",
  "The Moody Blues",
  "Supertramp",
  "Chicago",
  "Earth, Wind & Fire",
  "The Commodores",
  "The Jackson 5",
  "The Bee Gees",
  "ABBA",
  "Fleetwood Mac",
  "The Doobie Brothers",
  "Steely Dan",
  "War",
  "The Temptations",
  "The Spinners",
  "The O'Jays",
  "The Stylistics",
  "The Four Tops",
  "The Commodores",
  "The Pointer Sisters",
  "The Emotions",
  "Sly and the Family Stone",
  "Parliament-Funkadelic",
  "James Brown",
  "Isaac Hayes",
  "Al Green",
  "Marvin Gaye",
  "Stevie Wonder",
  "The Ohio Players",
  "The Isley Brothers",
  "The Average White Band",
  "Tower of Power",
  "Blood, Sweat & Tears",
  "The Ides of March",
  "Steppenwolf",
  "Blue Öyster Cult",
  "Ted Nugent",
  "Uriah Heep",
  "The Scorpions",
  "Rainbow",
  "Rush",
  "The Doobie Brothers",
  "Steely Dan",
  "Warren Zevon",
  "Tom Petty and the Heartbreakers",
  "Heart",
  "Fleetwood Mac",
  "The Cars",
  "Aerosmith",
  "Van Halen",
  "AC/DC",
  "Kiss",
  "The Ramones",
  "The Sex Pistols",
  "The Clash",
  "The Talking Heads",
  "Joy Division",
  "The Cure",
  "Siouxsie and the Banshees",
  "The Damned",
  "Wire",
  "The Buzzcocks",
  "The Stranglers",
   "U2",
  "The Smiths",
  "The Cure",
  "Joy Division",
  "New Order",
  "Depeche Mode",
  "Talking Heads",
  "R.E.M.",
  "The Police",
  "Duran Duran",
  "Tears for Fears",
  "A-ha",
  "Pet Shop Boys",
  "The B-52's",
  "The Pretenders",
  "Blondie",
  "The Go-Go's",
  "Madonna",
  "Cyndi Lauper",
  "Whitney Houston",
  "Prince",
  "Michael Jackson",
  "David Bowie",
  "The Rolling Stones",
  "AC/DC",
  "Guns N' Roses",
  "Van Halen",
  "Metallica",
  "Iron Maiden",
  "Judas Priest",
  "Motley Crue",
  "Def Leppard",
  "Bon Jovi",
  "Queen",
  "Kiss",
  "The Cult",
  "The Psychedelic Furs",
  "Echo & The Bunnymen",
  "Siouxsie and the Banshees",
  "The Sisters of Mercy",
  "The Mission UK",
  "The Church",
  "The Waterboys",
  "The Housemartins",
  "The Stone Roses",
  "The Jesus and Mary Chain",
  "The Pixies",
  "Sonic Youth",
  "Hüsker Dü",
  "The Replacements",
  "R.E.M.",
  "The Go-Betweens",
  "The Smithereens",
  "XTC",
  "The Jam",
  "The Style Council",
  "The Specials",
  "UB40",
  "The English Beat",
  "The Selecter",
  "The Human League",
  "Gary Numan",
  "Yazoo",
  "Eurythmics",
  "Orchestral Manoeuvres in the Dark",
  "Devo",
  "Spandau Ballet",
  "ABC",
  "Heaven 17",
  "Talk Talk",
  "Simple Minds",
  "Big Country",
  "The Alarm",
  "Echo & the Bunnymen",
  "The Mission UK",
  "The Cult",
  "The Sisters of Mercy",
  "The Jesus and Mary Chain",
  "The Fall",
  "Wire",
  "Public Image Ltd",
  "The Clash",
  "The Damned",
  "The Dead Kennedys",
  "Minor Threat",
  "Bad Brains",
  "Black Flag",
  "Hüsker Dü",
  "The Replacements",
  "Soul Asylum",
  "The Lemonheads",
  "Dinosaur Jr.",
  "The Meat Puppets",
  "Soundgarden",
  "Nirvana",
  "Jane's Addiction",
  "Red Hot Chili Peppers",
  "Faith No More",
  "The Cure",
  "The Smiths",
  "New Order",
  "Depeche Mode",
  "The Psychedelic Furs",
  "Echo & The Bunnymen",
  "Siouxsie and the Banshees",
  "Nirvana",
  "Pearl Jam",
  "Soundgarden",
  "Alice in Chains",
  "Stone Temple Pilots",
  "Green Day",
  "Weezer",
  "Smashing Pumpkins",
  "Radiohead",
  "Oasis",
  "Blur",
  "Pulp",
  "Suede",
  "Supergrass",
  "The Verve",
  "The Cranberries",
  "R.E.M.",
  "The Pixies",
  "Sonic Youth",
  "Nine Inch Nails",
  "Beck",
  "Red Hot Chili Peppers",
  "Faith No More",
  "Tool",
  "Metallica",
  "Guns N' Roses",
  "Pantera",
  "Slayer",
  "Megadeth",
  "Korn",
  "Limp Bizkit",
  "Rage Against the Machine",
  "System of a Down",
  "Deftones",
  "The Offspring",
  "NOFX",
  "Bad Religion",
  "Pennywise",
  "The Mighty Mighty Bosstones",
  "Less Than Jake",
  "Goldfinger",
  "Face to Face",
  "NOFX",
  "Bad Religion",
  "Pennywise",
  "The Mighty Mighty Bosstones",
  "Less Than Jake",
  "Goldfinger",
  "Face to Face",
  "Foo Fighters",
  "Screaming Trees",
  "Helmet",
  "Hum",
  "The Jesus Lizard",
  "Slint",
  "My Bloody Valentine",
  "Slowdive",
  "Swervedriver",
  "Mazzy Star",
  "Portishead",
  "Massive Attack",
  "Tricky",
  "Björk",
  "The Cardigans",
  "Garbage",
  "No Doubt",
  "The Smashing Pumpkins",
  "Alanis Morissette",
  "Jewel",
  "Sheryl Crow",
  "Rage Against the Machine",
  "Public Enemy",
  "Cypress Hill",
  "Beastie Boys",
  "Wu-Tang Clan",
  "N.W.A.",
  "Ice Cube",
  "Tupac",
  "Notorious B.I.G.",
  "Dr. Dre",
  "Snoop Dogg",
  "A Tribe Called Quest",
  "De La Soul",
  "The Fugees",
  "Outkast",
  "Radiohead",
  "The Verve",
  "Blur",
  "Oasis",
  "The Chemical Brothers",
  "The Prodigy",
  "Fatboy Slim",
  "Daft Punk",
  "The Crystal Method",
  "Underworld",
  "Orbital",
  "The Orb",
  "Leftfield",
  "Massive Attack",
  "Tricky",
  "Portishead",
  "Goldie",
  "LTJ Bukem",
  "DJ Shadow",
  "Aphex Twin",
  "Squarepusher",
  "Boards of Canada",
  "Moby",
  "The Future Sound of London",
  "Autechre",
  "Kraftwerk",
  "Gary Numan",
  "New Order",
  "Depeche Mode",
  "The Cure",
  "Siouxsie and the Banshees",
   "The Strokes",
  "Arctic Monkeys",
  "Interpol",
  "Yeah Yeah Yeahs",
  "The White Stripes",
  "The Black Keys",
  "Modest Mouse",
  "TV on the Radio",
  "Death Cab for Cutie",
  "Bright Eyes",
  "The Postal Service",
  "Vampire Weekend",
  "Phoenix",
  "The Shins",
  "Sufjan Stevens",
  "The Decemberists",
  "Fleet Foxes",
  "Band of Horses",
  "Iron & Wine",
  "Animal Collective",
  "MGMT",
  "LCD Soundsystem",
  "The National",
  "Arcade Fire",
  "Radiohead",
  "Coldplay",
  "Muse",
  "Keane",
  "Snow Patrol",
  "The Killers",
  "Kings of Leon",
  "Franz Ferdinand",
  "Bloc Party",
  "The Libertines",
  "The Hives",
  "The Vines",
  "Jet",
  "The Dandy Warhols",
  "The Bravery",
  "The Rapture",
  "The Stills",
  "Editors",
  "The Futureheads",
  "Maxïmo Park",
  "We Are Scientists",
  "Wolf Parade",
  "The Walkmen",
  "The Hold Steady",
  "The Gaslight Anthem",
  "The Fratellis",
  "The Kooks",
  "The Zutons",
  "The Coral",
  "The View",
  "Kaiser Chiefs",
  "The Ting Tings",
  "Gorillaz",
  "Beck",
  "The Avalanches",
  "Daft Punk",
  "Justice",
  "LCD Soundsystem",
  "Moby",
  "Röyksopp",
  "Air",
  "Zero 7",
  "Thievery Corporation",
  "Portishead",
  "Massive Attack",
  "Goldfrapp",
  "Sneaker Pimps",
  "Ladytron",
  "The Knife",
  "M83",
  "Sigur Rós",
  "Explosions in the Sky",
  "Godspeed You! Black Emperor",
  "Mono",
  "Russian Circles",
  "Pelican",
  "Red Sparowes",
  "This Will Destroy You",
  "65daysofstatic",
  "Isis",
  "Converge",
  "Neurosis",
  "Deftones",
  "Tool",
  "System of a Down",
  "Slipknot",
  "Mastodon",
  "Opeth",
  "Lamb of God",
  "Between the Buried and Me",
  "The Black Dahlia Murder",
  "As I Lay Dying",
  "Killswitch Engage",
  "Trivium",
  "Avenged Sevenfold",
  "Disturbed",
  "Five Finger Death Punch",
  "Bullet for My Valentine",
  "Atreyu",
  "Underoath",
  "Asking Alexandria",
  "Bring Me the Horizon",
  "Parkway Drive",
  "August Burns Red",
  "Architects",
  "The Devil Wears Prada",
  "A Day to Remember",
  "Escape the Fate",
  "At the Drive-In",
  "The Mars Volta",
  "Queens of the Stone Age",
  "Mastodon",
  "Coheed and Cambria",
  "Circa Survive",
  "Phoebe Bridgers",
  "Japanese Breakfast",
  "Mitski",
  "Snail Mail",
  "King Princess",
  "Clairo",
  "Girl in Red",
  "Beabadoobee",
  "Arlo Parks",
  "Lomelda",
  "Soccer Mommy",
  "Haim",
  "The 1975",
  "Bleachers",
  "Big Thief",
  "Waxahatchee",
  "Adrianne Lenker",
  "Faye Webster",
  "Black Midi",
  "Fontaines D.C.",
  "Idles",
  "Squid",
  "Dry Cleaning",
  "Shame",
  "The Murder Capital",
  "Working Men's Club",
  "Porridge Radio",
  "Black Country, New Road",
  "Lingua Ignota",
  "Yves Tumor",
  "clipping.",
  "Slauson Malone",
  "Moor Mother",
  "Backxwash",
  "Denzel Curry",
  "JPEGMAFIA",
  "slowthai",
  "Rina Sawayama",
  "100 gecs",
  "Charli XCX",
  "Caroline Polachek",
  "Grimes",
  "Tame Impala",
  "The Weeknd",
  "Lizzo",
  "Billie Eilish",
  "Doja Cat",
  "Harry Styles",
  "Dua Lipa",
  "Olivia Rodrigo",
  "BTS",
  "Lil Nas X",
  "Travis Scott",
  "Post Malone",
  "Kendrick Lamar",
  "Tyler, The Creator",
  "Frank Ocean",
  "Kanye West",
  "Childish Gambino",
  "Anderson .Paak",
  "Thundercat",
  "Kaytranada",
  "FKA Twigs",
  "SZA",
  "Solange",
  "Blood Orange",
  "Moses Sumney",
  "Angel Olsen",
  "Bon Iver",
  "James Blake",
  "Vampire Weekend",
  "LCD Soundsystem",
  "Foals",
  "The National",
  "Radiohead",
  "Sigur Rós",
  "Explosions in the Sky",
  "Godspeed You! Black Emperor",
  "Caribou",
  "Bonobo",
  "Flying Lotus",
  "Jon Hopkins",
  "Four Tet",
  "Nicolas Jaar",
  "Floating Points",
  "Kaitlyn Aurelia Smith",
  "Holly Herndon",
  "Oneohtrix Point Never",
  "Tim Hecker",
  "Grouper",
  "William Basinski",
  "Mount Eerie",
  "Sun Kil Moon",
  "Julien Baker",
  "Sufjan Stevens",
  "The Microphones",
  "Giles Corey",
  "Have a Nice Life",
  "Car Seat Headrest",
  "Protomartyr",
  "Owen Pallett",
  "Destroyer",
  "Deerhunter",
  "Parquet Courts",
  "Courtney Barnett",
  "Weyes Blood",
  "Julia Holter",
  "Dirty Projectors",
  "Grizzly Bear",
  "Animal Collective",
  "The War on Drugs",
  "Real Estate",
  "Beach House",
  "Tame Impala"
  ];