export default [
"1 Chronicles",
"1 Kings",
"1 Samuel",
"2 Chronicles",
"2 Kings",
"2 Samuel",
"Aaron's rod",
"Abraham's Bosom",
"Ahab's spirit",
"Altar of burnt offering",
"Amos",
"Anointing oil",
"Ark of Noah",
"Ark of the Covenant",
"Babylon",
"Balaam's donkey",
"Balaam's talking donkey",
"Beelzebul",
"Bowl of incense",
"Brazen Serpent",
"Breastplate of judgment",
"Bronze laver",
"Burning bush",
"Candlestick",
"Cherubim on the ark",
"Cloud of glory",
"Daniel in the lion's den",
"Daniel",
"Daniel's ability to interpret dreams",
"Dead Sea",
"Deuteronomy",
"Ecclesiastes",
"Egypt",
"Elijah's fire from heaven",
"Elisha's floating axe head",
"Elisha's healing of Naaman's leprosy",
"Ephod",
"Esther",
"Exodus",
"Ezekiel",
"Ezekiel's vision",
"Ezra",
"Fiery furnace",
"Garden of Eden",
"Garden of Gethsemane",
"Gates of Hades",
"Gates of Heaven",
"Gates of Jerusalem",
"Gates of Zion",
"Gehenna",
"Genesis",
"Gideon's fleece",
"Golden calf",
"Goliath",
"Gospel of Andrew (Epiphanius Panarion)",
"Gospel of Andrew",
"Gospel of Apelles (Epistle of Titus to the East)",
"Gospel of Apelles",
"Gospel of Barnabas (Epiphanius Panarion)",
"Gospel of Barnabas",
"Gospel of Bartholomew (Epiphanius Panarion)",
"Gospel of Bartholomew",
"Gospel of Basilides (Acta Basilidis)",
"Gospel of Basilides",
"Gospel of Carpocrates (Epiphanius Panarion)",
"Gospel of Carpocrates",
"Gospel of Cerinthus (Epiphanius Panarion)",
"Gospel of Cerinthus",
"Gospel of Eve (Johannine Prologue)",
"Gospel of Eve",
"Gospel of Gamaliel (Pseudo-Gamaliel)",
"Gospel of Gamaliel",
"Gospel of Hesychius (Heracleon)",
"Gospel of Hesychius",
"Gospel of James (also known as the Infancy Gospel of James)",
"Gospel of Judas Thomas (Codex Tchacos)",
"Gospel of Judas",
"Gospel of Mary (Magdalene)",
"Gospel of Mary Magdalene",
"Gospel of Matthias (Codex Montfortianus)",
"Gospel of Matthias (Epiphanius Panarion)",
"Gospel of Matthias",
"Gospel of Merin (Heracleon)",
"Gospel of Merin (Heracleon)",
"Gospel of Merin",
"Gospel of Nicodemus (also known as the Acts of Pilate)",
"Gospel of Perfection (Nag Hammadi Codex VI)",
"Gospel of Perfection",
"Gospel of Peter",
"Gospel of Philip",
"Gospel of Thaddaeus (Epiphanius Panarion)",
"Gospel of Thaddaeus",
"Gospel of the Birth of Mary (Protevangelium of James)",
"Gospel of the Birth of Mary",
"Gospel of the Ebionites",
"Gospel of the Egyptians (Codex Brucianus)",
"Gospel of the Egyptians",
"Gospel of the Four Heavenly Realms (Nag Hammadi Codex IV)",
"Gospel of the Four Heavenly Realms",
"Gospel of the Hebrews",
"Gospel of the Lord (Oxyrhynchus Papyrus 840)",
"Gospel of the Nativity of Jesus Christ (Pseudo-Matthew)",
"Gospel of the Nativity of Jesus Christ",
"Gospel of the Nativity of Mary (Protevangelium of James)",
"Gospel of the Nativity of Mary",
"Gospel of the Nazarenes",
"Gospel of the Pseudo-Matthew (Pseudo-Matthew)",
"Gospel of the Pseudo-Matthew",
"Gospel of the Savior (Pistis Sophia)",
"Gospel of the Savior",
"Gospel of the Savior's Passion (Nag Hammadi Codex III)",
"Gospel of the Savior's Passion",
"Gospel of the Secret Supper (Nag Hammadi Codex II)",
"Gospel of the Secret Supper",
"Gospel of the Seventy (Nag Hammadi Codex VII)",
"Gospel of the Seventy",
"Gospel of the Twelve (Nag Hammadi Codex VI)",
"Gospel of the Twelve Apostles",
"Gospel of the Twelve",
"Gospel of Thomas (Syriac Infancy Gospel)",
"Gospel of Thomas the Contender (Nag Hammadi Codex II)",
"Gospel of Thomas the Contender",
"Gospel of Thomas",
"Gospel of Truth (Valentinian Exposition)",
"Gospel of Truth",
"Gospel of Valentinus (Epistle of Ptolemy to Flora)",
"Gospel of Valentinus",
"Habakkuk",
"Haggai",
"Handwriting on the wall",
"Hosea",
"Isaiah",
"Isaiah's prophecy",
"Jacob's ladder",
"Jeremiah",
"Jeremiah's prophecy",
"Jerusalem",
"Job",
"Joel",
"Jonah and the great fish",
"Jonah",
"Jordan River",
"Joseph's ability to interpret dreams",
"Joshua and the walls of Jericho",
"Joshua",
"Judges",
"Lake of Fire",
"Lamentations",
"Lampstand of the Tabernacle",
"Legion",
"Leviticus",
"Lion's den",
"Malachi",
"Manna",
"Mercy seat of the Tabernacle",
"Mercy seat",
"Micah",
"Moses' hand becoming leprous",
"Moses' parting of the Jordan River",
"Moses' staff turning into a snake",
"Mount Abarim",
"Mount Ararat",
"Mount Calvary",
"Mount Carmel",
"Mount Ebal",
"Mount Ephron",
"Mount Gerizim",
"Mount Gilboa",
"Mount Gilead",
"Mount Heres",
"Mount Hermon",
"Mount Hor",
"Mount Horeb",
"Mount Jearim",
"Mount Moriah",
"Mount Nebo",
"Mount of Acacia",
"Mount of Assembly",
"Mount of Bashan",
"Mount of Beatitudes",
"Mount of Blessing",
"Mount of Corruption",
"Mount of Darkness",
"Mount of Decision",
"Mount of Deliverance",
"Mount of Destruction",
"Mount of Devotion",
"Mount of Division",
"Mount of Encouragement",
"Mount of Fulfillment",
"Mount of Glory",
"Mount of God",
"Mount of Goodness",
"Mount of Healing",
"Mount of Holiness",
"Mount of Hope",
"Mount of Inheritance",
"Mount of Joy",
"Mount of Jubilation",
"Mount of Knowledge",
"Mount of Love",
"Mount of Majesty",
"Mount of Olives",
"Mount of Peace",
"Mount of Perdition",
"Mount of Pleasure",
"Mount of Propitiation",
"Mount of Refuge",
"Mount of Rejoicing",
"Mount of Remembrance",
"Mount of Renewal",
"Mount of Rest",
"Mount of Righteousness",
"Mount of Safety",
"Mount of Salvation",
"Mount of Strength",
"Mount of the Amorites",
"Mount of the Congregation",
"Mount of the East",
"Mount of the Ladder",
"Mount of the Lord",
"Mount of the Lord's House",
"Mount of the Valley",
"Mount of Transfiguration",
"Mount of Truth",
"Mount of Understanding",
"Mount of Victory",
"Mount of Weeping",
"Mount of Wholeness",
"Mount of Wonder",
"Mount of Worship",
"Mount Paran",
"Mount Perazim",
"Mount Pisgah",
"Mount Scopus",
"Mount Seir",
"Mount Shapher",
"Mount Sinai",
"Mount Tabor",
"Mount Zalmon",
"Mount Zemaraim",
"Mount Zion",
"Nahum",
"Nehemiah",
"New Jerusalem",
"Numbers",
"Obadiah",
"Paradise",
"Parting of the Red Sea",
"Pillar of cloud",
"Pillar of fire",
"Plagues of Egypt",
"Promised Land",
"Proverbs",
"Psalms",
"Rainbow around the throne",
"Red Sea",
"Ruth",
"Samson's strength",
"Samuel's prophecy",
"Samuel's spirit",
"Sea of Galilee",
"Seven Spirits of God",
"Shadrach, Meshach, and Abednego in the fiery furnace",
"Sheol",
"Sodom and Gomorrah",
"Solomon's wisdom",
"Song of Solomon",
"Tabernacle of David",
"Tabernacle",
"Table of showbread",
"Temple of Herod",
"Temple of Solomon",
"Temple of Zerubbabel",
"The 24 Elders",
"The Abaddon",
"The Abomination of Desolation",
"The Abyss",
"The Accuser",
"The Acts of Barnabas",
"The Acts of John",
"The Acts of Paul",
"The Acts of Peter",
"The Acts of Philip",
"The Acts of the Apostles",
"The Acts of Thomas",
"The Adversary",
"The Advocate",
"The Alpha and Omega",
"The Alpha and the Omega",
"The Ancient of Days",
"The Angel Gabriel",
"The Angel Michael",
"The Angel of Death",
"The Angel of the Lord",
"The Angel Raphael",
"The Anointed One",
"The Antichrist",
"The Apocalypse of Adam",
"The Apocalypse of Paul",
"The Apocalypse of Peter",
"The Apocalypse of Thomas",
"The Apollyon",
"The Ascension of Isaiah",
"The Assumption of Moses",
"The Avenger",
"The Beast from the Earth",
"The Beast from the Sea",
"The Beast",
"The Beginning and the End",
"The Behemoth",
"The Book of Adam and Eve",
"The Book of Amos",
"The Book of Baruch",
"The Book of Daniel",
"The Book of Ecclesiastes",
"The Book of Enoch the Prophet",
"The Book of Exodus",
"The Book of Ezekiel",
"The Book of Genesis",
"The Book of Hosea",
"The Book of Isaiah",
"The Book of Jasher",
"The Book of Jeremiah",
"The Book of Job",
"The Book of Jubilees",
"The Book of Judith",
"The Book of Malachi",
"The Book of Micah",
"The Book of Proverbs",
"The Book of Psalms",
"The Book of Revelation",
"The Book of Seth",
"The Book of Solomon",
"The Book of the Cave of Treasures",
"The Book of the Secrets of Enoch",
"The Book of Tobit",
"The Book of Zechariah",
"The Bosom of Abraham",
"The Bottomless Pit",
"The Branch",
"The Bread of Life",
"The Bride of Christ",
"The Bridegroom",
"The Celestial City",
"The Cherubim",
"The Christ",
"The City of God",
"The Comforter",
"The Coptic Apocalypse of Peter",
"The Crown of Glory",
"The Crown of Life",
"The Crown of Righteousness",
"The Deceiver",
"The Demons",
"The Destroyer",
"The Didache",
"The Dominions",
"The Dragon",
"The Epistle of Barnabas",
"The Epistle of James",
"The Epistle to Philemon",
"The Epistle to the Colossians",
"The Epistle to the Ephesians",
"The Epistle to the Galatians",
"The Epistle to the Hebrews",
"The Epistle to the Philippians",
"The Epistle to the Romans",
"The Epistle to Titus",
"The Evil One",
"The False Prophet",
"The Father of Lies",
"The First and the Last",
"The First Book of Adam and Eve",
"The First Epistle of Peter",
"The First Epistle to the Corinthians",
"The First Epistle to the Thessalonians",
"The First Epistle to Timothy",
"The Foul Spirit",
"The Four Archangels",
"The four horsemen of the apocalypse",
"The Four Living Creatures",
"The Gehenna",
"The Glory of God",
"The Good Shepherd",
"The Gospel of Andrew",
"The Gospel of Barnabas",
"The Gospel of Bartholomew",
"The Gospel of James",
"The Gospel of John",
"The Gospel of Judas",
"The Gospel of Luke",
"The Gospel of Mark",
"The Gospel of Mary Magdalene",
"The Gospel of Matthew",
"The Gospel of Nicodemus",
"The Gospel of Peter",
"The Gospel of Philip",
"The Gospel of the Ebionites",
"The Gospel of the Infancy of Jesus Christ",
"The Gospel of the Nazarenes",
"The Gospel of Thomas Didymus",
"The Gospel of Truth",
"The Grave",
"The Great Harlot",
"The Hades",
"The Heavenly Jerusalem",
"The Hidden Manna",
"The High Priest",
"The Holy City",
"The Holy One",
"The Holy Spirit",
"The Host of Heaven",
"The Judge of the Living and the Dead",
"The King of Terrors",
"The Kingdom of God",
"The Kingdom of Heaven",
"The Lake of Fire",
"The Lamb of God",
"The Leviathan",
"The Life of Adam and Eve",
"The Light of the World",
"The Lion of Judah",
"The Lion of the Tribe of Judah",
"The Living Water",
"The Love of God",
"The Man of Lawlessness",
"The Mansions in Heaven",
"The mark of the beast",
"The Martyrdom of Isaiah",
"The Messiah",
"The Morning Star",
"The Nephilim",
"The New Heaven and the New Earth",
"The New Jerusalem",
"The Orders of Angels",
"The Outer Darkness",
"The Paradise",
"The Pearl of Great Price",
"The Pit",
"The Place of Weeping and Gnashing of Teeth",
"The Power of God",
"The Powers",
"The Prayer of Manasseh",
"The Prince of Peace",
"The Prince of this World",
"The Principalities",
"The Red Heifer",
"The Redeemer",
"The Resurrection and the Life",
"The River of Life",
"The Root of Jesse",
"The Second Book of Adam and Eve",
"The Second Death",
"The Second Epistle to the Corinthians",
"The Second Epistle to the Thessalonians",
"The Second Epistle to Timothy",
"The Secrets of Enoch",
"The Seraphim",
"The Serpent",
"The Seven Bowls",
"The Seven Seals",
"The Seven Trumpets",
"The Sheol",
"The Shepherd of Hermas",
"The Slanderer",
"The Son of Man",
"The Son of Perdition",
"The Spirit and the Bride say, Come!",
"The Spirit of Amos",
"The Spirit of Antichrist",
"The Spirit of Christ",
"The Spirit of Daniel",
"The Spirit of David",
"The Spirit of Deborah",
"The Spirit of Deliverance",
"The Spirit of Elijah",
"The Spirit of Ezekiel",
"The Spirit of Gideon",
"The Spirit of Glory and of God",
"The Spirit of God",
"The Spirit of Isaiah",
"The Spirit of Jeremiah",
"The Spirit of Jesus Christ",
"The Spirit of Knowledge",
"The Spirit of Malachi",
"The Spirit of Moses",
"The Spirit of Samson",
"The Spirit of Solomon",
"The Spirit of the Fear of the Lord",
"The Spirit of the Lord",
"The Spirit of the Prophets",
"The Spirit of Truth and of Power",
"The Spirit of Understanding",
"The Spirit of Wisdom",
"The Suffering Servant",
"The Tartarus",
"The Tempter",
"The Ten Commandments",
"The Ten Horns",
"The Ten Plagues of Egypt",
"The Testaments of the Twelve Patriarchs",
"The Thrones",
"The Tree of Life",
"The Twelve Apostles",
"The Twelve Prophets",
"The Twelve Tribes of Israel",
"The Two Witnesses",
"The Unclean Spirit",
"The Valley of Hinnom",
"The Vine",
"The Virtues",
"The Watchers",
"The Way, the Truth, and the Life",
"The White Stone with a New Name",
"The Whore of Babylon",
"The Wicked One",
"The Wisdom of God",
"The Wisdom of Jesus Son of Sirach",
"The Wisdom of Solomon",
"The Word of God",
"Tower of Babel",
"Tree of Knowledge of Good and Evil",
"Tree of Life",
"Urim and Thummim",
"Valley of Achor",
"Valley of Baca",
"Valley of Dry Bones",
"Valley of Elah",
"Valley of Jehoshaphat",
"Valley of Jezreel",
"Valley of Megiddo",
"Valley of Salt",
"Valley of Siddim",
"Veil of the Tabernacle",
"Walls of Jericho",
"Water of Purification",
"Witch of Endor's spirit",
"Zechariah",
"Zephaniah",
'Aaron',
'Abednego',
'Abel',
'Abraham',
'Achaicus',
'Adam',
'Alexander',
'Amos',
'Andrew',
'Andronicus',
'Anna',
'Annas',
'Apollos',
'Aquila',
'Aquilla',
'Archippus',
'Aristarchus',
'Barnabas',
'Bartholomew',
'Baruch',
'Bathsheba',
'Benjamin',
'Bildad',
'Boaz',
'Caesar Augustus',
'Caiaphas',
'Cain',
'Caleb',
'Clement',
'Crescens',
'Daniel',
'David',
'Deborah',
'Delilah',
'Demas',
'Demetrius',
'Diotrephes',
'Dorcas',
'Eli',
'Elihu',
'Elijah',
'Eliphaz',
'Elisha',
'Epaphras',
'Epaphroditus',
'Erastus',
'Esau',
'Esther',
'Eunice',
'Euodia',
'Eutychus',
'Eve',
'Ezra',
'Fortunatus',
'Gaius',
'Gideon',
'Hagar',
'Haggai',
'Ham',
'Hannah',
'Hermas',
'Herod Agrippa',
'Herod Antipas',
'Herod',
'Hezekiah',
'Hosea',
'Ignatius',
'Isaac',
'Isaiah',
'Jacob',
'James (son of Alphaeus)', 'Thaddaeus',
'James',
'Japheth',
'Jehu',
'Jeremiah',
'Jeroboam',
'Jesus',
'Job',
'Joel',
'John (son of Zebedee)', 'Luke',
'John the Baptist',
'John',
'Jonah',
'Jonathan',
'Joseph',
'Joshua',
'Josiah',
'Judah',
'Judas Iscariot',
'Junia',
'Lazarus',
'Leah',
'Linus',
'Lois',
'Lot',
'Lydia',
'Malachi',
'Manasseh',
'Mark',
'Martha',
'Mary (mother of Jesus)', 'Elizabeth',
'Mary Magdalene',
'Mary',
'Matthew',
'Meshach',
'Micah',
'Michal',
'Miriam',
'Mordecai',
'Moses',
'Naaman',
'Naomi',
'Nathan',
'Nehemiah',
'Nicodemus',
'Noah',
'Nympha',
'Onesimus',
'Peter',
'Philemon',
'Philip',
'Phoebe',
'Pontius Pilate',
'Prisca',
'Priscilla',
'Quartus',
'Rachel',
'Rahab',
'Rebekah',
'Rehoboam',
'Ruth',
'Samson',
'Samuel',
'Sarah',
'Saul',
'Shadrach',
'Shem',
'Silas',
'Simeon',
'Simon of Cyrene',
'Simon the Zealot',
'Solomon',
'Stephanas',
'Syntyche',
'Tabitha',
'Tamar',
'Thomas',
'Timothy',
'Titus',
'Tychicus',
'Urbanus',
'Zacharias',
'Zechariah',
'Zenas',
'Zophar',
];
