export default [
"African Fish Eagle",
"African Goshawk",
"African Harrier Hawk",
"Albatross",
"American Goldfinch",
"American Kestrel",
"American Robin",
"American Woodcock",
"Andean Condor",
"Aplomado Falcon",
"Bachman's Sparrow",
"Bald Eagle",
"Baltimore Oriole",
"Barn Owl",
"Barn Swallow",
"Barred Owl",
"Bateleur Eagle",
"Bearded Vulture",
"Black Harrier",
"Black Kite",
"Black Vulture",
"Black-and-chestnut Eagle",
"Black-billed Cuckoo",
"Black-capped Chickadee",
"Black-chested Snake Eagle",
"Black-throated Blue Warbler",
"Black-throated Green Warbler",
"Blackburnian Warbler",
"Blue Grosbeak",
"Blue Jay",
"Blue-footed Booby",
"Blue-gray Gnatcatcher",
"Blue-headed Vireo",
"Blue-winged Warbler",
"Bobolink",
"Bobwhite Quail",
"Bonelli's Eagle",
"Booted Eagle",
"Brewer's Blackbird",
"Broad-winged Hawk",
"Brown Pelican",
"Brown Thrasher",
"Brown-headed Cowbird",
"Bufflehead",
"Cactus Wren",
"California Condor",
"Canada Goose",
"Canyon Wren",
"Cape May Warbler",
"Cape Vulture",
"Carolina Chickadee",
"Carolina Wren",
"Cedar Waxwing",
"Cerulean Warbler",
"Chestnut-sided Warbler",
"Chimney Swift",
"Chipping Sparrow",
"Cinereous Vulture",
"Collared Forest Falcon",
"Common Buzzard",
"Common Grackle",
"Common Loon",
"Common Merganser",
"Common Raven",
"Common Redpoll",
"Common Yellowthroat",
"Cooper's Hawk",
"Crested Caracara",
"Crested Eagle",
"Crowned Eagle",
"Crowned Solitary Eagle",
"Dark-eyed Junco",
"Double-crested Cormorant",
"Double-toothed Kite",
"Downy Woodpecker",
"Eastern Bluebird",
"Eastern Kingbird",
"Eastern Meadowlark",
"Eastern Phoebe",
"Eastern Screech-Owl",
"Eastern Towhee",
"Eastern Wood-Pewee",
"Egyptian Vulture",
"Eurasian Sparrowhawk",
"European Honey Buzzard",
"European Robin",
"European Starling",
"Ferruginous Hawk",
"Field Sparrow",
"Fish Crow",
"Flamingo",
"Fox Sparrow",
"Golden Eagle",
"Golden-crowned Kinglet",
"Goshawk",
"Gray Catbird",
"Gray-cheeked Thrush",
"Great Blue Heron",
"Great Crested Flycatcher",
"Great Egret",
"Great Horned Owl",
"Greater Spotted Eagle",
"Green Heron",
"Grey-headed Fish Eagle",
"Griffon Vulture",
"Gyr Falcon",
"Hairy Woodpecker",
"Harpy Eagle",
"Harris's Hawk",
"Hermit Thrush",
"Herring Gull",
"Himalayan Griffon",
"Hooded Eagle",
"Hooded Merganser",
"Hooded Vulture",
"Hooded Warbler",
"Horned Grebe",
"Horned Lark",
"House Finch",
"House Sparrow",
"Imperial Eagle",
"Indigo Bunting",
"Kentucky Warbler",
"Killdeer",
"King Vulture",
"Kingfisher",
"Lanner Falcon",
"Lappet-faced Vulture",
"Lark Sparrow",
"Laughing Gull",
"Least Sandpiper",
"Least Tern",
"Lesser Spotted Eagle",
"Lincoln's Sparrow",
"Loggerhead Shrike",
"Long-crested Eagle",
"Long-legged Buzzard",
"Louisiana Waterthrush",
"Madagascar Fish Eagle",
"Magnolia Warbler",
"Mallard Duck",
"Marsh Harrier",
"Marsh Wren",
"Martial Eagle",
"Meadowlark",
"Merlin",
"Montagu's Harrier",
"Mountain Bluebird",
"Mountain Hawk Eagle",
"Mourning Dove",
"Mourning Warbler",
"Nashville Warbler",
"Nighthawk",
"Northern Cardinal",
"Northern Flicker",
"Northern Goshawk",
"Northern Harrier",
"Northern Mockingbird",
"Northern Parula",
"Northern Saw-whet Owl",
"Northern Waterthrush",
"Olive-sided Flycatcher",
"Orchard Oriole",
"Ornate Hawk Eagle",
"Osprey",
"Ostrich",
"Ovenbird",
"Owl",
"Pale Chanting Goshawk",
"Palm Warbler",
"Peregrine Falcon",
"Philadelphia Vireo",
"Pigeon",
"Pileated Woodpecker",
"Pine Siskin",
"Pine Warbler",
"Piping Plover",
"Prothonotary Warbler",
"Purple Finch",
"Purple Martin",
"Red Crossbill",
"Red Kite",
"Red-bellied Woodpecker",
"Red-breasted Nuthatch",
"Red-eyed Vireo",
"Red-headed Vulture",
"Red-headed Woodpecker",
"Red-shouldered Hawk",
"Red-tailed Hawk",
"Red-winged Blackbird",
"Ring-billed Gull",
"Ring-necked Pheasant",
"Rock Pigeon",
"Rose-breasted Grosbeak",
"Roseate Spoonbill",
"Rough-legged Buzzard",
"Rough-legged Hawk",
"Ruby-crowned Kinglet",
"Ruddy Duck",
"Ruffed Grouse",
"Rufous Hummingbird",
"Rufous-sided Towhee",
"Ruppell's Vulture",
"Saker Falcon",
"Sanderling",
"Sandhill Crane",
"Scarlet Tanager",
"Seagull",
"Secretary Bird",
"Sedge Wren",
"Sharp-shinned Hawk",
"Short-toed Eagle",
"Snow Bunting",
"Snowy Egret",
"Snowy Owl",
"Song Sparrow",
"Sora",
"Sparrow Hawk",
"Sparrowhawk",
"Spotted Sandpiper",
"Starling",
"Steller's Sea Eagle",
"Steppe Buzzard",
"Steppe Eagle",
"Sulawesi Serpent Eagle",
"Summer Tanager",
"Swainson's Hawk",
"Swainson's Thrush",
"Swallow",
"Tawny Eagle",
"Tennessee Warbler",
"Tern",
"Tree Sparrow",
"Tree Swallow",
"Tufted Titmouse",
"Turkey Vulture",
"Upland Sandpiper",
"Veery",
"Vermilion Flycatcher",
"Vesper Sparrow",
"Vulture",
"Western Bluebird",
"Western Grebe",
"Western Kingbird",
"Western Meadowlark",
"Western Tanager",
"White Hawk",
"White Pelican",
"White-backed Vulture",
"White-crowned Sparrow",
"White-rumped Vulture",
"White-tailed Eagle",
"White-throated Sparrow",
"Whooping Crane",
"Wild Turkey",
"Wilson's Warbler",
"Wood Duck",
"Wood Thrush",
"Woodpecker",
"Yellow Warbler",
"Yellow-bellied Flycatcher",
"Yellow-breasted Chat",
"Yellow-headed Blackbird",
"Yellow-throated Vireo",
];
