export default [
    "Head", "Forehead", "Temple", "Eye", "Eyelid", "Eyelash", "Eyebrow", "Ear", 
    "Earlobe", "Nose", "Nostril", "Cheek", "Jaw", "Chin", "Mouth", "Lip", 
    "Tooth", "Tongue", "Neck", "Shoulder", "Arm", "Elbow", "Forearm", "Wrist", 
    "Hand", "Palm", "Finger", "Thumb", "Nail", "Knuckle", "Back", "Spine", 
    "Scapula", "Chest", "Breast", "Abdomen", "Waist", "Hip", "Buttock", "Groin", 
    "Thigh", "Knee", "Shin", "Calf", "Ankle", "Heel", "Foot", "Toe", "Sole", 
    "Skin", "Hair", "Mole", "Freckle", "Birthmark", "Beard", "Mustache", 
    "Sideburn", "Eyebrow Piercing", "Ear Piercing", "Nose Piercing", "Lip Piercing", 
    "Navel Piercing", "Tattoo", "Scar", "Wrinkle", "Blush", "Eyelash Extension", 
    "Fingernail", "Toenail", "Knuckle Hair", "Arm Hair", "Leg Hair", "Foot Hair", 
    "Back Hair", "Chest Hair", "Abdominal Hair", "Facial Hair", "Eyebrow Hair", 
    "Sideburn Hair", "Neck Hair", "Lobe", "Eyebrow Ridge", "Collarbone", "Shinbone",
    "Upper arm", "Lower arm", "Upper leg", "Lower leg", "Left eye", "Right eye",
    "Left ear", "Right ear", "Left cheek", "Right cheek", "Left nostril", "Right nostril",
    "Upper lip", "Lower lip", "Upper eyelid", "Lower eyelid", "Left eyebrow", "Right eyebrow",
    "Left shoulder", "Right shoulder", "Left elbow", "Right elbow", "Left wrist", "Right wrist",
    "Left hand", "Right hand", "Left palm", "Right palm", "Left thumb", "Right thumb",
    "Left index finger", "Right index finger", "Left middle finger", "Right middle finger",
    "Left ring finger", "Right ring finger", "Left little finger", "Right little finger",
    "Left fingernail", "Right fingernail", "Left toenail", "Right toenail",
    "Left knee", "Right knee", "Left ankle", "Right ankle", "Left foot", "Right foot",
    "Left toe", "Right toe", "Left heel", "Right heel", "Left sole", "Right sole",
    "Left side of neck", "Right side of neck", "Front of neck", "Back of neck",
    "Left upper chest", "Right upper chest", "Left lower chest", "Right lower chest",
    "Left side of abdomen", "Right side of abdomen", "Upper back", "Lower back",
    "Left upper back", "Right upper back", "Left lower back", "Right lower back",
    "Left hip", "Right hip", "Left buttock", "Right buttock",
    "Left thigh", "Right thigh", "Left shin", "Right shin", "Left calf", "Right calf",
    "Left upper arm hair", "Right upper arm hair", "Left lower arm hair", "Right lower arm hair",
    "Left upper leg hair", "Right upper leg hair", "Left lower leg hair", "Right lower leg hair",
    "Left foot hair", "Right foot hair", "Left hand hair", "Right hand hair",
    "Left sideburn", "Right sideburn", "Left part of beard", "Right part of beard",
    "Left eyebrow hair", "Right eyebrow hair", "Left eyelash", "Right eyelash",
    "Left side of forehead", "Right side of forehead", "Left temple", "Right temple",
    "Left jawline", "Right jawline", "Left side of chin", "Right side of chin",
    "Left earlobe", "Right earlobe", "Left knuckle", "Right knuckle",
    "Left side of waist", "Right side of waist", "Nape of neck", "Crown of head",
    "Top of head", "Back of head", "Left side of head", "Right side of head",
    "Forehead wrinkle", "Crow's feet", "Laugh lines", "Frown lines",
    "Nasolabial fold", "Philtrum", "Adam's apple", "Trachea",
    "Sternum", "Clavicle", "Left rib", "Right rib", "Belly button",
    "Pelvic bone", "Coccyx", "Sacrum", "Pubic area", "Groin area",
    "Left inner thigh", "Right inner thigh", "Left outer thigh", "Right outer thigh",
    "Left inner calf", "Right inner calf", "Left outer calf", "Right outer calf",
    "Left forearm vein", "Right forearm vein", "Left arm vein", "Right arm vein",
    "Left hand vein", "Right hand vein", "Left foot vein", "Right foot vein",
    "Left eyelid crease", "Right eyelid crease", "Upper gum", "Lower gum",
    "Upper teeth", "Lower teeth", "Tongue tip", "Tongue surface",
    "Gingiva", "Palate", "Uvula", "Tonsils",
    "Left eyelid margin", "Right eyelid margin", "Left iris", "Right iris",
    "Left pupil", "Right pupil", "Left cornea", "Right cornea",
    "Left retina", "Right retina", "Left sclera", "Right sclera",
    "Left eye corner", "Right eye corner", "Left ear canal", "Right ear canal",
    "Left ear drum", "Right ear drum", "Left nostril rim", "Right nostril rim",
    "Left cheekbone", "Right cheekbone", "Left mandible", "Right mandible"
];
