export default [
  "To Kill a Mockingbird",
  "1984",
  "The Catcher in the Rye",
  "The Great Gatsby",
  "Pride and Prejudice",
  "The Lord of the Rings",
  "The Hobbit",
  "Animal Farm",
  "Brave New World",
  "The Picture of Dorian Gray",
  "Wuthering Heights",
  "Jane Eyre",
  "The Adventures of Huckleberry Finn",
  "The Adventures of Tom Sawyer",
  "Frankenstein",
  "Dracula",
  "The Hitchhiker's Guide to the Galaxy",
  "The Da Vinci Code",
  "The Shining",
  "A Clockwork Orange",
  "One Hundred Years of Solitude",
  "Crime and Punishment",
  "The Brothers Karamazov",
  "Anna Karenina",
  "War and Peace",
  "The Three Musketeers",
  "The Count of Monte Cristo",
  "Les Miserables",
  "The Hunchback of Notre-Dame",
  "The Picture of Dorian Gray",
  "Alice's Adventures in Wonderland",
  "Through the Looking-Glass",
  "The Adventures of Sherlock Holmes",
  "The Memoirs of Sherlock Holmes",
  "The Hound of the Baskervilles",
  "The Return of Sherlock Holmes",
  "The Valley of Fear",
  "The Sign of the Four",
  "The Lord of the Flies",
  "The Chronicles of Narnia",
  "The Lion, the Witch and the Wardrobe",
  "The Hunger Games",
  "Catching Fire",
  "Mockingjay",
  "Dune",
  "The Color Purple",
  "The Help",
  "The Handmaid's Tale",
  "Beloved",
  "The Bluest Eye",
  "The Sound and the Fury",
  "The Sun Also Rises",
  "A Farewell to Arms",
  "For Whom the Bell Tolls",
  "The Old Man and the Sea",
  "The Call of the Wild",
  "White Fang",
  "The Grapes of Wrath",
  "East of Eden",
  "Of Mice and Men",
  "The Picture of Dorian Gray",
  "The Portrait of a Lady",
  "The Age of Innocence",
  "The House of Mirth",
  "The Catcher in the Rye",
  "Nine Stories",
  "Franny and Zooey",
  "Raise High the Roof Beam, Carpenters and Seymour: An Introduction",
  "The Bell Jar",
  "The Complete Stories of Flannery O'Connor",
  "Slaughterhouse-Five",
  "Cat's Cradle",
  "Breakfast of Champions",
  "The Sirens of Titan",
  "Player Piano",
  "A Man Without a Country",
  "The God of Small Things",
  "Midnight's Children",
  "A Suitable Boy",
  "The Satanic Verses",
  "The Secret History",
  "The Goldfinch",
  "The Little Prince",
  "The Alchemist",
  "Love in the Time of Cholera",
  "One Hundred Years of Solitude",
  "Chronicle of a Death Foretold",
  "The House of the Spirits",
  "Island of the Blue Dolphins",
  "The Diary of a Young Girl",
  "Little Women",
  "Anne of Green Gables",
  "The Outsiders",
  "Go Set a Watchman",
  "The Green Mile",
  "The Stand",
  "It",
    "The Great Gatsby",
  "To Kill a Mockingbird",
  "1984",
  "Pride and Prejudice",
  "Animal Farm",
  "The Catcher in the Rye",
  "Brave New World",
  "The Hobbit",
  "Lord of the Rings",
  "Harry Potter and the Philosopher's Stone",
  "The Hunger Games",
  "The Da Vinci Code",
  "The Girl with the Dragon Tattoo",
  "Gone Girl",
  "The Fault in Our Stars",
  "Naked Lunch",
  "Fear and Loathing in Las Vegas",
  "On the Road",
  "The Electric Kool-Aid Acid Test",
  "Tropic of Cancer",
  "The Crying of Lot 49",
  "Finnegan's Wake",
  "Nausea",
  "Lolita",
  "Infinite Jest",
  "Gravity's Rainbow",
  "Slaughterhouse-Five",
  "One Hundred Years of Solitude",
  "Steppenwolf",
  "The Stranger",
  "The Naked and the Dead",
  "The Doors of Perception",
  "The Teachings of Don Juan",
  "Dune",
  "The Illuminatus! Trilogy",
  "The God of Small Things",
  "Valis",
  "The Dharma Bums",
  "The Haunting of Hill House",
  "The Hitchhiker's Guide to the Galaxy",
  "The Left Hand of Darkness",
  "The Witches' Sabbath",
  "Tropic of Capricorn",
  "The Master and Margarita",
  "The Three Stigmata of Palmer Eldritch",
  "The White Hotel",
  "Geek Love",
  "The Anarchist Cookbook",
  "The Communist Manifesto",
  "The Tao Te Ching",
  "The Bible",
  "The Koran",
  "The Tibetan Book of the Dead",
  "The Book of the Law",
  "The Secret Teachings of All Ages",
  "The Satanic Bible",
  "The Alchemist",
  "The Teachings of Buddha",
  "The Odyssey",
  "The Iliad",
  "The Divine Comedy",
  "The Canterbury Tales",
  "The Waste Land",
  "The Love Song of J. Alfred Prufrock",
  "Leaves of Grass",
  "Howl",
  "The Bridge",
  "The Red Wheelbarrow",
  "The Road Not Taken",
  "The Catcher in the Rye",
  "Lord of the Flies",
  "1984",
  "Brave New World",
  "Fahrenheit 451",
  "The Handmaid's Tale",
  "Animal Farm",
  "A Clockwork Orange",
  "Fight Club",
  "American Psycho",
  "Trainspotting",
  "The Picture of Dorian Gray",
  "Dracula",
  "Frankenstein",
  "The Strange Case of Dr. Jekyll and Mr. Hyde",
  "The Call of Cthulhu",
  "Do Androids Dream of Electric Sheep?",
  "Neuromancer",
  "Snow Crash",
  "The Diamond Age",
  "The Name of the Rose",
  "Invisible Cities",
  "If on a winter's night a traveler",
  "The Unbearable Lightness of Being",
  "The Hitchhiker's Guide to the Galaxy",
  "The Hunger Games",
  "The Da Vinci Code",
  "The Girl with the Dragon Tattoo",
  "Gone Girl",
  "The Fault in Our Stars",
  "The Perks of Being a Wallflower",
  "The Bell Jar",
  "The Great Gatsby",
  "To Kill a Mockingbird",
  "The Adventures of Huckleberry Finn",
  "The Scarlet Letter",
  "The Grapes of Wrath",
  "East of Eden",
  "The Sun Also Rises",
  "For Whom the Bell Tolls",
  "The Old Man and the Sea",
  "The Catch-22",
  "Siddhartha",
   "The Christ Conspiracy: The Greatest Story Ever Sold",
  "Astrotheology & Shamanism: Christianity's Pagan Roots. A Revolutionary Reinterpretation",
  "The Origins of Christianity and the Quest for the Historical Jesus Christ",
  "The Pagan Christ: Recovering the Lost Light",
  "The Sacred Mushroom and The Cross: A study of the nature and origins of Christianity within the fertility cults of the ancient Near East",
  "The Book Your Church Doesn't Want You To Read",
  "The Two Babylons: Or, The Papal Worship Proved to be the Worship of Nimrod and His Wife",
  "The World's Sixteen Crucified Saviors",
  "The Secret Teachings of All Ages",
  "The Gods of Eden",
  "The Hidden History of Jesus and the Holy Grail",
  "The Gnostic Gospels",
  "The Laughing Jesus: Religious Lies and Gnostic Wisdom",
  "The Egyptian Book of the Dead",
  "The Bible Fraud",
  "The Astrological Foundation of the Christ Myth",
  "The Astrology Book: The Encyclopedia of Heavenly Influences",
  "Astrology, Psychology, and the Four Elements",
  "The Secret Doctrine of the Rosicrucians",
  "The Divine Pymander of Hermes Mercurius Trismegistus",
  "The Hermetic Museum",
  "The Golden Bough: A Study in Magic and Religion",
  "The Mysterious Origins of Christianity",
  "The Secret History of the World",
  "The Secret Teachings of Moses",
  "The Secret Zodiacs of Washington DC",
  "The Lost Teachings of Atlantis",
  "The Sirius Mystery",
  "The Sirius Connection: Unlocking the Secrets of Ancient Egypt",
  "The Message of the Sphinx",
  "The Egyptian Hermes: A Historical Approach to the Late Pagan Mind",
  "The Egyptian Mysteries: New Light on Ancient Knowledge",
  "The Mysteries of Mithras: The Pagan Belief That Shaped the Christian World",
  "The Cult of the Black Virgin",
  "The Goddess in the Gospels: Reclaiming the Sacred Feminine",
  "The Serpent Grail: The Truth Behind the Holy Grail, the Philosopher's Stone and the Elixir of Life",
  "The Sacred History: How Angels, Mystics and Higher Intelligence Made Our World",
  "The Secret Life of Plants",
  "The Book of Enoch",
  "The Book of Jubilees",
  "The Apocryphon of John",
  "The Gospel of Thomas",
  "The Nag Hammadi Library",
  "The Corpus Hermeticum",
  "The Confessions of St. Augustine",
  "The Teachings of the Compassionate Buddha",
  "The Bhagavad Gita",
  "The Upanishads",
  "The Tao Te Ching",
  "The I Ching",
  "The Secret of the Golden Flower",
  "The Kybalion",
  "The Tree of Life: An Illustrated Study in Magic",
  "The Power of Myth",
  "The Masks of God: Oriental Mythology",
  "The Masks of God: Primitive Mythology",
  "The Masks of God: Creative Mythology",
  "The Masks of God: Transformations of Myth Through Time",
  "The Hero with a Thousand Faces",
  "The Gospel According to Jesus Christ",
  "The Last Temptation of Christ",
  "The Devil's Apocrypha: There Are Two Sides to Every Story",
  "Principles of Economics", 
"Calculus: Early Transcendentals", 
"Principles of Marketing", 
"Physics for Scientists and Engineers", 
"Principles of Microeconomics", 
"Chemistry: The Central Science", 
"Fundamentals of Corporate Finance", 
"Introduction to Psychology", 
"Anatomy and Physiology", 
"Organic Chemistry", 
"Fundamentals of Financial Management", 
"Principles of Macroeconomics", 
"Accounting Principles", 
"Human Anatomy and Physiology", 
"Managerial Accounting", 
"Psychology", 
"Biology", 
"Statistics for Business and Economics", 
"Managerial Economics", 
"Principles of Accounting", 
"Fundamentals of Physics", 
"Operations Management", 
"Marketing Management", 
"Sociology", 
"Financial Accounting", 
"Business Law", 
"Financial Management", 
"Microbiology", 
"Financial Markets and Institutions", 
"Principles of Management", 
"Business Statistics", 
"Principles of Investments", 
"Computer Networks", 
"Managerial Finance", 
"Information Technology for Management", 
"Macroeconomics", 
"Introduction to Information Systems", 
"Principles of Information Systems", 
"Management Information Systems", 
"Managerial Accounting: Tools for Business Decision Making", 
"Elementary Statistics", 
"Investments", 
"Supply Chain Management", 
"Business Analytics", 
"Intermediate Accounting", 
"Cost Accounting", 
"Essentials of Investments", 
"Business and Society", 
"Business Essentials", 
"Anatomy & Physiology: An Integrative Approach", 
"Introduction to Management Science", 
"Essentials of Marketing", 
"Operations and Supply Chain Management", 
"Fundamentals of Nursing", 
"Human Resource Management", 
"Strategic Management", 
"Intermediate Microeconomics", 
"Introduction to Operations Research", 
"Fundamentals of Financial Accounting", 
"Corporate Finance", 
"Human Resource Management: Essential Perspectives", 
"International Business", 
"Management Accounting", 
"International Economics", 
"Foundations of Financial Management", 
"Strategic Marketing", 
"Physics", 
"Intermediate Accounting: Reporting and Analysis", 
"Financial Accounting: Tools for Business Decision Making", 
"Global Business Today", 
"Accounting Information Systems", 
"Corporate Financial Accounting", 
"Financial Statement Analysis and Valuation", 
"Fundamentals of Investing", 
"Financial Accounting Theory", 
"Fundamentals of Financial Planning", 
"Introduction to Information Security", 
"Financial Markets and Institutions: Abridged Edition", 
"Marketing: An Introduction", 
"Essentials of Business Communication", 
"Investments: Analysis and Behavior", 
"Principles of Auditing & Other Assurance Services", 
"International Financial Management", 
"Corporate Finance: Core Principles and Applications", 
"Principles of Risk Management and Insurance"]