export default [
  "Absinthe",
  "Ale",
  "Amaretto",
  "Aperol",
  "Applejack",
  "Armagnac",
  "Bailey's Irish Cream",
  "Beer",
  "Bellini",
  "Benedictine",
  "Bitters",
  "Bourbon",
  "Brandy",
  "Calvados",
  "Campari",
  "Champagne",
  "Chartreuse",
  "Chianti",
  "Cider",
  "Cognac",
  "Cointreau",
  "Cosmopolitan",
  "Creme de Cassis",
  "Creme de Menthe",
  "Curacao",
  "Daiquiri",
  "Drambuie",
  "Dubonnet",
  "Eggnog",
  "Fizz",
  "Frangelico",
  "Gin",
  "Ginger Beer",
  "Glogg",
  "Grand Marnier",
  "Grenadine",
  "Guinness",
  "Harvey Wallbanger",
  "Hot Toddy",
  "Irish Coffee",
  "Jagermeister",
  "Kahlua",
  "Kir",
  "Lager",
  "Limoncello",
  "Long Island Iced Tea",
  "Mai Tai",
  "Margarita",
  "Martini",
  "Mezcal",
  "Midori",
  "Mimosa",
  "Mojito",
  "Mulled Wine",
  "Negroni",
  "Old Fashioned",
  "Pernod",
  "Pina Colada",
  "Port",
  "Prosecco",
  "Rum",
  "Sake",
  "Sambuca",
  "Sangria",
  "Scotch",
  "Sherry",
  "Sidecar",
  "Sloe Gin",
  "Sour",
  "Southern Comfort",
  "Sparkling Wine",
  "Spiced Rum",
  "Stout",
  "Tequila",
  "Tom Collins",
  "Tonic Water",
  "Triple Sec",
  "Vermouth",
  "Vodka",
  "Whiskey",
  "White Wine",
  "Wine Cooler",
  "Zinfandel",
  "Chateau Margaux",
  "Chateau Lafite Rothschild",
  "Chateau Latour",
  "Chateau Haut-Brion",
  "Chateau Mouton Rothschild",
  "Petrus",
  "Cheval Blanc",
  "Romanee-Conti",
  "Chateau d'Yquem",
  "Opus One",
  "Sassicaia",
  "Tignanello",
  "Gaja Barbaresco",
  "Caymus Special Selection",
  "Dominus Estate",
  "Shafer Hillside Select",
  "Penfolds Grange",
  "Henschke Hill of Grace",
  "Torbreck The Laird",
  "Sine Qua Non",
  "Screaming Eagle",
  "Harlan Estate",
  "DRC Romanee-Conti",
  "Domaine Leflaive Montrachet",
  "Domaine de la Romanee-Conti La Tache",
  "Domaine Leroy Musigny",
  "Sassicaia",
  "Solaia",
  "Ornellaia",
  "Chateau d'Esclans Whispering Angel",
  "Veuve Clicquot Brut Yellow Label",
  "Dom Perignon",
  "Krug",
  "Bollinger RD Extra Brut",
  "Louis Roederer Cristal",
  "Laurent-Perrier Grand Siecle",
  "Taittinger Comtes de Champagne",
  "Pol Roger Sir Winston Churchill",
  "Ruinart Blanc de Blancs",
  "Gosset Celebris Extra Brut",
  "Moet & Chandon Imperial Brut",
  "Chateau Musar",
  "Penfolds Bin 389",
  "Marchesi Antinori Tignanello",
  "Masseto",
  "Mascarello Barolo Monprivato",
  "Tenuta San Guido Sassicaia",
  "Biondi-Santi Brunello di Montalcino",
  "Ridge Monte Bello",
  "Guinness",
  "Heineken",
  "Stella Artois",
  "Budweiser",
  "Corona",
  "Becks",
  "Chimay",
  "Hoegaarden",
  "Pilsner Urquell",
  "Newcastle Brown Ale",
  "Leffe Blonde",
  "Duvel",
  "Westvleteren",
  "Orval",
  "La Trappe Quadrupel",
  "Tripel Karmeliet",
  "Weihenstephaner Hefeweissbier",
  "Paulaner Hefe-Weissbier",
  "Augustiner Helles",
  "Maisel's Weisse",
  "Franziskaner Hefe-Weissbier",
  "Ayinger Celebrator",
  "Pliny the Elder",
  "Sierra Nevada Pale Ale",
  "Samuel Adams Boston Lager",
  "Anchor Steam Beer",
  "Stone IPA",
  "Bell's Two Hearted Ale",
  "Founders Breakfast Stout",
  "Dogfish Head 90 Minute IPA",
  "Russian River Pliny the Younger",
  "Cantillon Gueuze",
  "Rochefort 10",
  "Rodenbach Grand Cru",
  "Mikkeller Beer Geek Breakfast",
  "Birra del Borgo Re Ale Extra",
  "BrewDog Punk IPA",
  "La Chouffe",
  "Hoegaarden Wit",
  "Pauwel Kwak",
  "Westmalle Tripel",
  "Saison Dupont",
  "Achel Blonde",
  "Straffe Hendrik Quad",
  "Spaten Oktoberfestbier",
  "Hacker-Pschorr Oktoberfest",
  "Warsteiner Premium Verum",
  "Tuborg Pilsner",
  "Carlsberg",
  "Baltika No. 9",
  "Asahi Super Dry",
  "Sapporo Premium Beer",
  "Kirin Ichiban",
  "Tsingtao",
  "Snow Beer",
  "Kingfisher",
  "Victoria Bitter",
  "Coopers Pale Ale",
  "Little Creatures Pale Ale",
  "James Squire The Chancer Golden Ale",
  "Cascade Pale Ale",
  "Fat Yak Pale Ale",
  "Boag's Premium",
  "Tooheys Extra Dry",
  "XXXX Gold",
  "James Boag's Draught",
  "Peroni Nastro Azzurro",
  "Stiegl Goldbräu",
  "Leffe Brune",
  "Delirium Tremens",
  "Brouwerij 't IJ Zatte",
  "Piraat",
  "Gouden Carolus Classic",
  "Brugse Zot Blond",
  "Kwak",
  "Chimay Blue",
  "Kasteel Rouge",
  "Rochefort 8",
  "Westvleteren 12",
  "La Trappe Dubbel",
  "St. Bernardus Abt 12",
  "Rodenbach Classic",
  "Lindemans Kriek",
  "Saison Dupont Vieille Provision",
  "Duvel Tripel Hop",
  "Hofbrau Dunkel",
  "Baltika No. 7",
  "Cisk Lager",
  "Whiskey Sour",
  "Old Fashioned",
  "Manhattan",
  "Irish Coffee",
  "Mint Julep",
  "Rob Roy",
  "Bourbon Smash",
  "Whiskey Ginger",
  "Rusty Nail",
  "Hot Toddy",
  "Black Russian",
  "White Russian",
  "Vodka Martini",
  "Bloody Mary",
  "Moscow Mule",
  "Cosmopolitan",
  "Screwdriver",
  "Greyhound",
  "Sex on the Beach",
  "Lemon Drop Martini",
  "Appletini",
  "Long Island Iced Tea",
  "Sea Breeze",
  "White Lady",
  "Black and White",
  "Harvey Wallbanger",
  "Kamikaze",
  "Bay Breeze",
  "Cape Codder",
  "Madras",
  "Blackberry Bramble",
  "Singapore Sling",
  "Mai Tai",
  "Zombie",
  "Corpse Reviver #2",
  "Sidecar",
  "French 75",
  "Gimlet",
  "Vesper"
];
