export default [ "Acura NSX",
  "Acura RSX",
  "Alfa Romeo Giulia",
  "Alfa Romeo Spider",
  "Aston Martin DB5",
  "Aston Martin DB11",
  "Aston Martin Vantage",
  "Audi A3",
  "Audi A4",
  "Audi A5",
  "Audi A6",
  "Audi A7",
  "Audi A8",
  "Audi R8",
  "Audi RS3",
  "Audi RS4",
  "Audi RS5",
  "Audi RS6",
  "Audi S3",
  "Audi S4",
  "Audi S5",
  "Audi S6",
  "Audi S7",
  "Audi S8",
  "Audi TT",
  "Bentley Continental GT",
  "BMW 3 Series",
  "BMW 4 Series",
  "BMW 5 Series",
  "BMW 6 Series",
  "BMW 7 Series",
  "BMW 8 Series",
  "BMW i8",
  "BMW M2",
  "BMW M3",
  "BMW M4",
  "BMW M5",
  "BMW M6",
  "BMW X1",
  "BMW X2",
  "BMW X3",
  "BMW X4",
  "BMW X5",
  "BMW X6",
  "BMW X7",
  "BMW Z3",
  "BMW Z4",
  "Bugatti Chiron",
  "Buick Regal",
  "Cadillac ATS",
  "Cadillac CTS",
  "Cadillac Escalade",
  "Cadillac XTS",
  "Chevrolet Camaro",
  "Chevrolet Corvette",
  "Chevrolet Cruze",
  "Chevrolet Impala",
  "Chevrolet Malibu",
  "Chevrolet Silverado",
  "Chevrolet Suburban",
  "Chevrolet Tahoe",
  "Chevrolet Traverse",
  "Chrysler 300",
  "Dodge Challenger",
  "Dodge Charger",
  "Dodge Durango",
  "Dodge Ram",
  "Ferrari 488 GTB",
  "Ferrari 458 Italia",
  "Ferrari 812 Superfast",
  "Ferrari California",
  "Ferrari F12 Berlinetta",
  "Ferrari F430",
  "Ferrari GTC4Lusso",
  "Ferrari LaFerrari",
  "Fiat 500",
  "Ford Bronco",
  "Ford Edge",
  "Ford Escape",
  "Ford Expedition",
  "Ford Explorer",
  "Ford F-150",
  "Ford Fiesta",
  "Ford Focus",
  "Ford Fusion",
  "Ford GT",
  "Ford Mustang",
  "GMC Acadia",
  "GMC Sierra",
  "GMC Yukon",
  "Honda Accord",
  "Honda Civic",
  "Honda CR-V",
  "Honda Fit",
  "Honda Odyssey",
  "Honda Pilot",
  "Hummer H1",
  "Hyundai Accent",
  "Hyundai Elantra",
  "Hyundai Genesis",
  "Hyundai Sonata",
  "Infiniti G35",
  "Infiniti G37",
  "Infiniti Q50",
  "Infiniti Q60",
  "Infiniti QX50",
  "Infiniti QX60",
  "Infiniti QX70",
  "Infiniti QX80",
  "Jaguar F-Pace", 
"Jaguar F-Type", 
"Jaguar XE", 
"Jaguar XF", 
"Jaguar XJ", 
"Jeep Cherokee", 
"Jeep Compass", 
"Jeep Grand Cherokee", 
"Jeep Wrangler", 
"Kia Optima", 
"Kia Sorento", 
"Kia Soul", 
"Kia Stinger", 
"Lamborghini Aventador", 
"Lamborghini Huracan", 
"Lamborghini Urus", 
"Land Rover Discovery", 
"Land Rover Range Rover", 
"Lexus ES", 
"Lexus GS", 
"Lexus GX", 
"Lexus IS", 
"Lexus LC", 
"Lexus LS", 
"Lexus LX", 
"Lexus NX", 
"Lexus RC", 
"Lexus RX", 
"Lincoln Continental", 
"Lincoln MKC", 
"Lincoln MKS", 
"Lincoln MKT", 
"Lincoln MKX", 
"Lincoln MKZ", 
"Lotus Elise", 
"Lotus Evora", 
"Maserati Ghibli", 
"Maserati GranTurismo", 
"Maserati Levante", 
"Maserati Quattroporte", 
"Mazda3", 
"Mazda6", 
"Mazda CX-3", 
"Mazda CX-5", 
"Mazda CX-9", 
"McLaren 570S", 
"McLaren 720S", 
"McLaren P1", 
"Mercedes-Benz A-Class", 
"Mercedes-Benz C-Class", 
"Mercedes-Benz CLA-Class", 
"Mercedes-Benz CLS-Class", 
"Mercedes-Benz E-Class", 
"Mercedes-Benz G-Class", 
"Mercedes-Benz GLA-Class", 
"Mercedes-Benz GLC-Class", 
"Mercedes-Benz GLE-Class", 
"Mercedes-Benz GLS-Class", 
"Mercedes-Benz S-Class", 
"Mercedes-Benz SL-Class", 
"Mercedes-Benz SLC-Class", 
"Mercedes-Benz SLK-Class", 
"Mercedes-Benz SLS AMG", 
"Mercedes-Benz AMG GT", 
"Mercedes-Benz Maybach S-Class", 
"Mini Cooper", 
"Mitsubishi Eclipse Cross", 
"Mitsubishi Mirage", 
"Nissan 370Z", 
"Nissan Altima", 
"Nissan Armada", 
"Nissan GT-R", 
"Nissan Maxima", 
"Nissan Murano", 
"Nissan Pathfinder", 
"Nissan Rogue", 
"Nissan Sentra", 
"Nissan Versa", 
"Pagani Huayra", 
"Porsche 911", 
"Porsche Boxster", 
"Porsche Cayenne", 
"Porsche Cayman", 
"Porsche Macan", 
"Porsche Panamera", 
"Rolls-Royce Dawn", 
"Rolls-Royce Ghost", 
"Rolls-Royce Phantom", 
"Rolls-Royce Wraith", 
"Subaru BRZ", 
"Subaru Crosstrek", 
"Subaru Forester", 
"Subaru Impreza", 
"Subaru Legacy", 
"Subaru Outback", 
"Subaru WRX", 
"Tesla Model 3", 
"Tesla Model S", 
"Tesla Model X", 
"Tesla Model Y", 
"Toyota 4Runner", 
"Toyota Avalon", 
"Toyota Camry", 
"Toyota Corolla", 
"Toyota Highlander", 
"Toyota Land Cruiser", 
"Toyota Prius", 
"Toyota RAV4", 
"Toyota Sequoia", 
"Toyota Sienna", 
"Toyota Supra", 
"Toyota Tacoma", 
"Toyota Tundra", 
"Volkswagen Arteon", 
"Volkswagen Atlas", 
"Volkswagen Golf", 
"Volkswagen Jetta", 
"Volkswagen Passat", 
"Volkswagen Tiguan", 
"Volvo S60", 
"Volvo S90", 
"Volvo V60", 
"Volvo XC40", 
"Volvo XC60", 
"Volvo XC90"]