export default [  "Abyssinian",  
"American Bobtail",  
"American Curl",  
"American Shorthair",  
"American Wirehair",  
"Balinese",  
"Bengal",  
"Birman",  
"Bombay",  
"British Shorthair",  
"Burmese",  
"Burmilla",  
"California Spangled",  
"Chantilly/Tiffany",  
"Chartreux",  
"Chausie",  
"Colorpoint Shorthair",  
"Cornish Rex",  
"Cymric",  
"Devon Rex",  
"Egyptian Mau",  
"Exotic Shorthair",  
"Havana Brown",  
"Himalayan",  
"Japanese Bobtail",  
"Javanese",  
"Korat",  
"LaPerm",  
"Maine Coon",  
"Manx",  
"Munchkin",  
"Nebelung",  
"Norwegian Forest",  
"Ocicat",  
"Oriental Longhair",  
"Oriental Shorthair",  
"Persian",  
"Peterbald",  
"Pixie-Bob",  
"Ragamuffin",  
"Ragdoll",  
"Russian Blue",  
"Savannah",  
"Scottish Fold",  
"Selkirk Rex",  
"Siamese",  
"Siberian",  
"Singapura",  
"Snowshoe",  
"Somali",  
"Sphynx",  
"Tonkinese",  
"Toyger",  
"Turkish Angora",  
"Turkish Van",  
"Aegean",  
"Australian Mist",  
"Bambino",  
"Brazilian Shorthair",  
"British Longhair",  
"Chausie",  
"Cheetoh",  
"Chinese Li Hua",  
"Cuban Brown",  
"Donskoy",  
"Dragon Li",  
"European Shorthair",  
"Foldex",  
"German Rex",  
"Highlander",  
"Khao Manee",  
"Korean Bobtail",  
"Korn Ja",  
"Kurilian Bobtail",  
"Lambkin",  
"Lykoi",  
"Minskin",  
"Napoleon",  
"Nebelung",  
"Nigerian",  
"Norwegian Forest",  
"Ojos Azules",  
"Petersburg Sphynx",  
"Safari",  
"Serengeti",  
"Seychellois",  
"Sokoke",  
"Thai",  
"Thai Lilac",  
"Toybob",  
"Ukrainian Levkoy",  
"Wila Krungthep",  
"York Chocolate"];