export default [
"Crop tops", 
"Flare jeans", 
"High-waisted shorts", 
"Hoodies", 
"Graphic T-shirts", 
"Maxi dresses", 
"Leather jackets", 
"Denim jackets", 
"Bomber jackets", 
"Skater skirts", 
"Parkas", 
"Overalls", 
"Jumpsuits", 
"High-waisted pants", 
"Ankle boots", 
"Platform sneakers", 
"Wedge sandals", 
"Slip-on loafers", 
"Peplum tops", 
"Midi skirts",
"Sari",
"Kimono",
"Cheongsam",
"Kilt",
"Dashiki",
"Dirndl",
"Hijab",
"Lederhosen",
"Boubou",
"Sarong",
"Baju Kurung",
"Kaftan",
"Thobe",
"Hanbok",
"Abaya",
"Chiton",
"Qipao",
"Poncho",
"Kente Cloth",
"Tartan",
"Scarves",
"Belts",
"Hats",
"Sunglasses",
"Ties",
"Watches",
"Jewelry",
"Gloves",
"Handbags",
"Backpacks",
"Shawls",
"Umbrellas",
"Hair accessories",
"Suspenders",
"Socks",
"Tights",
"Leg warmers",
"Arm warmers",
"Fascinators",
"Pocket squares",
"T-shirt",  "Jeans",  "Hoodie",  "Sneakers",  "Dress",  "Blouse",  "Skirt",  "Shorts",  "Swimsuit",  "Sandals",  "Flip-flops",  "Jacket",  "Coat",  "Raincoat",  "Umbrella",  "Scarf",  "Gloves",  "Hat",  "Beanie",  "Cap",  "Sunglasses",  "Belt",  "Tie",  "Suit",  "Dress shoes",  "Boots",  "Loafers",  "Slippers",  "Tank top",  "Sports bra",  "Yoga pants",  "Leggings",  "Sweatpants",  "Sweatshirt",  "Pajamas",  "Robe",  "Underwear",  "Bra",  "Boxers",  "Briefs",  "Thong",  "Socks",  "Stockings",  "Tights",  "Bathrobe",  "Shower cap",  "Hair band",  "Hair clip",  "Necklace",  "Bracelet",  "Earrings",  "Ring",  "Watch",  "Handbag",  "Backpack",  "Tote bag",  "Clutch",  "Wallet",  "Purse",  "Satchel",  "Messenger bag",  "Briefcase",  "Luggage",  "Trunk",  "Duffle bag",  "Gym bag",  "Fedora",  "Cowboy hat",  "Bucket hat",  "Beret",  "Baseball cap",  "Beanie",  "Visor",  "Headband",  "Sweater",  "Cardigan",  "Poncho",  "Shawl",  "Trench coat",  "Peacoat",  "Windbreaker",  "Puffer jacket",  "Vest",  "Ski jacket",  "Snow pants",  "Goggles",  "Ski gloves",  "Ski boots",  "Rain boots",  "Wellington boots",  "Wetsuit",  "Life jacket",  "Gym shorts",  "Running shoes",  "Cycling shorts",  "Swim trunks",  "Baseball jersey",  "Football jersey",  "Basketball jersey",  "Hockey jersey",  "Compression shorts"];