export default [
"A clever person solves a problem. A wise person avoids it.",
"A computer program does what you tell it to do, not what you want it to do.",
"A good programmer is someone who always looks both ways before crossing a one-way street.",
"A language that doesn't affect the way you think about programming is not worth knowing."
"A language that doesn't affect the way you think about programming is not worth knowing.",
"A program is never less than 90% complete, and never more than 95% complete.",
"Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.",
"Always leave the code better than you found it.",
"Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
"Code is a liability, not an asset.",
"Code is like a poem; it has to follow certain structural requirements, but the beauty is in the details.",
"Code is like humor. When you have to explain it, it’s bad.",
"Code is read more often than it is written.",
"Code is read much more often than it is written.",
"Code is written for people to read, and only incidentally for machines to execute.",
"Code never lies, comments sometimes do.",
"Code should be written to minimize the time it would take someone else to understand it.",
"Code that is commented out is code that was never written.",
"Code works if it compiles.",
"Coding is not just about creating something new, it's also about improving what already exists.",
"Coding is not just about what you know, but what you can figure out.",
"Coding is not just about what you know, it's about what you can learn.",
"Debugging is like being a detective in a mystery movie where you are also the murderer.",
"Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.",
"Documentation is like sex; when it's good, it's very, very good, and when it's bad, it's better than nothing.",
"Don't repeat yourself (DRY).",
"Fail fast, fail often.",
"Good code is its own best documentation.",
"Good code is like a good joke; it needs no explanation.",
"Good code is simple, clear, and easy to maintain.",
"Good design adds value faster than it adds cost.",
"If at first you don't succeed; call it version 1.0.",
"If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
"If it's not tested, it's broken.",
"If you can't explain it simply, you don't understand it well enough.",
"If you think math is hard, try programming.",
"If you want to go fast, go alone. If you want to go far, go together.",
"If you're not failing, you're not pushing your limits, and if you're not pushing your limits, you're not maximizing your potential.",
"It works on my machine.",
"Keep it simple, stupid (KISS).",
"Make it correct, make it clear, make it concise, make it fast. In that order.",
"Make it simple, but significant.",
"Make it work, make it right, make it fast.",
"Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
"Premature abstraction is as bad as premature optimization.",
"Premature optimization is the root of all evil.",
"Programmers are constantly making trade-offs between speed, quality, and maintainability.",
"Programming is a journey, not a destination.",
"Programming is like cooking; you can follow a recipe, but the best results come from experimentation and creativity.",
"Programs are meant to be read by humans and only incidentally for computers to execute.",
"Programs must be written for people to read, and only incidentally for machines to execute.",
"Real programmers don't comment their code. If it was hard to write, it should be hard to understand.",
"Simplicity is the soul of efficiency.",
"Software design is just like house design. A good architect designs for your current needs, with an eye for future growth and renovation.",
"Software development is a collaborative effort, not a solo endeavor.",
"Software engineering is what happens to programming when you add time and other programmers.",
"Software is a gas; it expands to fill its container.",
"Software is a great combination of artistry and engineering.",
"The art of programming is the skill of controlling complexity.",
"The best code is no code.",
"The best code is the code that doesn't exist.",
"The best code is the code that is never written.",
"The best code is the code that never had to be written.",
"The best error message is the one that never shows up.",
"The best programmers are those who think creatively and embrace change.",
"The best software development process is the one that works for you.",
"The best way to become a good programmer is to write a lot of code.",
"The best way to learn programming is to write programs.",
"The best way to predict the future is to invent it.",
"The best way to predict your future is to code it.",
"The code you write is the code you maintain.",
"The difference between a good programmer and a bad programmer is the amount of time it takes them to write code.",
"The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time.",
"The key to good programming is to always start with a clear understanding of the problem.",
"The key to writing good code is to write code that is easy to read.",
"The most important skill in programming is the ability to learn quickly.",
"The most important thing in the programming language is the name. A language will not succeed without a good name. I have recently invented a very good name and now I am looking for a suitable language.",
"The only constant in the software development lifecycle is change.",
"The only way to do great work is to love what you do.",
"The only way to go fast is to go well.",
"The perfect is the enemy of the good.",
"The sooner you start coding, the longer the program will take.",
"There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.",
"There are two ways to write error-free programs; only the third one works.",
"There's nothing more permanent than a temporary hack.",
"With enough eyeballs, all bugs are shallow.",
"You aren't gonna need it (YAGNI)."
]