export default ['red', 
'blue', 
'pink', 
'white', 
'blonde', 
'black', 
'moonrock', 
'purple',
'aqua',  
'beige',  
'black',  
'blue',  
'bronze',  
'brown',  
'burgundy',  
'champagne',  
'charcoal',  
'coral',  
'cream',  
'cyan',  
'gold',  
'gray',  
'green',  
'indigo',  
'ivory',  
'khaki',  
'lavender',  
'lemon',  
'lilac',  
'lime',  
'magenta',  
'maroon',  
'mauve',  
'navy',  
'olive',  
'orange',  
'peach',  
'pink',  
'purple',  
'red',  
'rose',  
'ruby',  
'rust',  
'salmon',  
'sapphire',  
'scarlet',  
'sienna',  
'silver',  
'slate',  
'tan',  
'tangerine',  
'teal',  
'terracotta',  
'turquoise',  
'violet',  
'white',  
'yellow',  
'apricot',  
'azure',  
'bisque',  
'celadon',  
'cinnamon',  
'coffee',  
'emerald',  
'fuchsia',  
'hazel',  
'jade',  
'mango',  
'mustard',  
'ochre',  
'orchid',  
'periwinkle',  
'sepia',  
'vermilion',
"red", 
"blue", 
"pink", 
"white", 
"blonde", 
"black", 
"moonrock", 
"purple",
"aqua",  
"beige",  
"black",  
"blue",  
"bronze",  
"brown",  
"burgundy",  
"champagne",  
"charcoal",  
"coral",  
"cream",  
"cyan",  
"gold",  
"gray",  
"green",  
"indigo",  
"ivory",  
"khaki",  
"lavender",  
"lemon",  
"lilac",  
"lime",  
"magenta",  
"maroon",  
"mauve",  
"navy",  
"olive",  
"orange",  
"peach",  
"pink",  
"purple",  
"red",  
"rose",  
"ruby",  
"rust",  
"salmon",  
"sapphire",  
"scarlet",  
"sienna",  
"silver",  
"slate",  
"tan",  
"tangerine",  
"teal",  
"terracotta",  
"turquoise",  
"violet",  
"white",  
"yellow",  
"apricot",  
"azure",  
"bisque",  
"celadon",  
"cinnamon",  
"coffee",  
"emerald",  
"fuchsia",  
"hazel",  
"jade",  
"mango",  
"mustard",  
"ochre",  
"orchid",  
"periwinkle",  
"sepia",  
"vermilion",
"AliceBlue",
  "AntiqueWhite",
  "Aqua",
  "Aquamarine",
  "Azure",
  "Beige",
  "Bisque",
  "Black",
  "BlanchedAlmond",
  "Blue",
  "BlueViolet",
  "Brown",
  "BurlyWood",
  "CadetBlue",
  "Chartreuse",
  "Chocolate",
  "Coral",
  "CornflowerBlue",
  "Cornsilk",
  "Crimson",
  "Cyan",
  "DarkBlue",
  "DarkCyan",
  "DarkGoldenRod",
  "DarkGray",
  "DarkGrey",
  "DarkGreen",
  "DarkKhaki",
  "DarkMagenta",
  "DarkOliveGreen",
  "DarkOrange",
  "DarkOrchid",
  "DarkRed",
  "DarkSalmon",
  "DarkSeaGreen",
  "DarkSlateBlue",
  "DarkSlateGray",
  "DarkSlateGrey",
  "DarkTurquoise",
  "DarkViolet",
  "DeepPink",
  "DeepSkyBlue",
  "DimGray",
  "DimGrey",
  "DodgerBlue",
  "FireBrick",
  "FloralWhite",
  "ForestGreen",
  "Fuchsia",
  "Gainsboro",
  "GhostWhite",
  "Gold",
  "GoldenRod",
  "Gray",
  "Grey",
  "Green",
  "GreenYellow",
  "HoneyDew",
  "HotPink",
  "IndianRed",
  "Indigo",
  "Ivory",
  "Khaki",
  "Lavender",
  "LavenderBlush",
  "LawnGreen",
  "LemonChiffon",
  "LightBlue",
  "LightCoral",
  "LightCyan",
  "LightGoldenRodYellow",
  "LightGray",
  "LightGrey",
  "LightGreen",
  "LightPink",
  "LightSalmon",
  "LightSeaGreen",
  "LightSkyBlue",
  "LightSlateGray",
  "LightSlateGrey",
  "LightSteelBlue",
  "LightYellow",
  "Lime",
  "LimeGreen",
  "Linen",
  "Magenta",
  "Maroon",
  "MediumAquaMarine",
  "MediumBlue",
  "MediumOrchid",
  "MediumPurple",
  "MediumSeaGreen",
  "MediumSlateBlue",
  "MediumSpringGreen",
  "MediumTurquoise",
  "MediumVioletRed",
  "MidnightBlue",
  "MintCream",
  "MistyRose",
  "Moccasin",
  "NavajoWhite",
  "Navy",
  "OldLace",
  "Olive",
  "OliveDrab",
  "Orange",
  "OrangeRed",
  "Orchid",
  "PaleGoldenRod",
  "PaleGreen",
  "PaleTurquoise",
  "PaleVioletRed",
  "PapayaWhip",
  "PeachPuff",
  "Peru",
  "Pink",
  "Plum",
  "PowderBlue",
  "Purple",
  "RebeccaPurple",
  "Red",
  "RosyBrown",
  "RoyalBlue",
  "SaddleBrown",
  "Salmon",
  "SandyBrown",
  "SeaGreen",
  "SeaShell",
  "Sienna",
  "Silver",
  "SkyBlue",
  "SlateBlue",
  "SlateGray",
  "Amaranth",
  "Baker-Miller Pink",
  "Black Coral",
  "Botticelli",
  "Caput Mortuum",
  "Celeste",
  "Cerulean Frost",
  "Cherry Blossom Pink",
  "Coquelicot",
  "Cornell Red",
  "Damaris",
  "Deep Champagne",
  "Deep Koamaru",
  "Egyptian Blue",
  "Fallow",
  "Fandango",
  "Fern Green",
  "Flavescent",
  "French Lilac",
  "Gainsboro Metallic",
  "Gamboge",
  "Gargoyle Gas",
  "Ginger",
  "Heliotrope Gray",
  "Honeydew Melon",
  "Icterine",
  "Inchworm",
  "Iris Blue",
  "Ivory Black",
  "Jazzberry Jam",
  "Kombu Green",
  "Languid Lavender",
  "Lavender Blue",
  "Lavender Pink",
  "Lemon Glacier",
  "Liver Chestnut",
  "Majorelle Blue",
  "Mango Tango",
  "Mardi Gras",
  "Mauve Taupe",
  "Mauveine",
  "Maya Blue",
  "Mikado Yellow",
  "Mimi Pink",
  "Mindaro",
  "Misty Moss",
  "Moonstone",
  "Nadeshiko Pink",
  "Napier Green",
  "Old Mauve",
  "Oxford Blue",
  "Pale Taupe",
  "Paradise Pink",
  "Pastel Brown",
  "Persian Pink",
  "Pewter Blue",
  "Piggy Pink",
  "Pine Green",
  "Pistachio",
  "Puce Red",
  "Quartz Pink",
  "Radical Red",
  "Rajah",
  "Raspberry Rose",
  "Rhythm",
  "Rose Dust",
  "Rose Madder",
  "Royal Fuchsia",
  "Rufous",
  "Satin Sheen Gold",
  "Serpentine",
  "Shadow Blue",
  "Shocking Pink",
  "Sinopia",
  "Smokey Topaz",
  "Space Cadet",
  "Stil De Grain Yellow",
  "Straw",
  "Sunglow",
  "Tangelo",
  "Terra Cotta",
  "Thulian Pink",
  "Timberwolf",
  "Tropical Rain Forest",
  "Tyrian Purple",
  "Ube",
  "Verdigris",
  "Violet Blue",
  "Vivid Tangerine",
  "Watermelon",
  "Wenge",
  "Wine Dregs",
  "Xanadu",
  "Yale Blue",
  "Zaffre"];