export default [  
"80s pop star",
"90s grunge rocker",
"Alice in Wonderland",
"Alien Queen",
"Alien",
"Ancient Greek/Roman Deity",
"Angel",
"Anna",
"Ariel",
"Astronaut",
"Baker",
"Ballerina",
"Barbie",
"Baseball player",
"Basketball player",
"Batgirl",
"Belle",
"Belly dancer",
"Betty Boop",
"Boxer",
"Breakdancer",
"Bride of Frankenstein",
"Captain Hook",
"Catwoman",
"Cheerleader",
"Chef",
"Cheshire Cat",
"Cinderella",
"Circus Acrobat",
"Circus Clown",
"Circus Ringmaster",
"Circus Strongman/Strongwoman",
"Cowgirl",
"Crazy Scientist",
"Creepy Doll",
"Creepy Marionette Doll",
"Creepy Porcelain Doll",
"Creepy Scarecrow",
"Cruella de Vil",
"Cruella",
"Cryptic Enchantress",
"Cryptic Fortune Teller",
"Cryptic Riddler",
"Cryptic Ringmaster",
"Cryptic Sorcerer/Sorceress",
"Cursed Knight",
"Cursed Medieval Knight",
"Cursed Medieval Princess",
"Cursed Nun",
"Cursed Pirate Captain",
"Cursed Pirate",
"Cursed Princess",
"Cursed Samurai Warrior",
"Cursed Samurai",
"Cursed Witch",
"Cursed Wizard",
"Daisy Duck",
"Dark Angel",
"Dark Fairy",
"Dark Sorcerer",
"Day of the Dead Sugar Skull",
"Devil",
"Disco diva",
"Doctor",
"Doll",
"Duchess",
"Egyptian queen",
"Elsa",
"Enchanting Fairy",
"Evil Genie",
"Evil Jester",
"Evil Mermaid",
"Evil Queen",
"Fairy Tale Character Mashup",
"Fairy",
"Femme fatale",
"Figure skater",
"Firefighter",
"Flight attendant",
"Football player",
"Fortune Teller",
"Frankenstein",
"Geisha",
"Ghost",
"Ghostly Ballerina",
"Ghostly Geisha Doll",
"Ghostly Geisha",
"Ghostly Spirit",
"Ghostly Victorian Lady",
"Ghostly Witch",
"Goddess",
"Golfer",
"Gothic Ballerina",
"Gothic Corpse Bride",
"Gothic Dark Princess",
"Gothic Fairy Princess",
"Gothic Gargoyle Queen",
"Gothic Gargoyle",
"Gothic Ghost Bride",
"Gothic Ghost Bride",
"Gothic Knight",
"Gothic Medieval Princess",
"Gothic Pirate",
"Gothic Red Riding Hood",
"Gothic Vampire Hunter",
"Gothic Vampire Queen",
"Gothic Vampire",
"Gothic Witch Hunter",
"Grim Reaper Bride",
"Grim Reaper",
"Grimm Evil Queen",
"Grimm Evil Sorcerer",
"Grimm Fairy Godmother",
"Grimm Fairytale Character",
"Grimm Reaper",
"Grimm Steampunk Inventor",
"Grimm Steampunk Scientist",
"Grimm Witch Hunter",
"Gymnast",
"Gypsy",
"Harley Quinn",
"Haunted Bride",
"Haunted Clown",
"Haunted Doll",
"Haunted Fortune Teller",
"Haunted Gypsy",
"Haunted Housekeeper",
"Haunted Red Riding Hood",
"Haunted Vampire Bride",
"Haunted Zombie Bride",
"Hip hop dancer",
"Hula dancer",
"Indian princess",
"Jasmine",
"Jessica Rabbit",
"Mad Hatter",
"Mad Scientist",
"Maid",
"Maleficent Queen",
"Maleficent",
"Malevolent Fairy",
"Malevolent Magician",
"Masquerade Masked Ball Attendee",
"Medusa",
"Mermaid",
"Moana",
"Monster Bride",
"Mulan",
"Mummy Princess",
"Mummy",
"Mysterious Phantom",
"Mystic Sorceress",
"Mystic Witch Doctor",
"Mystical Dark Angel",
"Mystical Druid",
"Mystical Oracle",
"Mystical Shaman",
"Nightmare Clown",
"Ninja",
"Nurse",
"Peter Pan",
"Pilot",
"Pirate Captain",
"Pirate",
"Poison Ivy",
"Police officer",
"Pop star",
"Power Ranger",
"Princess",
"Queen of Hearts",
"Queen",
"Race car driver",
"Rag Doll",
"Red Riding Hood",
"Robot",
"Rockstar",
"Salsa dancer",
"Samurai Warrior",
"Scarecrow",
"Schoolgirl",
"Seductive Succubus",
"Shadow Ninja",
"Shadowy Grim Reaper",
"Shadowy Reaper",
"Shadowy Sorcerer",
"Shadowy Sorceress",
"Shadowy Vampire Queen",
"Shadowy Warlock",
"Shadowy Witch Doctor",
"Sinister Clown",
"Sinister Harlequin Jester",
"Sinister Harlequin",
"Sinister Jester",
"Sinister Marionette",
"Sinister Ringmaster",
"Sinister Steampunk Inventor",
"Sinister Voodoo Doll",
"Sinister Voodoo Priest/Priestess",
"Sinister Witch Hunter",
"Sinister Zombie Doll",
"Sinister Zombie Nurse",
"Skeleton",
"Snow White",
"Sorceress",
"Star Wars character",
"Steampunk Aviator",
"Steampunk Explorer",
"Steampunk Inventor",
"Steampunk Skeleton",
"Steampunk Vampire Hunter",
"Steampunk Vampire",
"Steampunk Witch",
"Steampunk Zombie",
"Superhero",
"Tennis player",
"Tinkerbell",
"Twisted Alice",
"Twisted Mad Hatter",
"Ursula",
"Vampire Hunter",
"Vampire",
"Vampiric Seductress",
"Vengeful Banshee",
"Vengeful Dark Fairy",
"Vengeful Ghost",
"Voodoo Doll",
"Voodoo Priest/Priestess",
"Waitress",
"Werewolf",
"Wicked Fairy Godmother",
"Wicked Fairy",
"Wicked Fallen Angel",
"Wicked Forest Nymph",
"Wicked Forest Witch",
"Wicked Queen",
"Wicked Steampunk Engineer",
"Wicked Steampunk Inventor",
"Wicked Steampunk Pirate",
"Wicked Steampunk Scientist",
"Wicked Stepmother",
"Wicked Victorian Lady",
"Wicked Witch Doctor",
"Wicked Witch of the West",
"Wicked Witch of the Woods",
"Witch Doctor",
"Witch",
"Witchy Vixen",
"Wonder Woman",
"Wrestler",
"Zombie Astronaut",
"Zombie Astronomer",
"Zombie Athlete",
"Zombie Cheerleader",
"Zombie Chef",
"Zombie Doctor",
"Zombie Firefighter",
"Zombie Flight Attendant",
"Zombie Football Player",
"Zombie Gardener",
"Zombie Gladiator",
"Zombie Hunter",
"Zombie Mechanic",
"Zombie Nurse",
"Zombie Pilot",
"Zombie Police Officer",
"Zombie Prom Attendee",
"Zombie Prom Queen/King",
"Zombie Rocker",
"Zombie Rockstar",
"Zombie Schoolgirl",
"Zombie Soldier",
"Zombie Surgeon",
"Zombie Teacher",
"Zombie"];