export default [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia (formerly Macedonia)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
 "Paraguay",  
"Peru",  
"Philippines",  
"Poland",  
"Portugal",  
"Qatar",  
"Romania",  
"Russia",  
"Rwanda",  
"Saint Kitts and Nevis",  
"Saint Lucia",  
"Saint Vincent and the Grenadines",  
"Samoa",  
"San Marino",  
"Sao Tome and Principe",  
"Saudi Arabia",  
"Senegal",  
"Serbia",  
"Seychelles",  
"Sierra Leone",  
"Singapore",  
"Slovakia",  
"Slovenia",  
"Solomon Islands",  
"Somalia",  
"South Africa",  
"South Sudan",  
"Spain",  
"Sri Lanka",  
"Sudan",  
"Suriname",
    "Swaziland",  
"Sweden",  
"Switzerland",  
"Syria",  
"Taiwan",  
"Tajikistan",  
"Tanzania",  
"Thailand",  
"Timor-Leste",  
"Togo",  
"Tonga",  
"Trinidad and Tobago",  
"Tunisia",  
"Turkey",  
"Turkmenistan",  
"Tuvalu",  
"Uganda",  
"Ukraine",  
"United Arab Emirates",  
"United Kingdom",  
"United States of America",  
"Uruguay",  
"Uzbekistan",  
"Vanuatu",  
"Venezuela",  
"Vietnam",  
"Yemen",  
"Zambia",  
"Zimbabwe",
"Argentina",  "Bolivia",  "Brazil",  "Chile",  "Colombia",  "Ecuador",  "Guyana",  "Paraguay",  "Peru",  "Suriname",  "Uruguay",  "Venezuela",
"Albania",  "Andorra",  "Austria",  "Belarus",  "Belgium",  "Bosnia and Herzegovina",  "Bulgaria",  "Croatia",  "Cyprus",  "Czech Republic",  "Denmark",  "Estonia",  "Finland",  "France",  "Germany",  "Greece",  "Hungary",  "Iceland",  "Ireland",  "Italy",  "Kosovo",  "Latvia",  "Liechtenstein",  "Lithuania",  "Luxembourg",  "Malta",  "Moldova",  "Monaco",  "Montenegro",  "Netherlands",  "North Macedonia",  "Norway",  "Poland",  "Portugal",  "Romania",  "Russia",  "San Marino",  "Serbia",  "Slovakia",  "Slovenia",  "Spain",  "Sweden",  "Switzerland",  "Ukraine",  "United Kingdom",  "Vatican City"
]