export default [
"dress",  
"Midi dress",  
"Little black dress",  
"Wrap dress",  
"Bodycon dress",  
"Shift dress",  
"A-line dress",  
"Peplum dress",  
"Shirt dress",  
"Fit and flare dress",  
"Sheath dress",  
"Skater dress",  
"Off-the-shoulder dress",  
"Empire waist dress",  
"Halter dress",  
"Tunic dress",  
"Kimono dress",  
"Mermaid dress",  
"High-low dress",  
"Boho dress",  
"Tea length dress",  
"Cocktail dress",  
"Ball gown",  
"Prom dress",  
"Wedding dress",  
"Sundress",  
"Floral dress",  
"Striped dress",  
"Polka dot dress",  
"Lace dress",  
"Chiffon dress",  
"Velvet dress",  
"Satin dress",  
"Sequin dress",  
"Embroidered dress",  
"Beaded dress",  
"Geometric print dress",  
"Paisley dress",  
"Denim dress",  
"Jumpsuit dress",  
"Cape dress",  
"One-shoulder dress",  
"Tiered dress",  
"Ruffled dress",  
"tutu dress",  
"Pleated dress",  
"Asymmetrical dress",  
"Cutout dress",  
"Backless dress",  
"Bodysuit dress",  
"Bardot dress",  
"Fitted dress",  
"Sweater dress",  
"Cable knit dress",  
"Turtleneck dress",  
"Mini dress",  
"Bandage dress",  
"Wraparound dress",  
"Strappy dress",  
"Slip dress",  
"Gingham dress",  
"Embellished dress",  
"Fringed dress",  
"Crochet dress",  
"Net dress",  
"Corset dress",  
"Balloon dress",  
"Pinafore dress",  
"Utility dress",  
"Cargo dress",  
"Shirtwaist dress",  
"Layered dress",  
"Prairie dress",  
"Peasant dress",  
"Babydoll dress",  
"Bubble dress",  
"Smock dress",  
"Shift dress",  
"Swing dress",  
"Tube dress",  
"Dungaree dress",  
"Duster dress",  
"T-shirt dress",  
"Hooded dress",  
"Sports dress",  
"Maternity dress",  
"Nursing dress",  
"shirt dress",  
"kaftan dress",  
"beach dress",  
"tank dress",  
"shirt dress",  
"tunic dress",  
"wrap dress",  
"halter dress",  
"kimono dress",  
"off-the-shoulder dress",  
"A-line dress",  
"peasant dress",  
"boho dress"]