export default [ "Paul Atreides",
  "Leto Atreides",
  "Lady Jessica",
  "House Atreides",
  "House Harkonnen",
  "Duke Leto",
  "Baron Vladimir Harkonnen",
  "Gurney Halleck",
  "Dr. Yueh",
  "Thufir Hawat",
  "Mentats",
  "Bene Gesserit",
  "Reverend Mother",
  "Kwisatz Haderach",
  "Spice Melange",
  "Arrakis",
  "Shai-Hulud",
  "Fremen",
  "Stilgar",
  "Chani",
  "Liet-Kynes",
  "Emperor Shaddam IV",
  "CHOAM",
  "Landsraad",
  "Gom Jabbar",
  "Weirding Way",
  "Ornithopter",
  "Shield Generator",
  "Lasgun",
  "Sardaukar",
  "Corrino",
  "Kaitain",
  "Ix",
  "Tleilaxu",
  "Face Dancers",
  "Axlotl Tanks",
  "The Water of Life",
  "Crysknife",
  "The Voice",
  "Kanly",
  "Thopter",
  "Guild Navigator",
  "The Golden Path",
  "The Jihad",
  "Shadout Mapes",
  "Feyd-Rautha Harkonnen",
  "Giedi Prime",
  "Harah",
  "Jamis",
  "Piter de Vries",
  "Alia Atreides",
  "Idaho",
  "The Baron's Heartplug",
  "Baliset",
  "Pardot Kynes",
  "Hawat's Battle Language",
  "The Fremen Fedaykin",
  "St. Alia of the Knife",
  "The Bene Tleilax",
  "The Tleilaxu Master Scytale",
  "Harkonnen Battle Language",
  "The Baron's Suspensors",
  "The Emperor's Sardaukar Death Commandos",
  "The Hunter-Seeker",
  "The Fremen's Stillsuit",
  "The Water Sellers",
  "The Great Convention",
  "The Guild Steersman",
  "The Mahdi",
  "The Preacher",
  "The Sietch",
  "The Bene Gesserit Litany Against Fear",
  "The Baron's Heartplugs",
  "The Emperor's Truthsayer",
  "The Bene Gesserit Missionaria Protectiva",
  "The Gom Jabbar Test",
  "The Fremen Muan Pattern",
  "The Sapho Juice",
  "The Fremen Grief Ceremony",
  "The Imperial Ecologist",
  "The Bene Tleilax Axlotl Tanks",
  "The Fremen Crysknife Dance",
  "The Voice of the Bene Gesserit",
  "The Fremen Blue-within-Blue Eyes",
  "The Fremen Sanctorum",
  "The Sardaukar's Inkvine Scar",
  "The Fremen Taboo on Water Waste",
  "The Kwisatz Haderach Prophecy",
  "The Landsraad Heighliner",
  "The Tleilaxu Face Dancers",
  "The Bene Gesserit Bene Tleilax Alliance",
  "The Sandtrout",
  "The Fremen Terraforming Project",
  "The Emperor's Corrino Throne",
  "The Fremen Sandworm Rider",
  "The Fish Speakers",
  "The Fremen Chakobsa Language",
  "The Shield Wall",
  "The Bene Gesserit Mission on Wallach IX",
  "The Tleilaxu Axlotl Tanks",
  "The Fremen Knife Fighting",
  "The Honored Matres",
  "The Face Dancer Scytale's Ghola Project",
  "The No-Ship",
  "The Ixian Thinking Machines",
  "The Gholas",
  "The Tleilaxu Ghola Masters",
  "The Spice Agony",
  "The Honored Matres' Agony",
  "The Scattering",
  "The God Emperor Leto II",
  "The Duncan Idaho Ghola",
  "The Fish Speaker Army",
  "The Bene Gesserit's Kwizeen Tasting",
  "The Muad'Dib Jihad",
  "The Siona Bloodline",
  "The Bene Gesserit Voice-Glove",
  "The Bene Gesserit's Prana-Bindu Training",
  "The Bene Gesserit's Other Memory",
  "The Tleilaxu Kralizec",
  "The Fremen Resonance Field",
  "The Ixian Holtzman Effect",
  "The Spice Orgy",
  "The Ixian Navigators",
  "The Axlotl Tanks' Limited Cloning",
  "The Golden Elixir",
  "The Spice Sapho Ampules",
  "The Tleilaxu Axlotl Tanks' Process",
  "The Fremen Sandtrout Gloves",
  "The Bene Gesserit's Honored Matres Plan",
  "The Fish Speaker Honorifics",
  "The Spice Essence of Arrakis",
  "The Tleilaxu's Replacement Organs",
  "The Bene Gesserit's Voice on Water",
  "The Guild Steersman's Navigational Control",
  "The Fremen's Sietch Council",
  "The Bene Gesserit's Prana-Bindu Levels",
  "The Scattering's Tyrant Rulers",
  "The Ixian's No-Field Projector",
  "The Fish Speaker Empress",
  "The Ixian's Hypno-Linguistics",
  "The Bene Gesserit's Typhoon Struggle",
  "The Fremen's Wind Trap",
  "The Tleilaxu's Breeding Programs",
  "The Honored Matres' Quasi-Telepathy",
  "The Ixian's Ixianoids",
  "The Fish Speaker's Gossip Network",
  "The Bene Gesserit's Spacing Guild Manipulation",
  "The Tleilaxu's Ultimate Kwisatz Haderach Project",
  "The Ixian's Dream Machine",
  "The Fish Speaker's Sandworm Riding Ritual",
  "The Bene Gesserit's Axlotl Tank Escape",
  "The Fremen's Deathstill",
  "The Scattering's Sandworm Breeding Programs",
  "The Ixian's Crystal Torch",
  "The Fish Speaker's Imperial Messenger Service",
  "The Tleilaxu's Face Dancer Ghola",
  "The Bene Gesserit's Reverend Mother Training",
  "The Fremen's Agony Gauntlet",
  "The Honored Matres' Hunter-Seeker",
  "The Ixian's Nullentropy Tube",
  "The Fish Speaker's Spice Stockpiles",
  "The Tleilaxu's Honored Matres Contingency Plan",
  "The Bene Gesserit's Kwisatz Haderach Prediction"];
