export default [
  "Ambient Techno",
  "Breakbeat",
  "Chillout",
  "Deep House",
  "Drum and Bass",
  "Dub",
  "Dubstep",
  "Electro",
  "Electronic Body Music (EBM)",
  "Electronica",
  "Electropop",
  "Eurodance",
  "Experimental",
  "Future Garage",
  "Gabber",
  "Glitch",
  "Glitch Hop",
  "Hard Trance",
  "Hardcore Techno",
  "House",
  "IDM (Intelligent Dance Music)",
  "Industrial",
  "Italo Disco",
  "Jungle",
  "Liquid Funk",
  "Makina",
  "Minimal Techno",
  "New Beat",
  "Nu Jazz",
  "Outsider House",
  "Progressive House",
  "Psybient",
  "Psychedelic Trance",
  "Rave",
  "Schranz",
  "Synthwave",
  "Tech House",
  "Techno",
  "Trance",
  "Tribal House",
  "UK Garage",
  "2-Step Garage",
  "Acid House",
  "Acid Techno",
  "Aggrotech",
  "Ambient Dub",
  "Ambient House",
  "Baltimore Club",
  "Bassline",
  "Bass Music",
  "Balearic Beat",
  "Big Beat",
  "Bitpop",
  "Broken Beat",
  "Chillwave",
  "Dance-Punk",
  "Dark Ambient",
  "Darkwave",
  "Digital Hardcore",
  "Disco House",
  "Downtempo",
  "Dream House",
  "Dub Techno",
  "EBM (Electronic Body Music)",
  "Electro-Industrial",
  "Electroclash",
  "Electronicore",
  "Electronica",
  "Ethnic Electronica",
  "Fidget House",
  "Footwork",
  "Freestyle",
  "French House",
  "Funkot",
  "Future Bass",
  "Ghetto House",
  "Glitch Pop",
  "Goa Trance",
  "Grime",
  "Happy Hardcore",
  "Hard House",
  "Hi-NRG",
  "Horrorcore",
  "Industrial Techno",
  "Italo House",
  "J-Tek",
  "Jazztronica",
  "Jumpstyle",
  "Krautrock",
  "Laptronica",
  "Latin House",
  "Leftfield House",
  "Leftfield Techno",
  "Lofi House",
  "Madchester",
  "Mashup",
  "Microhouse",
  "Minimal House",
  "Minimal Wave",
  "Moombahton",
  "Neotrance",
  "Neurofunk",
  "New Rave",
  "Nightcore",
  "Noise",
  "Nortec",
  "Nortec Collective",
  "Nu Skool Breaks",
  "Oldschool Jungle",
  "Progressive Trance",
  "Raggacore",
  "Raggatek",
  "Rave Breaks",
  "Rhythmic Noise",
  "Ska-Punk",
  "Speedcore",
  "Subground",
  "Sunrise Trance",
  "Swing House",
  "Synthpop",
  "Synthpunk",
  "Tech Trance",
  "Techstep",
  "Trancecore",
  "Tribal Techno",
  "Turbofolk"]