export default [
  'happy', 'sad', 'angry', 'joyful', 'excited', 'bored', 'anxious', 'calm',
  'relieved', 'stressed', 'confident', 'insecure', 'grateful', 'resentful',
  'content', 'restless', 'peaceful', 'irritated', 'hopeful', 'hopeless',
  'energetic', 'lethargic', 'curious', 'indifferent', 'proud', 'ashamed',
  'loving', 'hateful', 'jealous', 'generous', 'optimistic', 'pessimistic',
  'courageous', 'fearful', 'motivated', 'unmotivated', 'focused', 'distracted',
  'comfortable', 'uncomfortable', 'satisfied', 'unsatisfied', 'inspired', 'uninspired',
  'compassionate', 'indignant', 'creative', 'unimaginative', 'thoughtful', 'thoughtless',
  'concerned', 'unconcerned', 'empathetic', 'apathetic', 'amused', 'unamused',
  'interested', 'uninterested', 'passionate', 'impassive', 'surprised', 'unsurprised',
  'accepting', 'judgmental', 'appreciative', 'ungrateful', 'friendly', 'unfriendly',
  'sincere', 'insincere', 'honest', 'dishonest', 'aware', 'unaware', 'sensitive', 'insensitive',
  'ambitious', 'unambitious', 'patient', 'impatient', 'trusting', 'mistrusting',
  'loyal', 'disloyal', 'admiring', 'disapproving', 'enthusiastic', 'apathetic',
  'warm', 'cold', 'forgiving', 'unforgiving', 'thankful', 'entitled',
  'kind', 'unkind', 'silly', 'serious', 'humorous', 
  'happy', 'sad', 'angry', 'joyful', 'excited', 'bored', 'anxious', 'calm',
  'relieved', 'stressed', 'confident', 'insecure', 'grateful', 'resentful',
  'content', 'restless', 'peaceful', 'irritated', 'hopeful', 'hopeless',
  'energetic', 'lethargic', 'curious', 'indifferent', 'proud', 'ashamed',
  'loving', 'hateful', 'jealous', 'generous', 'optimistic', 'pessimistic',
  'courageous', 'fearful', 'motivated', 'unmotivated', 'focused', 'distracted',
  'comfortable', 'uncomfortable', 'satisfied', 'unsatisfied', 'inspired', 'uninspired',
  'compassionate', 'indignant', 'creative', 'unimaginative', 'thoughtful', 'thoughtless',
  'concerned', 'unconcerned', 'empathetic', 'apathetic', 'amused', 'unamused',
  'interested', 'uninterested', 'passionate', 'impassive', 'surprised', 'unsurprised',
  'accepting', 'judgmental', 'appreciative', 'ungrateful', 'friendly', 'unfriendly',
  'sincere', 'insincere', 'honest', 'dishonest', 'aware', 'unaware', 'sensitive', 'insensitive',
  'ambitious', 'unambitious', 'patient', 'impatient', 'trusting', 'mistrusting',
  'loyal', 'disloyal', 'admiring', 'disapproving', 'enthusiastic', 'apathetic',
  'warm', 'cold', 'forgiving', 'unforgiving', 'thankful', 'entitled',
  'kind', 'unkind', 'silly', 'serious', 'humorous', 'dry'

];
