export default ["Printable planner pages",  
"Social media templates",  
"Instagram story highlight covers",  
"Digital scrapbooking papers",  
"Graphic design templates",  
"Printable wall art",  
"Digital clip art",  
"Digital embroidery patterns",  
"Custom fonts",  
"Digital stickers",  
"Custom logos",  
"Printable party invitations",  
"Customized digital portrait illustrations",  
"Digital patterns for sewing",  
"Printable recipe cards",  
"Custom digital invitations",  
"Digital art prints",  
"Customized social media posts",  
"Digital coloring pages",  
"Printable planner stickers",  
"Customized website design templates",  
"Printable journal pages",  
"Printable gift tags",  
"Customized phone wallpapers",  
"Digital mockups for product photography",  
"Printable to-do lists",  
"Digital recipe book",  
"Customized wedding invitation templates",  
"Digital collage sheets",  
"Customized branding kits",  
"Printable habit trackers",  
"Customized email signature templates",  
"Digital printable calendars",  
"Printable thank-you cards",  
"Customized baby shower invitation templates",  
"Digital wedding seating charts",  
"Printable daily affirmations",  
"Customized family tree templates",  
"Digital wedding programs",  
"Printable party decorations",  
"Customized resume templates",  
"Digital scrapbooking elements",  
"Printable wall calendars",  
"Customized gift certificate templates",  
"Digital travel planner",  
"Printable bookmarks",  
"Customized social media banner templates",  
"Digital photo overlays",  
"Printable weekly meal planners",  
"Customized business card templates",  
"Digital mood boards",  
"Printable invitations for kids' parties",  
"Customized resume cover letter templates",  
"Digital photo frames",  
"Printable chore charts",  
"Customized invitation envelopes",  
"Digital business plan templates",  
"Printable coupon books",  
"Customized social media icon sets",  
"Digital wedding thank-you cards",  
"Printable wedding favor tags",  
"Customized email newsletter templates",  
"Digital photo album templates",  
"Printable gift certificates",  
"Customized logo designs for blogs",  
"Digital wedding signs",  
"Printable photo booth props",  
"Customized menu templates",  
"Digital planner stickers",  
"Printable party banners",  
"Customized photo album templates",  
"Digital recipe cards",  
"Printable wall art quotes",  
"Customized gift tag templates",  
"Digital social media templates for events",  
"Printable place cards",  
"Customized web buttons",  
"Digital invitation inserts",  
"Printable workout plans",  
"Customized social media profile templates",  
"Digital menu boards for restaurants",  
"Printable packing lists",  
"Customized brochures",  
"Digital graduation announcement templates",  
"Printable garden planner",  
"Customized t-shirt designs",  
"Digital wedding photo books",  
"Printable party games",  
"Customized promotional materials for events",  
"Digital art tutorials",  
"Printable business forms",  
"Customized product packaging designs",  
"Digital wedding signage",  
"Printable photo albums",  
"Customized menu boards for cafes",  
"Digital portfolio templates",  
"Printable recipe booklets",  
"Customized book cover designs",  
"Digital product catalogues",  
"Printable art prints for children's rooms."];