export default [
    "Bright blue eyes, sharp nose, thin lips.",
    "Round face, small eyes, freckles, dimpled chin.",
    "Long face, bushy eyebrows, wide smile, deep-set eyes.",
    "Square jaw, high cheekbones, small ears.",
    "Oval face, large hazel eyes, straight nose.",
    "Soft features, gentle eyes, rosy cheeks.",
    "Prominent chin, curly hair, piercing green eyes.",
    "Narrow face, long nose, full lips, small eyes.",
    "Broad forehead, thin eyebrows, plump cheeks.",
    "Sharp features, almond-shaped eyes, prominent cheekbones.",
    "Smooth skin, round cheeks, small mouth.",
    "Defined jawline, deep blue eyes, short hair.",
    "Strong brow, wide-set eyes, firm mouth.",
    "Angular face, high forehead, small brown eyes.",
    "Flat cheeks, thin lips, hooked nose.",
    "Youthful appearance, sparkling eyes, light freckles.",
    "Rugged features, intense eyes, strong nose.",
    "Soft jawline, wide eyes, thin, arched eyebrows.",
    "Heart-shaped face, large eyes, small, upturned nose.",
    "Chiseled features, stern expression, piercing gaze.",
    "Round eyes, freckled nose, playful smile.",
    "Gentle expression, soft eyes, faint smile.",
    "Sharp cheekbones, stern look, thin lips.",
    "Wide forehead, kind eyes, soft smile.",
    "Narrow eyes, strong jawline, straight eyebrows.",
    "Deep-set eyes, prominent nose, full beard.",
    "Soft features, wide eyes, freckles, round chin.",
    "Angular jaw, piercing brown eyes, thick eyebrows.",
    "Square face, bushy beard, small, deep eyes.",
    "Broad nose, full lips, warm smile.",
    "Oval face, big green eyes, wavy hair.",
    "Glistening eyes, high cheekbones, straight nose.",
    "Sunken eyes, scarred cheek, stern mouth.",
    "Youthful glow, bright eyes, dimpled smile.",
    "Laugh lines, twinkling eyes, graying hair.",
    "Weathered skin, piercing gaze, thin lips.",
    "Pale complexion, sharp features, icy stare.",
    "Rosy cheeks, button nose, kind expression.",
    "Wrinkled forehead, squinting eyes, wide smile.",
    "Long face, pointed chin, almond-shaped eyes.",
    "Tanned skin, chiseled jaw, hooded eyes.",
    "Soft gaze, round cheeks, small mouth.",
    "Drooping eyes, furrowed brow, full mustache.",
    "Smooth skin, thin eyebrows, pursed lips.",
    "High cheekbones, small eyes, thin mustache.",
    "Squarish jaw, deep-set eyes, straight hairline.",
    "Gaunt face, hollow cheeks, piercing blue eyes.",
    "Round chin, soft eyes, faint freckles.",
    "Stern expression, bushy eyebrows, bald head.",
    "Delicate features, small ears, gentle smile.",
    "Thick eyelashes, full lips, rosy complexion.",
    "Wavy hair, bright smile, twinkling eyes.",
    "Rounded jaw, heavy eyebrows, intense gaze.",
    "Strong nose, small eyes, chapped lips.",
    "Broad face, smiling eyes, thick beard.",
    "Tight jaw, intense brown eyes, crew cut.",
    "Prominent cheekbones, narrow eyes, thin lips.",
    "Sunken cheeks, furrowed brow, thinning hair.",
    "Wrinkled skin, kind eyes, gentle smile.",
    "Chubby cheeks, button nose, soft gaze.",
    "Flat nose, wide lips, round face.",
    "Sharp nose, high forehead, small, bright eyes.",
    "Pale skin, dark circles, thin eyebrows.",
    "Long eyelashes, wide smile, dimpled cheeks.",
    "Short hair, square jaw, hooded eyes.",
    "Hollow eyes, gaunt cheeks, stubble beard.",
    "Full lips, round face, small eyes.",
    "Pointed chin, arched eyebrows, stern look.",
    "Wavy hairline, bright eyes, freckled nose.",
    "Smooth forehead, narrow eyes, pointed nose.",
    "Thick beard, small ears, furrowed brow.",
    "Small chin, wide-set eyes, thin lips.",
    "Bulging eyes, flat nose, wide mouth.",
    "Prominent jawline, deep-set eyes, thick eyebrows.",
    "Delicate features, soft eyes, subtle smile.",
    "High cheekbones, long lashes, gentle expression.",
    "Round face, sparkling eyes, cherry lips.",
    "Sharp jawline, almond eyes, sleek eyebrows.",
    "Oval face, wide eyes, rosy cheeks.",
    "Small features, kind gaze, thin lips.",
    "Full cheeks, dimples, warm, inviting smile.",
    "Narrow face, piercing gaze, straight nose.",
    "Soft jaw, bright eyes, glossy lips.",
    "Prominent cheekbones, hooded eyes, full lips.",
    "Smooth forehead, arched eyebrows, small mouth.",
    "Defined jawline, deep-set eyes, subtle makeup.",
    "Broad forehead, twinkling eyes, plush lips.",
    "Angular face, stern look, chiseled cheeks.",
    "Sun-kissed skin, freckles, beaming smile.",
    "Elegant features, serene eyes, graceful smile.",
    "Youthful glow, big eyes, playful smirk.",
    "Weathered skin, wise eyes, firm mouth.",
    "Gentle frown, delicate nose, thin eyebrows.",
    "Round chin, soft gaze, painted lips.",
    "Charming smile, heart-shaped face, sparkling eyes.",
    "Wrinkled cheeks, wise gaze, gentle lips.",
    "Petite nose, flushed cheeks, shy smile.",
    "Intense eyes, strong jaw, bold lipstick.",
    "Glowing complexion, full eyebrows, radiant smile.",
    "Gaunt face, hollow cheeks, piercing gaze.",
    "Doe eyes, button nose, glossy lips.",
    "Sharp features, hawkish nose, smirking mouth.",
    "Wavy hairline, curious eyes, soft smile.",
    "Bubbly cheeks, small mouth, twinkling eyes.",
    "Square jaw, alert eyes, neutral expression.",
    "Strong cheekbones, narrow eyes, pouty lips.",
    "Laugh lines, warm eyes, tender smile.",
    "Tanned skin, lively eyes, cheerful grin.",
    "Flat cheeks, serious mouth, thin lips.",
    "Full lashes, plump lips, blushing cheeks.",
    "Classic beauty, serene expression, fine features.",
    "Heavy brows, intense stare, firm jaw.",
    "Porcelain skin, delicate lips, shy eyes.",
    "Sculpted face, bold eyes, striking makeup.",
    "Graceful neck, soft features, warm eyes.",
    "Prominent chin, wise eyes, knowing smile.",
    "Short hair, playful look, light freckles.",
    "Dramatic eyes, arched brows, confident air.",
    "Sultry look, full lips, sharp cheekbones.",
    "Long neck, elegant nose, demure smile.",
    "Youthful freckles, vibrant eyes, lively expression.",
    "Regal posture, commanding eyes, sculpted lips.",
    "Sunkissed cheeks, bright eyes, infectious laugh.",
    "Piercing blue eyes, soft cheeks, neutral expression.",
    "Hazel eyes, natural look, serene smile.",
    "Freckled nose, kind eyes, tender expression.",
    "Strong features, determined look, bold presence.",
    "Plump cheeks, joyous smile, sparkling eyes.",
    "Tight curls, playful grin, twinkling eyes.",
    "Sleek hair, regal bearing, piercing gaze.",
    "Soft curls, gentle smile, dreamy eyes.",
    "Vivid eyes, striking features, confident demeanor.",
    "Radiant skin, captivating eyes, graceful smile.",
    "Elegant brows, mesmerizing gaze, soft, full lips.",
    "Luminous complexion, striking eyes, delicate smile.",
    "Symmetrical features, glowing skin, charming grin.",
    "Dazzling smile, high cheekbones, alluring eyes.",
    "Refined nose, tender lips, serene expression.",
    "Exquisite features, bewitching eyes, enchanting smile.",
    "Sleek hair, porcelain skin, gentle laugh.",
    "Captivating look, plush lips, flawless skin.",
    "Angelic presence, soft gaze, heartwarming smile.",
    "Stunning eyes, perfect jawline, irresistible charm.",
    "Ethereal beauty, dreamy eyes, serene demeanor.",
    "Alluring eyes, rosy cheeks, magnetic smile.",
    "Enchanting visage, sparkling eyes, luscious lips.",
    "Luxurious hair, captivating smile, hypnotic eyes.",
    "Breathtaking features, soulful eyes, captivating grace.",
    "Vivid eyes, sculpted face, bewitching smile.",
    "Regal posture, exquisite features, radiant glow.",
    "Doe-eyed beauty, cherubic lips, entrancing aura.",
    "Majestic look, sculpted brows, striking charm.",
    "Graceful elegance, tender gaze, inviting smile.",
    "Flawless skin, magnetic eyes, spellbinding expression.",
    "Entrancing eyes, sculpted cheekbones, alluring lips.",
    "Angelic face, sparkling eyes, infectious laugh.",
    "Classic beauty, stunning gaze, captivating presence.",
    "Timeless elegance, deep eyes, graceful smile.",
    "Glamorous look, lustrous hair, engaging smile.",
    "Refined elegance, piercing eyes, beguiling smile.",
    "Lustrous eyes, enchanting features, magnetic aura.",
    "Sultry gaze, flawless skin, charming lips.",
    "Irresistible allure, radiant complexion, heart-stopping smile.",
    "Stunning allure, mesmerizing eyes, graceful poise.",
    "Bewitching presence, luminous skin, enchanting laugh."
];