export default [
  'Angelfish',
  'Barracuda',
  'Blue Whale',
  'Clam',
  'Clownfish',
  'Crab',
  'Cuttlefish',
  'Dolphin',
  'Eel',
  'Fiddler Crab',
  'Flounder',
  'Giant Squid',
  'Great White Shark',
  'Green Sea Turtle',
  'Humpback Whale',
  'Jellyfish',
  'Krill',
  'Lionfish',
  'Lobster',
  'Manta Ray',
  'Manatee',
  'Megalodon',
  'Moray Eel',
  'Nautilus',
  'Nudibranch',
  'Octopus',
  'Orca',
  'Oyster',
  'Penguin',
  'Plankton',
  'Pufferfish',
  'Ray',
  'Red Snapper',
  'Sardine',
  'Sea Anemone',
  'Sea Cucumber',
  'Sea Horse',
  'Sea Lion',
  'Sea Otter',
  'Sea Slug',
  'Sea Star',
  'Sea Urchin',
  'Seagull',
  'Seahorse',
  'Seal',
  'Shark',
  'Shrimp',
  'Squid',
  'Starfish',
  'Stingray',
  'Swordfish',
  'Tiger Shark',
  'Tuna',
  'Walrus',
  'Whale Shark',
  'Zooplankton',
  'Albacore',
  'Amphipod',
  'Anchovy',
  'Arctic Char',
  'Barnacle',
  'Beluga Whale',
  'Bryozoan',
  'Chiton',
  'Clione',
  'Cockle',
  'Comb Jelly',
  'Copepod',
  'Crinoid',
  'Dungeness Crab',
  'Ghost Shrimp',
  'Giant Isopod',
  'Giant Pacific Octopus',
  'Goby',
  'Gooseneck Barnacle',
  'Gorgonian',
  'Grass Shrimp',
  'Gray Whale',
  'Grouper',
  'Hagfish',
  'Harbor Seal',
  'Herring',
  'Horseshoe Crab',
  'Irukandji Jellyfish',
  'Kelp Crab',
  'Kelpfish',
  'King Crab',
  'Lamprey',
  'Limpet',
  'Lingcod',
  'Longfin Squid',
  'Mackerel',
  'Mahi Mahi',
  'Mantis Shrimp',
  'Moon Jellyfish',
  'Mussel',
  'Narwhal',
  'Northern Fur Seal',
  'Northern Shrimp',
  'Oarfish',
  'Pacific Halibut',
  'Pacific Herring',
  'Prawn',
  'Purple Sea Urchin',
  'Queen Conch',
  'Rockfish',
  'Salmon',
  'Sand Dollar',
  'Sardine',
  'Scallop',
  'Sea Dragon',
  'Sea Fan',
  'Sea Slug',
  'Sea Spider',
  'Sea Sponge',
  'Sheepshead',
  'Shortfin Mako Shark',
  'Snow Crab',
  'Spiny Dogfish',
  'Spot Prawn',
  'Squid',
  'Starfish',
  'Stone Crab',
  'Surf Clam',
  'Tanner Crab',
  'Tiger Fish',
  'Albacore Tuna',
  'Anchovy',
  'Arctic Char',
  'Barracuda',
  'Bass',
  'Bluegill',
  'Carp',
  'Catfish',
  'Chub',
  'Clownfish',
  'Cod',
  'Crappie',
  'Dolphinfish',
  'Eel',
  'Flounder',
  'Grouper',
  'Haddock',
  'Halibut',
  'Herring',
  'Kingfish',
  'Lamprey',
  'Lingcod',
  'Mackerel',
  'Mahi Mahi',
  'Marlin',
  'Mullet',
  'Northern Pike',
  'Perch',
  'Pollock',
  'Pompano',
  'Rainbow Trout',
  'Red Snapper',
  'Rockfish',
  'Salmon',
  'Sardine',
  'Sea Bass',
  'Shark',
  'Skate',
  'Smelt',
  'Sole',
  'Swordfish',
  'Tilapia',
  'Trout',
  'Tuna',
  'Walleye',
  'Whitefish',
  'Yellow Perch',
  'Yellowfin Tuna',
  'Zander',
  'Alligator Gar',
  'Angelfish',
  'Arapaima',
  'Arowana',
  'Bichir',
  'Butterflyfish',
  'Cardinalfish',
  'Cichlid',
  'Discus',
  'Dragonfish',
  'Electric Eel',
  'Emperor Angelfish',
  'Filefish',
  'Firefish',
  'Giant Gourami',
  'Gourami',
  'Gramma',
  'Hatchetfish',
  'Hogfish',
  'Jellybean Parrotfish',
  'Kissing Gourami',
  'Koi',
  'Lionfish',
  'Mandarinfish',
  'Moorish Idol',
  'Neon Tetra',
  'Oscar',
  'Parrotfish',
  'Piranha',
  'Pufferfish',
  'Queen Angelfish',
  'Rainbowfish',
  'Red Devil Cichlid',
  'Redtail Catfish',
  'Scorpionfish',
  'Sea Horse',
  'Siamese Fighting Fish',
  'Tetra',
  'Threadfin Butterflyfish',
  'Triggerfish',
  'Wrasse',
  'X-Ray Tetra',
  'Yellow Tang']
