export default [
  "Pizza",
  "Burger",
  "Sushi",
  "Taco",
  "Fried Chicken",
  "Ramen",
  "Steak",
  "Pasta",
  "Burrito",
  "Hot Dog",
  "Curry",
  "Fajitas",
  "Dim Sum",
  "Noodle Soup",
  "Pad Thai",
  "Tikka Masala",
  "Tandoori Chicken",
  "Chicken Parmesan",
  "Meatloaf",
  "Fish and Chips",
  "Lasagna",
  "Biryani",
  "Roast Beef",
  "Shrimp Scampi",
  "Sashimi",
  "Pho",
  "Miso Soup",
  "Beef Stroganoff",
  "Crab Cakes",
  "Shepherd's Pie",
  "Peking Duck",
  "Gyoza",
  "Fried Rice",
  "Baklava",
  "Borscht",
  "Pierogi",
  "Lamb Chops",
  "Butter Chicken",
  "Chimichanga",
  "Paella",
  "Chow Mein",
  "Gumbo",
  "Enchiladas",
  "Huevos Rancheros",
  "Pesto",
  "Goulash",
  "Scallops",
  "Stuffed Peppers",
  "Clam Chowder",
  "Ratatouille",
  "Gazpacho",
  "Crab Rangoon",
  "Chicken Adobo",
  "Jambalaya",
  "Samosas",
  "Chicken Tikka",
  "Chana Masala",
  "Falafel",
  "Schnitzel",
  "Bouillabaisse",
  "Tom Yum Soup",
  "Ceviche",
  "Corned Beef and Cabbage",
  "Beef Bourguignon",
  "Lobster Bisque",
  "Shawarma",
  "Butternut Squash Soup",
  "Osso Buco",
  "Hamburger Helper",
  "Spanakopita",
  "Frittata",
  "Torta",
  "Cottage Pie",
  "Bangers and Mash",
  "Carbonara",
  "Ravioli",
  "Mac and Cheese",
  "Fajita Quesadilla",
  "Gnocchi",
  "Scampi",
  "Tamales",
  "Kebabs",
  "Fish Tacos",
  "Jerk Chicken",
  "Pulled Pork",
  "Beef Brisket",
  "Cornish Pasty",
"pancake",
'ice-cream sundae',
'chicken fried steak',
"Grand Slam Breakfast",
  "Lumberjack Slam",
  "Belgian Waffle Slam",
  "All-American Slam",
  "Build Your Own Grand Slam",
  "Moons Over My Hammy",
  "Country-Fried Steak and Eggs",
  "Sirloin Steak and Eggs",
  "T-Bone Steak and Eggs",
  "Chicken Fried Chicken and Eggs",
  "Pancake Breakfast",
  "Blueberry Pancake Breakfast",
  "Strawberry Pancake Breakfast",
  "Chocolate Chip Pancake Breakfast",
  "Banana Pecan Pancake Breakfast",
  "Biscuits and Gravy",
  "Super Bird",
  "Club Sandwich",
  "French Dip",
  "Meatball Marinara",
  "Tuna Melt",
  "BLT Sandwich",
  "Grilled Cheese Sandwich",
  "Philly Cheesesteak",
  "Country Fried Steak",
  "Meatloaf",
  "Pot Roast",
  "Spaghetti and Meatballs",
  "Fish and Chips",
  "Chicken Fried Steak",
  "Corned Beef Hash",
  "Mac and Cheese",
  "Chicken Tenders",
  "Tater Tots",
  "Onion Rings",
  "Loaded Nachos",
  "Mozzarella Sticks",
  "Chili Cheese Fries",
  "Bacon Cheeseburger",
  "Mushroom Swiss Burger",
  "Jalapeño Bacon Burger",
  "Western Burger",
  "Veggie Burger",
  "Fish Sandwich",
  "Turkey Sandwich",
  "Grilled Chicken Sandwich",
  "Fried Chicken Sandwich",
  "Quesadilla",
  "Taco Salad",
  "Cobb Salad",
  "Caesar Salad",
  "Chef's Salad",
  "Santa Fe Skillet",
  "Chicken and Broccoli Skillet",
  "Country-Fried Steak Skillet",
  "Hashbrown Skillet",
  "Chorizo Skillet",
  "Ultimate Omelette",
  "Denver Omelette",
  "Cheese Omelette",
  "Spinach and Mushroom Omelette",
  "Ham and Cheese Omelette",
  "Patty Melt",
  "Blueberry Pancakes",
  "Chocolate Chip Pancakes",
  "Banana Pecan Pancakes",
  "Belgian Waffles",
  "Strawberry Waffles",
  "Bacon",
  "Sausage",
  "Ham",
  "Corned Beef Hash and Eggs",
  "Eggs Benedict",
  "Fried Eggs and Bacon",
  "Egg and Cheese Sandwich",
  "Seared Foie Gras with Fig Compote",
  "Osetra Caviar with Blinis and Crème Fraîche",
  "Lobster Bisque with Cognac Cream",
  "Beef Carpaccio with Shaved Parmesan and Truffle Oil",
  "Risotto with Black Truffle and Mascarpone",
  "Pan-Seared Scallops with Butternut Squash Purée and Brown Butter Sage Sauce",
  "Beef Wellington with Mushroom Duxelle and Madeira Sauce",
  "Roasted Duck Breast with Cherry Port Reduction",
  "Grilled Lamb Chops with Mint Gremolata",
  "Black Angus Ribeye Steak with Béarnaise Sauce",
  "Pan-Seared Sea Bass with Lemon Beurre Blanc",
  "Roasted Chicken Breast with Natural Jus",
  "Rack of Venison with Juniper Berry Sauce",
  "Pork Tenderloin with Apple Calvados Sauce",
  "Crème Brûlée with Fresh Berries",
  "Chocolate Soufflé with Raspberry Sauce",
  "Molten Chocolate Cake with Vanilla Bean Ice Cream",
  "New York Cheesecake with Blueberry Compote",
  "Tiramisu with Espresso Syrup",
  "Panna Cotta with Fruit Coulis",
  "Sushi",
  "Ramen",
  "Pho",
  "Pad Thai",
  "Miso Soup",
  "Korean BBQ",
  "Chicken Tikka Masala",
  "Curry Laksa",
  "Biryani",
  "Beef Noodle Soup",
  "Bulgogi",
  "Gyoza",
  "Dumplings",
  "Tom Yum Soup",
  "Satay",
  "Char Siu",
  "Katsu Curry",
  "Green Curry",
  "Red Curry",
  "Laksa",
  "Bibimbap",
  "Kimchi Fried Rice",
  "Hainanese Chicken Rice",
  "Nasi Lemak",
  "Nasi Goreng",
  "Peking Duck",
  "Hot Pot",
  "Szechuan Chicken",
  "Kung Pao Chicken",
  "Mapo Tofu",
  "Shumai",
  "Banh Mi",
  "Chow Mein",
  "Lo Mein",
  "Spring Rolls",
  "Summer Rolls",
  "Laab",
  "Som Tam",
  "Khao Soi",
  "Massaman Curry",
  "Tom Kha Gai",
  "Baozi",
  "Xiaolongbao",
  "Jjajangmyeon",
  "Bulgogi Bibimbap",
  "Pad See Ew",
  "Tomato Egg Stir Fry",
  "Cantonese Fried Rice",
  "Yangzhou Fried Rice",
  "Hokkien Char Mee",
  "Chow Fun",
  "Hakka Noodles",
  "Hakka Yong Tau Foo",
  "Malaysian Satay",
  "Laksa Johor",
  "Nasi Kandar",
  "Murtabak",
  "Roti Canai",
  "Tandoori Chicken",
  "Butter Chicken",
  "Naan",
  "Chana Masala",
  "Saag Paneer",
  "Aloo Gobi",
  "Fish Curry",
  "Palak Paneer",
  "Bhindi Masala",
  "Baingan Bharta",
  "Goan Fish Curry",
  "Hyderabadi Biryani",
  "Chicken 65",
  "Andhra Chicken Curry",
  "Kerala Fish Curry",
  "Pani Puri",
  "Vada Pav",
  "Masala Dosa",
  "Medu Vada",
  "Thosai",
  "Nasi Campur",
  "Nasi Padang",
  "Rendang",
  "Gulai",
  "Sate Lilit",
  "Soto Ayam",
  "Mie Goreng",
  "Sop Buntut",
  "Bak Kut Teh",
  "Char Kway Teow",
  "Roast Pork",
  "Pork Belly",
  "Taiwanese Beef Noodle Soup",
  "Beef Rendang",
  "Sambal Udang",
  "Ayam Goreng",
  "Ayam Penyet",
  "Spaghetti with tomato sauce",
  "Vegetable stir-fry with rice",
  "Tuna salad sandwich",
  "Grilled cheese sandwich",
  "Omelette with cheese and vegetables",
  "Chili con carne",
  "Tomato soup with grilled cheese",
  "Pasta with garlic and olive oil",
  "Fried rice with vegetables and egg",
  "Quesadilla with beans and cheese",
  "Bean burrito with rice",
  "Taco salad",
  "Chicken quesadilla",
  "Fried egg sandwich",
  "Tortilla soup",
  "Chicken noodle soup",
  "Beef stir-fry with vegetables",
  "Baked potato with cheese and broccoli",
  "Veggie burger with fries",
  "Pita bread with hummus and vegetables",
  "Ramen noodle soup with vegetables",
  "Macaroni and cheese",
  "Pancakes with syrup",
  "French toast with syrup",
  "Waffles with syrup",
  "Breakfast burrito with eggs and sausage",
  "BLT sandwich",
  "Cobb salad",
  "Caesar salad",
  "Greek salad",
  "Pulled pork sandwich",
  "Grilled chicken sandwich",
  "Baked chicken with vegetables",
  "Baked fish with vegetables",
  "Bean soup with vegetables",
  "Black bean chili",
  "Rice and beans",
  "Spinach and feta omelette",
  "Mushroom and cheese omelette",
  "Tomato and mozzarella salad",
  "Cucumber and tomato salad",
  "Eggplant parmesan",
  "Baked ziti with cheese",
  "Pepperoni pizza",
  "Margherita pizza",
  "Vegetable pizza",
  "Chicken and broccoli alfredo",
  "Fettuccine alfredo",
  "Beef and broccoli stir-fry",
  "Lentil soup",
  "Split pea soup",
  "Potato soup",
  "Minestrone soup",
  "Chicken fajitas",
  "Beef tacos",
  "Vegetable tacos",
  "Chicken fried rice",
  "Beef fried rice",
  "Vegetable fried rice",
  "Tomato and basil pizza",
  "Pesto pasta",
  "Pesto pizza",
  "Caprese salad",
  "Roasted chicken with vegetables",
  "Roasted vegetables",
  "Quiche with vegetables and cheese",
  "Tofu stir-fry with vegetables",
  "Veggie stir-fry with tofu",
  "Black bean and corn salad",
  "Miso soup",
  "Soba noodle salad",
  "Tuna salad with avocado",
  "Salmon burger with fries",
  "Egg salad sandwich",
  "Fruit salad",
  "Yogurt and granola",
  "Peanut butter and jelly sandwich",
  "Hummus and pita chips",
  "Chicken and vegetable curry",
  "Beef and vegetable curry",
  "Vegetable curry",
  "Sweet and sour chicken with vegetables",
  "Sweet and sour pork with vegetables",
  "Egg drop soup",
  "Hot and sour soup",
  "Sesame noodles with vegetables",
  "Sesame chicken with vegetables",
  "Tofu and vegetable curry",
  "Veggie burger with avocado",
  "BBQ chicken sandwich",
  "BBQ pulled pork sandwich",
  "Taco bowl with rice and beans",
  "Vegetable lasagna",
   "Bagel",
  "Bacon",
  "Banana bread",
  "Biscuits and gravy",
  "Blueberry muffin",
  "Breakfast burrito",
  "Breakfast sandwich",
  "Cereal",
  "Cheese omelette",
  "Chilaquiles",
  "Chocolate croissant",
  "Cinnamon roll",
  "Coffee cake",
  "Corned beef hash",
  "Croissant",
  "Egg and cheese sandwich",
  "Egg salad sandwich",
  "Egg white omelette",
  "Eggs benedict",
  "English muffin",
  "French toast",
  "Frittata",
  "Fruit salad",
  "Granola",
  "Greek yogurt",
  "Green smoothie",
  "Grits",
  "Ham and cheese omelette",
  "Hash browns",
  "Home fries",
  "Huevos rancheros",
  "Irish breakfast",
  "Lox and bagel",
  "Mango smoothie",
  "Muesli",
  "Oatmeal",
  "Omelette",
  "Orange juice",
  "Pancakes",
  "Papaya smoothie",
  "Peanut butter and jelly sandwich",
  "Porridge",
  "Potato pancakes",
  "Protein shake",
  "Quiche",
  "Raspberry smoothie",
  "Sausage and egg sandwich",
  "Sausage and gravy",
  "Scrambled eggs",
  "Smoked salmon",
  "Smoothie bowl",
  "Spinach and feta omelette",
  "Strawberry smoothie",
  "Sweet potato hash",
  "Tater tots",
  "Tea",
  "Toasted bagel",
  "Toasted English muffin",
  "Turkey sausage",
  "Vegetable omelette",
  "Waffles",
  "Yogurt parfait",
  "Zucchini and mushroom omelette",
  "Apple cider donut",
  "Avocado toast",
  "Belgian waffle",
  "Blackberry muffin",
  "Blueberry pancakes",
  "Breakfast pizza",
  "Breakfast quesadilla",
  "Buckwheat pancakes",
  "Cantaloupe smoothie",
  "Cherry scone",
  "Chia pudding",
  "Chocolate chip pancakes",
  "Coffee",
  "Corn muffin",
  "Cottage cheese",
  "Cranberry muffin",
  "Cream of wheat",
  "Egg casserole",
  "Egg in a basket",
  "Egg muffin",
  "Egg salad",
  "Egg white sandwich",
  "Eggplant omelette",
  "Feta cheese omelette",
  "Flapjacks",
  "Fresh fruit smoothie",
  "Fried egg sandwich",
  "Fruit and nut granola",
  "Goat cheese omelette",
  "Golden raisin scone",
  "Gouda and bacon omelette",
  "Green juice",
  "Hamburger patty and eggs",
  "Hazelnut coffee",
  "Homemade granola bars",
  "Honeydew smoothie",
  "Huevos a la Mexicana",
  "Kale smoothie",
  "Lemon poppy seed muffin",
  "Maple syrup",
  "Mixed berry smoothie",
  "Oatmeal raisin cookie",
  "Oatmeal with fruit"
]





