export default [
  "Apple",
  "Apricot",
  "Avocado",
  "Banana",
  "Blackberry",
  "Blueberry",
  "Cantaloupe",
  "Cherry",
  "Coconut",
  "Cranberry",
  "Cucumber",
  "Date",
  "Dragonfruit",
  "Durian",
  "Elderberry",
  "Fig",
  "Grape",
  "Grapefruit",
  "Guava",
  "Honeydew",
  "Jackfruit",
  "Kiwi",
  "Kumquat",
  "Lemon",
  "Lime",
  "Lychee",
  "Mango",
  "Mangosteen",
  "Mulberry",
  "Nectarine",
  "Orange",
  "Papaya",
  "Passionfruit",
  "Peach",
  "Pear",
  "Persimmon",
  "Pineapple",
  "Plum",
  "Pomegranate",
  "Quince",
  "Raspberry",
  "Redcurrant",
  "Starfruit",
  "Strawberry",
  "Tangerine",
  "Tomato",
  "Watermelon",
  "Acai Berry",
  "Acerola Cherry",
  "African Cherry Orange",
  "African Cucumber",
  "African Mango",
  "Almond Fruit",
  "American Black Elderberry",
  "Arctic Raspberry",
  "Barbados Cherry",
  "Black Currant",
  "Blood Orange",
  "Breadfruit",
  "Buddha's Hand",
  "Buffalo Currant",
  "Cape Gooseberry",
  "Ceylon Gooseberry",
  "Cherimoya",
  "Chico Fruit",
  "Chinese Bayberry",
  "Chinese Date",
  "Chinese Grapefruit",
  "Clementine",
  "Cloudberry",
  "Cocoa Fruit",
  "Cornelian Cherry",
  "Crabapple",
  "Cupuacu",
  "Damson",
  "Desert Lime",
  "Emu Apple",
  "Feijoa",
  "Gac Fruit",
  "Goumi Berry",
  "Grumichama",
  "Hackberry",
  "Hawthorn Berry",
  "Jabuticaba",
  "Japanese Cherry",
  "Japanese Persimmon",
  "Jostaberry",
  "Jujube",
  "Kaffir Lime",
  "Kakadu Plum",
  "Karonda",
  "Kei Apple",
  "Kiwano",
  "Kiwifruit",
  "Kumato",
  "Limequat",
  "Longan",
  "Mamey Sapote",
  "Manzanita Berry",
  "Medlar",
  "Monstera Deliciosa",
  "Mountain Soursop",
  "Muscadine",
  "Naranjilla",
  "Neem Fruit",
  "Noni Fruit",
  "Olive",
  "Otaheite Apple",
  "Pepino",
  "Peruvian Apple Cactus",
  "Physalis",
  "Pitaya",
  "Poha Berry",
  "Pomelo",
  "Prickly Pear",
  "Purple Mangosteen",
  "Rambutan",
  "Red Mombin",
  "Roselle",
  "Rowan Berry",
  "Salak Fruit",
  "Sapodilla",
  "Saskatoon Berry"]