export default [  
"Paula Scher",  
"Saul Bass",  
"Jessica Walsh",  
"Milton Glaser",  
"Chip Kidd",  
"David Carson",  
"Michael Bierut",  
"Aaron Draplin",  
"Massimo Vignelli",  
"Ellen Lupton",  
"Stefan Sagmeister",  
"Tibor Kalman",  
"Kyle Cooper",  
"Debbie Millman",  
"Brian Collins",  
"Wim Crouwel",  
"Paul Rand",  
"Erik Spiekermann",  
"April Greiman",  
"Lance Wyman",  
"Maggie Macnab",  
"Jenny Holzer",  
"David Airey",  
"Luke Wroblewski",  
"Joshua Davis",  
"John Maeda",  
"Alex Trochut",  
"Jessica Hische",  
"Rian Hughes",  
"Armin Hofmann",  
"Jan Tschichold",  
"Herb Lubalin",  
"Bradbury Thompson",  
"Jessica Svendsen",  
"Emily Oberman",  
"Kate Moross",  
"Tad Carpenter",  
"Neville Brody",  
"Jonathan Barnbrook",  
"Simon Walker",  
"Timothy Goodman",  
"Steve Powers",  
"Anthony Burrill",  
"Peter Saville",  
"Mirko Ilic",  
"Chermayeff & Geismar",  
"Sagmeister & Walsh",  
"Landor Associates",  
"Pentagram",  
"Wolff Olins",  
"MetaDesign",  
"Chase Design Group",  
"Happy Cog",  
"Fantasy Interactive",  
"Seymour Chwast",  
"George Lois",  
"Ivan Chermayeff",  
"David Hillman",  
"David Gentleman",  
"Alan Fletcher",  
"Brian Tattersfield",  
"Vaughan Oliver",  
"Peter Blake",  
"Gary Taxali",  
"Mark Ryden",  
"Shepard Fairey",  
"Banksy",  
"Barbara Kruger",  
"Yayoi Kusama",  
"Kaws",  
"Takashi Murakami",  
"Yuko Shimizu",  
"Marcel Dzama",  
"Barry McGee",  
"Chris Johanson",  
"Robbie Conal",  
"Joan Miró",  
"Henri Matisse",  
"Pablo Picasso",  
"Salvador Dalí",  
"Vincent van Gogh",  
"Andy Warhol",  
"Roy Lichtenstein",  
"Keith Haring",  
"Edward Hopper",  
"Grant Wood",  
"Georgia O'Keeffe",  
"Frida Kahlo",  
"Jean-Michel Basquiat",  
"Bridget Riley",  
"David Hockney",  
"Frank Stella",  
"Sol LeWitt",  
"Donald Judd",  
"Robert Rauschenberg",  
"Jasper Johns",  
"Mark Rothko",  
"Willem de Kooning",  
"Jackson Pollock",  
"Alfred Stieglitz"];