export default [  "Afro",  
"Angled Bob",  
"Asymmetric Bob",  
"Balayage",  
"Bangs",  
"Beachy Waves",  
"Beehive",  
"Big Curls",  
"Blonde",  
"Blunt Bob",  
"Braids",  
"Bridal Updo",  
"Bun",  
"Chignon",  
"Color Highlights",  
"Classic Bob",  
"Cornrows",  
"Crew Cut",  
"Crimped",  
"Curly Bob",  
"Curly Pixie Cut",  
"Deep Side Part",  
"Dreadlocks",  
"Dutch Braid",  
"Emo Hair",  
"Faux Hawk",  
"Feathered",  
"Finger Waves",  
"Flipped Bob",  
"French Braid",  
"French Twist",  
"Fringe",  
"Full Fringe",  
"Braids",  
"Half-half",  
"High Ponytail",  
"Highlights",  
"Hime Cut",  
"Hippie",  
"Inverted Bob",  
"Jheri Curl",  
"Curly",  
"Knot",  
"Layered Bob",  
"Loose Curls",  
"Low Ponytail",  
"Bun",  
"Mohawk",  
"Mullet",  
"Natural",  
"Ombre",  
"Pigtails",  
"Pixie Cut",  
"Plaits",  
"Pompadour",  
"Ponytail",  
"Purple",  
"Ringlets",  
"Rockabilly",  
"Roller Set",  
"Rooty Blonde",  
"Shag",  
"Short Bob",  
"Side Bangs",  
"Side Braid",  
"Side Part",  
"Side Ponytail",  
"Sleek Ponytail",  
"Space Buns",  
"Spiky",  
"Straight",  
"Super Short Pixie Cut",  
"Surfer",  
"Textured Bob",  
"Top Knot",  
"Twist Out",  
"Undercut",  
"Updo",  
"Vintage Waves",  
"Wavy",  
"Wedding",   
"Wispy Bangs",  
"Xpression Braids",  
"Yarn Braids",  
"Zig Zag Part"]