export default [
  "Brahma",
  "Vishnu",
  "Shiva",
  "Ganesha",
  "Indra",
  "Kali",
  "Durga",
  "Lakshmi",
  "Saraswati",
  "Yama",
  "Hanuman",
  "Varuna",
  "Agni",
  "Surya",
  "Chandra",
  "Kartikeya",
  "Parvati",
  "Radha",
  "Krishna",
  "Rama",
  "Sita",
  "Bhumi",
  "Dhanvantari",
  "Kamadeva",
  "Dattatreya",
  "Garuda",
  "Kuber",
  "Narayana",
  "Shesha",
  "Vayu",
  "Budha",
  "Rahu",
  "Ketu",
  "Vasuki",
  "Ananta",
  "Kamadhenu",
  "Uma",
  "Rudra",
  "Bhairava",
  "Chitragupta",
  "Jambavan",
  "Vasudeva",
  "Madhava",
  "Narada",
  "Narasimha",
  "Pancha Bhoota",
  "Savitri",
  "Urvashi",
  "Yaksha",
  "Yakshini",
  "Bhumi Devi",
  "Draupadi",
  "Maha Lakshmi",
  "Maheshwara",
  "Mohini",
  "Rati",
  "Santoshi Mata",
  "Shakuni",
  "Tulsi Devi",
  "Ugrasena",
  "Vamana",
  "Vijaya",
  "Yashoda",
  "Ambarisha",
  "Anasuya",
  "Bali",
  "Bhima",
  "Brahmani",
  "Chamunda",
  "Daksha",
  "Dakshinamurti",
  "Devi",
  "Dhruva",
  "Diti",
  "Draupadi",
  "Ganga",
  "Gayatri",
  "Goddess Kalaratri",
  "Goddess Katyayani",
  "Goddess Siddhidatri",
  "Goddess Skandamata",
  "Goddess Brahmacharini",
  "Goddess Chandraghanta",
  "Goddess Kushmanda",
  "Goddess Mahagauri",
  "Goddess Shailputri",
  "Goddess Vijaya",
  "Goddess Chandika",
  "Goddess Mrityunjaya",
  "Goddess Annapurna",
  "Goddess Bhubaneswari",
  "Goddess Bhuvaneshwari",
  "Goddess Gauri",
  "Goddess Jwalamukhi",
  "Goddess Mahakali",
  "Goddess Mahalakshmi",
  "Goddess Matangi",
  "Goddess Parvati",
  "Goddess Raja Rajeshwari",
  "Goddess Ramakrishna",
  "Goddess Tara",
  "Goddess Tripura Sundari",
  "Goddess Vagdevi",
  "Goddess Varahi",
  "Goddess Vindhya Vasini",
  "Goddess Bhudevi",
  "Goddess Jaya",
  "Goddess Shree",
  "Goddess Sumukhi",
  "Goddess Tulja",
  "Goddess Vidya",
  "Goddess Ugra",
  "Goddess Mohana",
  "Goddess Dakshayani",
  "Goddess Maha Devi",
  "Goddess Anjaneya",
  "Goddess Maha Saraswati",
  "Goddess Matrika",
  "Goddess Meenakshi",
  "Goddess Mumbadevi",
  "Goddess Nageswari",
  "Goddess Pratyangira",
  "Goddess Sridevi",
  "Goddess Ulka",
  "Goddess Uma",
  "Goddess Vagishwari",
  "Goddess Vasavi",
  "Goddess Vasudhara",
  "Goddess Yogmaya",
  "Goddess Yogini",
  "Goddess Yogya",
  "Goddess Yogini",
  "Goddess Yagnyeshwari",
  "Goddess Amba",
  "Goddess Bhadrakali",
  "Goddess Bhagavathi",
  "Goddess Bhagwati",
  "Goddess Dhumavati",
  "Goddess Durga Devi",
  "Goddess Durga Parameshwari",
  "Goddess Kamakshi",
  "Goddess Kameswari",
  "Goddess Kanaka Durga",
  "Goddess Lalita",
  "Goddess Mahishasura Mardini",
  "Goddess Manasa Devi",
  "Goddess Parashakti",
  "Goddess Parvathi Devi",
  "Goddess Renuka",
  "Goddess Rukmini",
  "Goddess Sarvamangala",
  "Goddess Shakti",
  "Goddess Shanta",
  "Goddess Shree Durga",
  "Goddess Shree Tara",
  "Goddess Sri Rajarajeshwari",
  "Goddess Sri Vidya",
  "Goddess Tripura",
  "Goddess Tripura Bhairavi",
  "Goddess Tripura Bhavani",
  "Goddess Tripura Devi",
  "Goddess Tripuramba",
  "Goddess Tripur Sundari",
  "Goddess Tulasi",
  "Goddess Uma Devi",
  "Goddess Vaishnavi",
  "Goddess Vaishno Devi",
  "Goddess Valli",
  "Goddess Vanadurga",
  "Goddess Vandevi",
  "Goddess Vindhyeshwari",
  "Goddess Vishalakshi",
  "Goddess Vishnumaya",
  "Goddess Yellamma",
  "Goddess Yellavva",
  "Goddess Yellavva",
  "Goddess Aditi",
  "Goddess Anasuya Devi",
  "Goddess Ambalika",
  "Goddess Anandamayi",
  "Goddess Aparajita",
  "Goddess Arya",
  "Goddess Arundhati",
  "Goddess Ashapurna",
  "Goddess Ashoka Sundari",
  "Goddess Ashtalakshmi",
  "Goddess Ashtamatrika",
  "Goddess Ashtanaga",
  "Goddess Ashtavinayaki",
  "Goddess Avantika",
  "Goddess Avvaiyar",
  "Goddess Bhadrakali Devi",
  "Goddess Bhadrakshi",
  "Goddess Bhagyavidhata",
  "Goddess Bhagyalakshmi",
  "Goddess Bhamati",
  "Goddess Bhargavi",
  "Goddess Bhavani Mata",
  "Goddess Bhuvaneshwari Devi",
  "Goddess Brahmani Devi",
  "Goddess Chandika Devi",
  "Goddess Dakshayani Devi",
  "Goddess Dandapani",
  "Goddess Devaki",
  "Goddess Dhanalakshmi Devi",
  "Goddess Dhaneshwari",
  "Goddess Dhumorna",
  "Goddess Durga Bhavani",
  "Goddess Durga Devi",
  "Goddess Durga Mata",
  "Goddess Durga Parameshwari",
  "Goddess Durga Shakthi",
  "Goddess Durga Shakti",
  "Goddess Durga Siddhi",
  "Goddess Durga Vandana",
  "Goddess Durga Vishnumaya",
  "Goddess Ekadasha Rudra",
  "Goddess Ela Devi",
  "Goddess Ellamma Devi",
  "Goddess Ennavaley",
  "Goddess Ganga Mata",
  "Goddess Gayathri",
  "Goddess Girija",
  "Goddess Gomathi Amman",
  "Goddess Gouri",
  "Goddess Gowri",
  "Goddess Gowrimma",
  "Goddess Grishma",
  "Goddess Gupta Kali",
  "Goddess Harini",
  "Goddess Harsiddhi",
  "Goddess Hemavathi",
  "Goddess Indumati",
  "Goddess Ishaani",
  "Goddess Jagadamba",
  "Goddess Jagadambika",
  "Goddess Jai",
  "Goddess Jambavathi",
  "Goddess Janani",
  "Goddess Janardana",
  "Goddess Janaki",
  "Goddess Jayanti",
  "Goddess Jyestha",
  "Goddess Jyothi",
  "Goddess Kadambari",
  "Goddess Kadru",
  "Goddess Kailash",
  "Goddess Kainkarya Pradayini",
  "Goddess Kakawarni",
  "Goddess Kamadhenu Devi",
  "Goddess Kamalakshi",
  "Goddess Kamalatmika",
  "Goddess Kamalika",
  "Goddess Kamalini",
  "Goddess Kamakhya",
  "Goddess Kameshwari Devi",
  "Goddess Kamini",
  "Goddess Kamya",
  "Goddess Kanan",
  "Goddess Kanak",
  "Goddess Kanak Durga",
  "Goddess Kanaka Durga Devi",
  "Goddess Kanakadhara Devi",
  "Goddess Kanakalatha",
  "Goddess Kanakambika",
  "Goddess Kanakavalli",
  "Goddess Kanakeshwari",
  "Goddess Kananbala",
  "Goddess Kanchan",
  "Goddess Kanchanmala",
  "Goddess Kanchi Kamakshi",
  "Goddess Kanchika",
  "Goddess Kanda Mata",
  "Goddess Kandalaya",
  "Goddess Kanyakumari",
  "Goddess Kapalini",
  "Goddess Karthiyayini",
  "Goddess Karthiyayini Devi",
  "Goddess Karumari Amman",
  "Goddess Karunamayi",
  "Goddess Karunya",
  "Goddess Karuppar",
  "Goddess Karuvaki",
  "Goddess Kashmira",
  "Goddess Kashyapi",
  "Goddess Kasturba",
  "Goddess Katyayani Devi",
  "Goddess Katyayani Mata",
  "Goddess Kavitha",
  "Goddess Kavita",
  "Goddess Kavya",
  "Goddess Keshini",
  "Goddess Keshori",
  "Goddess Ketaki",
  "Goddess Kethaki",
  "Goddess Ketki",
  "Goddess Ketu",
  "Goddess Khyati",
  "Goddess Kirti",
  "Goddess Kiran",
  "Goddess Kishori",
  "Goddess Kirtida",
  "Goddess Kokila",
  "Goddess Komal",
  "Goddess Koushiki",
  "Goddess Kratika",
  "Goddess Kripi",
  "Goddess Krishi",
  "Goddess Krishna",
  "Goddess Krishnaveni",
  "Goddess Kshama",
  "Goddess Kshipra",
  "Goddess Kshipra Devi",
  "Goddess Kshirasagar",
  "Goddess Kuber Devi",
  "Goddess Kumari",
  "Goddess Kumud",
  "Goddess Kumudini",
  "Goddess Kunda",
  "Goddess Kundalini",
  "Goddess Kundeshwari",
  "Goddess Kunjika",
  "Goddess Kurukulla",
  "Goddess Lakshmi Devi",
  "Goddess Lakshmi Mata",
  "Goddess Lalithambika",
  "Goddess Lalitha Devi",
  "Goddess Lalita Devi",
  "Goddess Lalita Parameshwari",
  "Goddess Laxmi Narayani",
  "Goddess Leela",
  "Goddess Leelavati",
  "Goddess Lila",
  "Goddess Lochana",
  "Goddess Lokeshwari",
  "Goddess Lopamudra",
  "Goddess Madanatraya",
  "Goddess Madhu",
  "Goddess Madhuri",
  "Goddess Madhurima",
  "Goddess Madhusudani",
  "Goddess Madina",
  "Goddess Madira",
  "Goddess Maha Bhagavati",
  "Goddess Maha Devi",
  "Goddess Maha Durga",
  "Goddess Maha Kali",
  "Goddess Maha Lakshmi",
  "Goddess Maha Maya",
  "Goddess Maha Parvati",
  "Goddess Maha Saraswati",
  "Goddess Maha Shakti",
  "Goddess Maha Tripura Sundari",
  "Goddess Mahadevi",
  "Goddess Mahakali Devi",
  "Goddess Mahakali Mata",
  "Goddess Mahalakshmi",
  "Goddess Mahamaya",
  "Goddess Mahasaraswati",
  "Goddess Mahashakti",
  "Goddess Mahashakthi",
  "Goddess Maheshwari",
  "Goddess Mahishasuramardini",
  "Goddess Mahishasura Mardini",
  "Goddess Malini",
  "Goddess Mallika",
  "Goddess Mallikarjuna",
  "Goddess Mangala",
  "Goddess Mangalambika",
  "Goddess Manikarnika",
  "Goddess Manjari",
  "Goddess Manju",
  "Goddess Manjusha",
  "Goddess Manoranjani",
  "Goddess Mantra",
  "Goddess Mantrini",
  "Goddess Medha",
  "Goddess Medini",
  "Goddess Meenakshi Devi",
  "Goddess Meenakshi Sundari",
  "Goddess Menaka",
  "Goddess Minal",
  "Goddess Mithila",
  "Goddess Mithra",
  "Goddess Mohana Sundari",
  "Goddess Mohini",
  "Goddess Mohini Devi",
  "Goddess Mookambika",
  "Goddess Mridula",
  "Goddess Mrinalini",
  "Goddess Mudrika",
  "Goddess Mukta",
  "Goddess Muktabai",
  "Goddess Mukteshwari",
  "Goddess Naga Devi",
  "Goddess Nagalakshmi",
  "Goddess Nagambika",
  "Goddess Nagaratna",
  "Goddess Nagashree",
  "Goddess Nagaveni",
  "Goddess Nalini",
  "Goddess Naman",
  "Goddess Namrata",
  "Goddess Nandini",
  "Goddess Narmada",
  "Goddess Narayani",
  "Goddess Navadurga",
  "Goddess Navajyothi",
  "Goddess Navanita",
  "Goddess Navarathri",
  "Goddess Naveena",
  "Goddess Neeva",
  "Goddess Neeladevi",
  "Goddess Neelam",
  "Goddess Neelima",
  "Goddess Neeta",
  "Goddess Neha",
  "Goddess Netra",
  "Goddess Nilambari",
  "Goddess Nilima",
  "Goddess Nirmala",
  "Goddess Nirmaya",
  "Goddess Nisarga",
  "Goddess Nitya",
  "Goddess Nitya Devi",
  "Goddess Nityanandini",
  "Goddess Nityasundari",
  "Goddess Ojaswini",
  "Goddess Omkareshwari",
  "Goddess Oshini",
  "Goddess Padma",
  "Goddess Padmaja",
  "Goddess Padmavathi",
  "Goddess Pallavi",
  "Goddess Padmini",
  "Goddess Panchami",
  "Goddess Panchavaktra",
  "Goddess Panchdevi",
  "Goddess Parajika",
  "Goddess Parashakti",
  "Goddess Parvati Devi",
  "Goddess Parvati Mata",
  "Goddess Parvathi Devi",
  "Goddess Parvathy",
  "Goddess Pavana",
  "Goddess Pavitra",
  "Goddess Pavithra",
  "Goddess Pavani",
  "Goddess Phoolan Devi",
  "Goddess Poonam",
  "Goddess Poornima",
  "Goddess Poorvaja",
  "Goddess Poorvashada",
  "Goddess Prabhavati",
  "Goddess Prachetasa",
  "Goddess Prakruti",
  "Goddess Pramila",
  "Goddess Prasanna",
  "Goddess Pratibha",
  "Goddess Pratima",
  "Goddess Pratishtha",
  "Goddess Preeti",
  "Goddess Prema",
  "Goddess Priti",
  "Goddess Priya",
  "Goddess Priyanka",
  "Goddess Pushpa",
  "Goddess Pushpalata",
  "Goddess Quirina",
  "Goddess Rachana",
  "Goddess Rachita",
  "Goddess Radha",
  "Goddess Radhika",
  "Goddess Radhika Devi",
  "Goddess Radhika Krishna",
  "Goddess Raghavi",
  "Goddess Raka",
  "Goddess Raksha",
  "Goddess Rama Devi",
  "Goddess Ramadevi",
  "Goddess Ramya",
  "Goddess Rani",
  "Goddess Ranjana",
  "Goddess Rati",
  "Goddess Ratna",
  "Goddess Rati Devi",
  "Goddess Ratnamala",
  "Goddess Ratnapriya",
  "Goddess Ratnavali",
  "Goddess Ravana",
  "Goddess Renuka",
  "Goddess Reshmi",
  "Goddess Riddhi",
  "Goddess Ridhi",
  "Goddess Rina",
  "Goddess Rishika",
  "Goddess Rishyasringa",
  "Goddess Rithika",
  "Goddess Ritika",
  "Goddess Ritu",
  "Goddess Rituparna",
  "Goddess Rohini",
  "Goddess Roopali",
  "Goddess Roopini",
  "Goddess Roshni",
  "Goddess Rucha",
  "Goddess Ruchi",
  "Goddess Ruchika",
  "Goddess Rukhmani",
  "Goddess Rupal",
  "Goddess Rupavati",
  "Goddess Rupeshwari",
  "Goddess Sabha",
  "Goddess Sabina",
  "Goddess Sachi",
  "Goddess Sachita",
  "Goddess Sadhana",
  "Goddess Sadhika",
  "Goddess Saffron",
  "Goddess Sagarika",
  "Goddess Saha",
  "Goddess Sahana",
  "Goddess Sahasra",
  "Goddess Sahasra Devi",
  "Goddess Sajala",
  "Goddess Sajili",
  "Goddess Sajni",
  "Goddess Sakhi",
  "Goddess Sakti",
  "Goddess Sambhavi",
  "Goddess Samhita",
  "Goddess Sampriti",
  "Goddess Samridhi",
  "Goddess Samyukta",
  "Goddess Sananda",
  "Goddess Sandhya",
  "Goddess Sangeeta",
  "Goddess Sanjana",
  "Goddess Sanjivani",
  "Goddess Sanjukta",
  "Goddess Sankriti",
  "Goddess Santoshi Devi",
  "Goddess Sanya",
  "Goddess Saphala",
  "Goddess Sarada",
  "Goddess Saraswati Devi",
  "Goddess Saraswati Mata",
  "Goddess Sarga",
  "Goddess Sarika",
  "Goddess Sarita",
  "Goddess Saroj",
  "Goddess Sarojini",
  "Goddess Sarvamangala",
  "Goddess Sarvani",
  "Goddess Sarvashri",
  "Goddess Sarveshwari",
  "Goddess Sarvottam",
  "Goddess Sati",
  "Goddess Satya",
  "Goddess Satyawati",
  "Goddess Satyavati",
  "Goddess Saudamini",
  "Goddess Sauvagya",
  "Goddess Savitri Devi",
  "Goddess Savya",
  "Goddess Shabari",
  "Goddess Shailaja",
  "Goddess Shailaputri",
  "Goddess Shakti",
  "Goddess Shambhavi",
  "Goddess Shankari",
  "Goddess Shanmukhi",
  "Goddess Shanta",
  "Goddess Shanti",
  "Goddess Sharadamba",
  "Goddess Sharada Devi",
  "Goddess Sharanya",
  "Goddess Sharmila",
  "Goddess Shashti",
  "Goddess Shashwati",
  "Goddess Shatakshi",
  "Goddess Shatavisha",
  "Goddess Shatayu",
  "Goddess Shatrunjaya",
  "Goddess Shatrupa",
  "Goddess Sheela",
  "Goddess Shefali",
  "Goddess Shejali",
  "Goddess Shila",
  "Goddess Shilpa",
  "Goddess Shiva",
  "Goddess Shivali",
  "Goddess Shivani",
  "Goddess Shobhana",
  "Goddess Shobhita",
  "Goddess Shradha",
  "Goddess Shreya",
  "Goddess Shreya Devi",
  "Goddess Shridevi",
  "Goddess Shristi",
  "Goddess Shuchi",
  "Goddess Shuchismita",
  "Goddess Shuddhi",
  "Goddess Shukla",
  "Goddess Shweta",
  "Goddess Siddhidatri",
  "Goddess Siddhi Devi",
  "Goddess Simran",
  "Goddess Sita",
  "Goddess Sita Devi",
  "Goddess Sitara",
  "Goddess Sitashri",
  "Goddess Sitawati",
  "Goddess Smrithi",
  "Goddess Smriti",
  "Goddess Sneha",
  "Goddess Sobha",
  "Goddess Sohani",
  "Goddess Sohini",
  "Goddess Soma",
  "Goddess Somasundari",
  "Goddess Sonali",
  "Goddess Sonam",
  "Goddess Sonia",
  "Goddess Soudamini",
  "Goddess Soumya",
  "Goddess Sowmya",
  "Goddess Srishti",
  "Goddess Sristi",
  "Goddess Srividya",
  "Goddess Stuti",
  "Goddess Sudha",
  "Goddess Sudiksha",
  "Goddess Sujata",
  "Goddess Sujaya",
  "Goddess Sujitha",
  "Goddess Sujyoti",
  "Goddess Sulekha",
  "Goddess Sumitra",
  "Goddess Sunaina",
  "Goddess Sunayana",
  "Goddess Sunita",
  "Goddess Suparna",
  "Goddess Supriya",
  "Goddess Surabhi",
  "Goddess Surya",
  "Goddess Sushila",
  "Goddess Sushma",
  "Goddess Sushmita",
  "Goddess Sushri",
  "Goddess Sushrut",
  "Goddess Sushruta",
  "Goddess Sushrutta",
  "Goddess Susmita",
  "Goddess Swadesh",
  "Goddess Swadhinta",
  "Goddess Swaha",
  "Goddess Swamini",
  "Goddess Swapna",
  "Goddess Swara",
  "Goddess Swaraj",
  "Goddess Swarupa",
  "Goddess Swasti",
  "Goddess Swathi",
  "Goddess Swati",
  "Goddess Sweta",
  "Goddess Tabassum",
  "Goddess Tahira",
  "Goddess Tania",
  "Goddess Tanisha",
  "Goddess Tanvi",
  "Goddess Tara",
  "Goddess Taraka",
  "Goddess Tarangini",
  "Goddess Tarika",
  "Goddess Tarini",
  "Goddess Tarulata",
  "Goddess Tavishi",
  "Goddess Tejal",
  "Goddess Trisha",
  "Goddess Tripti",
  "Goddess Trishna",
  "Goddess Triveni",
  "Goddess Tulasi",
  "Goddess Ujwala",
  "Goddess Uma",
  "Goddess Umadevi",
  "Goddess Urmila",
  "Goddess Urmi",
  "Goddess Urvasi",
  "Goddess Urvi",
  "Goddess Usha",
  "Goddess Ushas",
  "Goddess Uttara",
  "Goddess Vagdevi",
  "Goddess Vahini",
  "Goddess Vaidehi",
  "Goddess Vaisnavi",
  "Goddess Vaishali",
  "Goddess Vaishnavi",
  "Goddess Vaishno Devi",
  "Goddess Vajra",
  "Goddess Vajreshwari",
  "Goddess Valsa",
  "Goddess Vanaja",
  "Goddess Vanamala",
  "Goddess Vanara",
  "Goddess Vandana",
  "Goddess Vani",
  "Goddess Varada",
  "Goddess Varalakshmi",
  "Goddess Varuna",
  "Goddess Varuni",
  "Goddess Varsha",
  "Goddess Varshini",
  "Goddess Vasantasri",
  "Goddess Vasanta Devi",
  "Goddess Vasavi",
  "Goddess Vasudha",
  "Goddess Vasudhara",
  "Goddess Vasuki",
  "Goddess Vasumati",
  "Goddess Vasundhara",
  "Goddess Vasundhra",
  "Goddess Vayuna",
  "Goddess Veena",
  "Goddess Veeramani",
  "Goddess Veeravati",
  "Goddess Vibha",
  "Goddess Vibhavari",
  "Goddess Vibhuti",
  "Goddess Vidhi",
  "Goddess Vidya",
  "Goddess Vijaya",
  "Goddess Vijayalakshmi",
  "Goddess Vijayanti",
  "Goddess Vikruti",
  "Goddess Vilasini",
  "Goddess Vilina",
  "Goddess Vimala",
  "Goddess Vinata",
  "Goddess Vinayaki",
  "Goddess Vinaya",
  "Goddess Vineeta",
  "Goddess Vineetha",
  "Goddess Vinutha",
  "Goddess Vinuthna",
  "Goddess Vishakha",
  "Goddess Vishalakshi",
  "Goddess Vishnu Maya",
  "Goddess Vishnu Priya",
  "Goddess Vishruthi",
  "Goddess Vishvaja",
  "Goddess Vishvamukhi",
  "Goddess Vishvapriya",
  "Goddess Vishwambhara",
  "Goddess Vishwamitra",
  "Goddess Vishweshwari",
  "Goddess Visita",
  "Goddess Vrinda",
  "Goddess Vritika",
  "Goddess Vritti",
  "Goddess Vyoma",
  "Goddess Vyomini",
  "Goddess Yachana",
  "Goddess Yajna",
  "Goddess Yamuna",
  "Goddess Yashawini",
  "Goddess Yashila",
  "Goddess Yashoda",
  "Goddess Yashodhara",
  "Goddess Yasmin",
  "Goddess Yogini",
  "Goddess Yukta",
  "Goddess Yuthika",
  "Goddess Zara"
]