export default ["A landscape with mountains and a lake",
  "A city skyline at night",
  "A sunset over a beach",
  "A forest with a river running through it",
  "A snowy mountain peak",
  "An underwater scene with coral and fish",
  "A space scene with planets and stars",
  "A futuristic cityscape",
  "A desert with a cactus",
  "A field of flowers",
  "A farm with cows and a barn",
  "A jungle with a waterfall",
  "A volcano erupting",
  "A castle on a hill",
  "A lighthouse by the sea",
  "A street in a small town",
  "A garden with a pond",
  "A modern office building",
  "A bridge over a river",
  "A haunted house",
  "A medieval village",
  "A beach with palm trees",
  "A train traveling through a forest",
  "A futuristic spaceship",
  "A group of hot air balloons",
  "A carnival with rides and games",
  "A concert with a stage and crowd",
  "A theater with a stage and audience",
  "A busy airport",
  "A luxury yacht in the ocean",
  "A snowy cabin in the woods",
  "A row of colorful houses",
  "A skyscraper at sunset",
  "A lake with a dock and boat",
  "A snowy city street",
  "A group of people hiking in the mountains",
  "A tropical island with a waterfall",
  "A castle in the clouds",
  "A circus with performers and animals",
  "A futuristic robot",
  "A vintage car on a city street",
  "A spacecraft traveling through a wormhole",
  "A maze with a person trying to find their way out",
  "A person walking through a forest with glowing mushrooms",
  "A waterfall with a rainbow",
  "A city street in the rain",
  "A person sitting on a bench in a park",
  "A beach with a pier and boats",
  "A group of people rock climbing",
  "A city street with a bicycle lane",
  "A sunset over a city skyline",
  "A person looking out at the stars",
  "A person snowboarding down a mountain",
  "A person surfing a wave",
  "A group of people playing soccer on a field",
  "A person swimming in a pool",
  "A person kayaking down a river",
  "A group of people on a rollercoaster",
  "A person riding a horse through a meadow",
  "A person skiing down a mountain",
  "A person scuba diving in the ocean",
  "A person bungee jumping off a bridge",
  "A person hang gliding through the sky",
  "A person parachuting out of a plane",
  "A person skydiving from a helicopter",
  "A person base jumping from a cliff",
  "A person zip lining through a forest",
  "A person white water rafting down a river",
  "A person rock climbing a cliff",
  "A person hiking up a mountain",
  "A person camping in a forest",
  "A person fishing on a lake",
  "A person hunting in a field",
  "A person playing golf on a course",
  "A person playing tennis on a court",
  "A person playing basketball on a court",
  "A person playing baseball on a field",
  "A person playing football on a field",
  "A person playing volleyball on a beach",
  "A person playing soccer on a beach"]