export default [
    "Aerospace",
    "Automotive",
    "Banking",
    "Biotechnology",
    "Chemical",
    "Construction",
    "Consulting",
    "Consumer Electronics",
    "Defense",
    "Education",
    "Energy",
    "Entertainment",
    "Fashion",
    "Finance",
    "Food and Beverage",
    "Gaming",
    "Healthcare",
    "Hospitality",
    "Information Technology",
    "Insurance",
    "Internet",
    "Legal",
    "Logistics",
    "Manufacturing",
    "Media",
    "Mining",
    "Music",
    "Oil and Gas",
    "Pharmaceutical",
    "Real Estate",
    "Retail",
    "Sports",
    "Telecommunications",
    "Transportation",
    "Travel",
    "Utilities",
    "Advertising",
    "Agriculture",
    "Architecture",
    "Art",
    "Automobile",
    "Aviation",
    "Beauty",
    "Beverage",
    "Broadcasting",
    "Catering",
    "Chemistry",
    "Communications",
    "Computer",
    "Cosmetics",
    "Design",
    "Electronics",
    "Engineering",
    "Fashion Design",
    "Film",
    "Fitness",
    "Furniture",
    "Gaming",
    "Health",
    "Home Appliances",
    "Hospital",
    "Information",
    "Investment",
    "Jewelry",
    "Lifestyle",
    "Machinery",
    "Management",
    "Marketing",
    "Medical",
    "Metallurgy",
    "Mobile",
    "Packaging",
    "Petroleum",
    "Photography",
    "Plastics",
    "Printing",
    "Public Relations",
    "Publishing",
    "Railway",
    "Real Estate",
    "Research",
    "Restaurant",
    "Security",
    "Software",
    "Steel",
    "Textile",
    "Tourism",
    "Toys",
    "Training",
    "Waste Management",
    "Web Design",
    "Wholesale",
    "Wireless",
    "Woodworking",
    "Writing",
        "Accounting",
    "Airline",
    "Architecture",
    "Astrology",
    "Automation",
    "Biochemistry",
    "Blockchain",
    "Cinema",
    "Circus",
    "Comedy",
    "Cybersecurity",
    "Dentistry",
    "E-commerce",
    "Ecology",
    "Event Planning",
    "Fashion Retail",
    "Fine Arts",
    "Forestry",
    "Futurism",
    "Gambling",
    "Genealogy",
    "Genetics",
    "Geology",
    "Green Energy",
    "Human Resources",
    "Import/Export",
    "Interior Design",
    "Investment Banking",
    "Landscape Architecture",
    "Language Services",
    "Law Enforcement",
    "Maritime",
    "Meteorology",
    "Neuroscience",
    "Nonprofit",
    "Nursing",
    "Oceanography",
    "Outdoor Recreation",
    "Paralegal Services",
    "Performing Arts",
    "Pharmacology",
    "Philosophy",
    "Photovoltaics",
    "Podcasting",
    "Political Consulting",
    "Psychiatry",
    "Public Speaking",
    "Renewable Energy",
    "Robotics",
    "Sales",
    "Sculpture",
    "Social Media",
    "Space Exploration",
    "Sports Management",
    "Sustainability",
    "Tax Services",
    "Technology",
    "Urban Planning",
    "Venture Capital",
    "Virtual Reality",
    "Volunteerism",
    "Wine Industry",
    "Yoga",
    "Zoology",
    "3D Printing",
    "Agribusiness",
    "Alternative Energy",
    "Animation",
    "Artificial Intelligence",
    "Automated Vehicles",
    "Big Data",
    "Bioinformatics",
    "Clean Technology",
    "Cloud Computing",
    "Data Science",
    "Digital Marketing",
    "Drone Technology",
    "E-learning",
    "Environmental Science",
    "Food Processing",
    "Genetic Engineering",
    "Golf",
    "Horticulture",
    "Hydroponics",
    "Industrial Design",
    "Influencer Marketing",
    "Internet of Things (IoT)",
    "Machine Learning",
    "Nanotechnology",
    "Online Gaming",
    "Personal Development",
    "Quantum Computing",
    "Remote Sensing",
    "Renovation",
    "Smart Home",
    "Space Tourism",
    "Virtual Assistant",
    "Wearable Technology"
]
