export default ["Aikido",
  "Arnis",
  "Baguazhang",
  "Bajiquan",
  "Bando",
  "Bartitsu",
  "Battōjutsu",
  "Bōjutsu",
  "Boxing",
  "Brazilian Jiu-Jitsu",
  "Bujinkan",
  "Capoeira",
  "Changquan",
  "Choi Kwang-Do",
  "Choy Lay Fut",
  "Combat Hopak",
  "Crane Style Kung Fu",
  "Crav Maga",
  "Cuong Nhu",
  "Dambe",
  "Danzan Ryu Jujitsu",
  "Daito-ryu Aiki-jujutsu",
  "Dragon Kung Fu",
  "Eagle Claw",
  "Eskrima",
  "Fencing",
  "Filipino Kali",
  "Gatka",
  "Gendai Goshin Jutsu",
  "Glima",
  "Gōjū-ryū",
  "Gong Kwon Yu Sul",
  "Gouren",
  "Greco-Roman Wrestling",
  "Haidong Gumdo",
  "Hakko Ryu",
  "Hapkido",
  "Hard Qigong",
  "Hwa Rang Do",
  "Iaido",
  "Isshin-ryū",
  "Jeet Kune Do",
  "Jiujitsu",
  "Judo",
  "Jujutsu",
  "Kajukenbo",
  "Karate",
  "Kendo",
  "Kenjutsu",
  "Khapkido",
  "Kickboxing",
  "Kobudo",
  "Krav Maga",
  "Kuk Sool Won",
  "Kurash",
  "Kyokushin",
  "Lathi Khela",
  "Lethwei",
  "Lucha Libre",
  "Malla-yuddha",
  "Martial Arts Tricking",
  "Mixed Martial Arts (MMA)",
  "Monkey Kung Fu",
  "Muay Boran",
  "Muay Thai",
  "Naginatajutsu",
  "Ninjutsu",
  "Nippon Kempo",
  "Pakua Chang",
  "Pankration",
  "Pencak Silat",
  "Penkat Silat Bukti Negara",
  "Pentjak Silat",
  "Pentjak Silat Serak",
  "Pradal Serey",
  "Sambo",
  "San Soo",
  "Savate",
  "Shaolin Kung Fu",
  "Shindo Muso Ryu",
  "Shinkendo",
  "Shintaido",
  "Shootfighting",
  "Shooto",
  "Shorinji Kempo",
  "Shuai Jiao",
  "Silat",
  "Ssireum",
  "Sumo",
  "Systema",
  "Taekkyon",
  "Taekwondo",
  "Tai Chi",
  "Taiho Jutsu",
  "Taido",
  "Takewondo",
  "Tang Soo Do",
  "Tantojutsu",
  "Tatsumi Ryu",
  "Tenjin Shinyo-ryu Jujutsu",
  "Thai Boxing",
  "Thang-ta",
  "Vale Tudo"];