export default [
  "Soft Overhead Lighting",
  "High-Key Lighting",
  "Low-Key Lighting",
  "Naturalistic Daylight",
  "Artificial Moonlight",
  "Silhouette Lighting",
  "Backlighting",
  "Harsh Shadows",
  "Flat Lighting",
  "Chiaroscuro Lighting",
  "Split Lighting",
  "Rim Lighting",
  "Sidelighting",
  "Three-Point Lighting",
  "Two-Point Lighting",
  "Single-Point Lighting",
  "Practical Light Source",
  "Motivated Lighting",
  "Unmotivated Lighting",
  "Fill Light",
  "Key Light",
  "Hair Light",
  "Edge Light",
  "Footlight",
  "Catch Light",
  "Diffused Lighting",
  "Focused Spot",
  "Broad Lighting",
  "Narrow Lighting",
  "Frontal Lighting",
  "Up Lighting",
  "Down Lighting",
  "Cross Lighting",
  "Top Lighting",
  "Bounced Light",
  "Direct Sunlight",
  "Hard Light",
  "Soft Light",
  "Ambient Light",
  "Texture Light",
  "Dappled Sunlight",
  "Contrast Lighting",
  "Shadowless Lighting",
  "Shadow Play",
  "High Contrast",
  "Low Contrast",
  "Mood Lighting",
  "Accent Lighting",
  "High-Speed Lighting",
  "Dynamic Lighting",
  "Static Lighting",
  "Directional Light",
  "Omni-Directional Light",
  "Background Light",
  "Foreground Light",
  "Available Light",
  "Tungsten Lighting",
  "LED Lighting",
  "Fluorescent Lighting",
  "Natural Backlight",
  "Artificial Backlight",
  "Overcast Sky",
  "Golden Hour Glow",
  "Magic Hour Ambiance",
  "Day for Night",
  "Dramatic Lighting",
  "Cold Lighting",
  "Warm Lighting",
  "Filtered Light",
  "Stylized Lighting",
  "Underexposed",
  "Overexposed",
  "Neutral Exposure",
  "Book Light",
  "China Ball",
  "Ring Light",
  "Beauty Light",
  "Butterfly Lighting",
  "Clamshell Lighting",
  "Rembrandt Lighting",
  "Loop Lighting",
  "Paramount Lighting",
  "Spotlight",
  "Floodlight",
  "Cucoloris Effect",
  "Gobo Patterns",
  "Disco Lighting",
  "Stage Lighting",
  "Mixed Color Temperature",
  "Monochromatic",
  "Dual Tone",
  "Complementary Colors",
  "Anamorphic Flare",
  "Lens Flare",
  "Candlelight",
  "Firelight",
  "Urban Glow",
  "Neon Light",
  "Blacklight",
  "Police Siren Effect",
  "Strobe Light",
  "Flashlight Beam",
  "Headlight Glow"
]
