export default [
'black background', 
'swirl background', 
'dreamy forest', 
'ancient egypt', 
'ancient mesopotamia', 
'ancient rome', 
'ancient china', 
'ancient india', 
'stormy night', 
'blustery cold winter', 
'dark paint splatters', 
'dark pattern', 
'geometric pattern', 
'clean lines', 
'at night', 
'christmas',
'jerusalem',
'ancient japan',
'siberia',
'underground',
'on mars',
'out in the middle of the woods',
"mt. rushmore",
'on the moon',
'5th dimension',
'back of police car',
'insane asylum',
'burger joint',
'parking lot',
'trampoline',
'portapody',
'stage',
'banquet hall',
"inside the great brain",
"valhalla",
"a turtle's dream",
"rock concert",
"planet of the apes",
"their own birth",
"their own death",
'hawaii',
'aspen colorado',
'spooky forest', 
'barren wasteland',
"Paris, France", 
"New York City, USA", 
"Tokyo, Japan", 
"Sydney, Australia", 
"London, England", 
"Rio de Janeiro, Brazil", 
"Cape Town, South Africa", 
"Bali, Indonesia", 
"Dubai, United Arab Emirates", 
"Vancouver, Canada", 
"Moscow, Russia", 
"Reykjavik, Iceland", 
"Bangkok, Thailand", 
"Marrakech, Morocco", 
"Buenos Aires, Argentina", 
"Amsterdam, Netherlands", 
"Barcelona, Spain", 
"Rome, Italy", 
"Beijing, China", 
"Maui, Hawaii, USA", 
"Santorini, Greece", 
"Toronto, Canada", 
"Stockholm, Sweden", 
"Prague, Czech Republic", 
"Vienna, Austria",
"Wilderness or national parks without a map or compass", 
"Inner city areas known for high crime rates", 
"Abandoned or remote industrial areas", 
"Sewers or underground tunnels", 
"Areas with hazardous materials or radiation exposure", 
"Dense forests or jungle areas without a guide", 
"Desert or arid regions without adequate water supply", 
"High-altitude mountain areas without proper gear or experience", 
"Areas with active landmines or unexploded ordnance", 
"War zones or conflict areas"]