export default [
'illustrated', 
'painted', 
'drawn', 
'illustrated', 
'ink blots', 
'carved',
'etched',
'cut and sewn',
'blocked out',
'fine-art painted',
'digitally composed',
'rendered',
'minimal',
'clean lines',
'outlined',
'tie-dyed',
'Night Photography',
'street photography',
'map pencils',
'pattern',
'shaded',
'oblique projection',
'spray painted',
'diagrammed',
'glass blown',
'block printed',
'dot matrix',
'cross-hatched',
'burned',
'woodblock printed',
'printed',
'burnished',
'metalcut',
'duotone',
'free-hand brushed',
'low-poly',
'photorealistic', 
'photocopied',
'Dalle de verre',
'drybrushed',
'drip painted',
'realism',
'dye-sublimination',
'oragami', 
'sculpted',
'calligraphy',
'inked',
'graffitti', 
'computer generated', 
'cartoonish',
'graphical art',
'3d model', 
'sketched', 
'illustrated', 
'oil painting', 
'black and white pencils', 
'grease pens', 
'watercolors', 
'illustrated in dark inks',
"Generative art software", 
"ASCII art", 
"Augmented Reality", 
"Virtual Reality", 
"Projection Mapping", 
"Interactive installations", 
"Digital Painting", 
"Data Visualization", 
"Algorithmic art", 
"3D Printing", 
"Glitch Art", 
"Holography", 
"Kinetic sculpture", 
"LED Art", 
"Laser art", 
"Light installations", 
"Liquid Light Shows", 
"Magnetic Resonance Imaging (MRI)", 
"Neuroaesthetics", 
"Neurofeedback art", 
"Optical Illusions", 
"Organic Motion", 
"Pixel art", 
"Quantum Art", 
"Robotic art", 
"Sound Art", 
"Steganography", 
"Textile art using electronics", 
"Wearable technology art", 
"Motion graphics", 
"Typography", 
"Video installations", 
"Virtual fashion", 
"360-degree photography", 
"Acoustic art", 
"Aerial photography", 
"Bioluminescence art", 
"Biofeedback art", 
"Brain-computer interfaces", 
"Brainwave art", 
"Computer vision art", 
"Cybernetic art", 
"Data sonification", 
"Digital embroidery", 
"Digital murals", 
"Digital sculptures", 
"Drone art", 
"E-textiles", 
"Electric field visualizations", 
"Electro-luminescent art", 
"Electromagnetic imaging", 
"Electrophysiology art", 
"Environmental art", 
"Fluid dynamics art", 
"Fractal art", 
"Geometric abstraction", 
"Geotagging art", 
"Glitch sculpture", 
"Gravity painting", 
"Heat signature photography", 
"Hyperrealism", 
"Infographic art", 
"Infrared photography", 
"Magnetic fields imaging", 
"Mapping projections on nature", 
"Metaphysical art", 
"Microscopy art", 
"Mind-mapping art", 
"MRI spectroscopy", 
"Music visualization", 
"Nanoart", 
"Non-photorealistic rendering", 
"Optical fiber art", 
"Particle physics art", 
"Photography using expired film", 
"Pinhole photography", 
"Psychedelic art", 
"Radio art", 
"Real-time processing", 
"Resonance imaging", 
"Satellite imagery art", 
"Science fiction art", 
"Security holograms", 
"Smoke painting", 
"Sonic art", 
"Stereographic projections", 
"Structural coloration art", 
"Sunography", 
"Superimposition art", 
"Synthetic biology art", 
"Tactile art", 
"Thermal imaging", 
"Time-lapse photography", 
"Time-stretching video", 
"Transcranial magnetic stimulation art", 
"Transparent LCD screens", 
"Ultraviolet photography", 
"Unconventional printing", 
"Video mapping", 
"X-ray imaging",
  "Acrylic paint",
  "Airbrush",
  "Alcohol ink",
  "Assemblage",
  "Bamboo",
  "Beadwork",
  "Bronze",
  "Calligraphy",
  "Candle-making",
  "Ceramics",
  "Chalk",
  "Charcoal",
  "Collage",
  "Concrete",
  "Crochet",
  "Decoupage",
  "Digital art",
  "Diorama",
  "Drawing",
  "Encaustic",
  "Engraving",
  "Etching",
  "Fabric",
  "Fiber",
  "Flameworking",
  "Found objects",
  "Fresco",
  "Furniture",
  "Glass",
  "Gold leaf",
  "Gouache",
  "Graphic design",
  "Graffiti",
  "Illustration",
  "Ink",
  "Installation art",
  "Jewelry",
  "Knitting",
  "Lace",
  "Leather",
  "Lino print",
  "Manga",
  "Marble",
  "Metal",
  "Mixed media",
  "Mosaic",
  "Murals",
  "Oil paint",
  "Origami",
  "Painting",
  "Papercraft",
  "Pastel",
  "Pencil",
  "Photography",
  "Plaster",
  "Polymer clay",
  "Pottery",
  "Printmaking",
  "Quilting",
  "Resin",
  "Sculpture",
  "Silk",
  "Silverpoint",
  "Sketching",
  "Soap-making",
  "Spray paint",
  "Stencil",
  "Stitching",
  "Stone",
  "String art",
  "Sumi-e",
  "Tapestry",
  "Taxidermy",
  "Tempera",
  "Textile",
  "Tie-dye",
  "Tole painting",
  "Watercolor",
  "Weaving",
  "Wood",
  "Woodblock printing",
  "Woodcarving",
  "Yarn bombing",
  "Zentangle",
  "3D printing",
  "Augmented reality",
  "Virtual reality",
  "Generative art",
  "Projection mapping",
  "Interactive installations",
  "Holography",
  "Kinetic sculpture",
  "LED art",
  "Liquid light shows",
  "Magnetic resonance imaging",
  "Neurofeedback art",
  "Pixel art",
  "Quantum art",
  "Sound art",
  "Steganography",
  "Video installations",
  "Wearable technology art",
  "Fractal art",
  "Infrared photography",
  "Optical fiber art",
  "Smoke painting",
  "Transparent LCD screens",
  "Ultraviolet photography",
  "Unconventional printing"]