export default ["Generalized Anxiety Disorder",
"Major Depressive Disorder",
"Bipolar Disorder",
"Obsessive-Compulsive Disorder",
"Post-Traumatic Stress Disorder",
"Social Anxiety Disorder",
"Panic Disorder",
"Borderline Personality Disorder",
"Schizophrenia",
"Eating Disorders",
"Attention Deficit Hyperactivity Disorder",
"Autism Spectrum Disorder",
"Dissociative Identity Disorder",
"Narcissistic Personality Disorder",
"Antisocial Personality Disorder",
"Avoidant Personality Disorder",
"Dependent Personality Disorder",
"Histrionic Personality Disorder",
"Schizotypal Personality Disorder",
"Anorexia Nervosa",
"Bulimia Nervosa",
"Binge-Eating Disorder",
"Insomnia Disorder",
"Hypersomnia Disorder",
"Narcolepsy",
"Sleep Apnea",
"Restless Legs Syndrome",
"Substance Use Disorders",
"Alcohol Use Disorder",
"Cocaine Use Disorder",
"Opioid Use Disorder",
"Gambling Disorder",
"Internet Gaming Disorder",
"Compulsive Buying Disorder",
"Compulsive Hoarding",
"Trichotillomania",
"Body Dysmorphic Disorder",
"Gender Dysphoria",
"Transvestic Fetishism",
"Voyeuristic Disorder",
"Exhibitionistic Disorder",
"Sexual Masochism Disorder",
"Sexual Sadism Disorder",
"Frotteuristic Disorder",
"Kleptomania",
"Pyromania",
"Tourette's Disorder",
"Persistent Depressive Disorder",
"Premenstrual Dysphoric Disorder",
"Disruptive Mood Dysregulation Disorder",
"Schizoaffective Disorder",
"Delusional Disorder",
"Brief Psychotic Disorder",
"Shared Psychotic Disorder",
"Substance/Medication-Induced Psychotic Disorder",
"Psychotic Disorder Due to Another Medical Condition",
"Factitious Disorder",
"Malingering",
"Conversion Disorder",
"Somatic Symptom Disorder",
"Illness Anxiety Disorder",
"Body-Focused Repetitive Behavior Disorders",
"Non-Suicidal Self-Injury",
"Dyslexia",
"Dyscalculia",
"Dysgraphia",
"Developmental Coordination Disorder",
"Attention Deficit Disorder",
"Oppositional Defiant Disorder",
"Conduct Disorder",
"Intermittent Explosive Disorder",
"Personality Disorders Not Otherwise Specified",
"Agoraphobia",
"Specific Phobia",
"Body Integrity Identity Disorder",
"Insomnia Due to Mental Disorder",
"Hypersomnolence Due to Mental Disorder",
"Circadian Rhythm Sleep-Wake Disorders",
"Non-Rapid Eye Movement Sleep Arousal Disorder",
"Nightmare Disorder",
"Adjustment Disorders",
"Factitious Disorder Imposed on Another",
"Depressive Disorder Due to Another Medical Condition",
"Anxiety Disorder Due to Another Medical Condition",
"Obsessive-Compulsive and Related Disorders Due to Another Medical Condition",
"Trauma- and Stressor-Related Disorders Due to Another Medical Condition",
"Feeding and Eating Disorders Due to Another Medical Condition",
"Elimination Disorders Due to Another Medical Condition",
"Sleep-Wake Disorders Due to Another Medical",
"Hallucinations", 
"Paranoia", 
"Delusions", 
"Night terrors", 
"Sleep paralysis", 
"Anxiety", 
"Fear", 
"Madness", 
"Schizophrenia", 
"Psychosis", 
"Trauma", 
"Horror", 
"Insomnia", 
"Confusion", 
"Panic", 
"Depression", 
"Obsessions", 
"Compulsions", 
"Flashbacks", 
"Nightmares", 
"Voices", 
"Blackouts", 
"Frightening thoughts", 
"Phobias", 
"Schizoaffective disorder", 
"Borderline personality disorder", 
"Bipolar disorder", 
"Dissociative disorders", 
"Personality disorders", 
"Antisocial behavior", 
"Psychopathy", 
"Dissociation", 
"Disorientation", 
"Paradoxical sleep", 
"REM sleep", 
"Lucid dreaming", 
"Abnormal sleep patterns", 
"Despair", 
"Hopelessness", 
"Anguish", 
"Numbness", 
"Panic attacks", 
"Agoraphobia", 
"Claustrophobia", 
"Trapped", 
"Suffocation", 
"Night sweats", 
"Cold sweat", 
"Palpitations", 
"Hyperventilation", 
"Insanity", 
"Madness", 
"Hysteria", 
"Schizotypal", 
"Mania", 
"Psychotic breaks", 
"Paranoia", 
"Alienation", 
"Isolation", 
"Self-destructive behavior", 
"Suicidal ideation", 
"Delirium", 
"Catatonia", 
"Uncontrollable rage", 
"Hallucinations", 
"Visual disturbances", 
"Auditory disturbances", 
"Memory lapses", 
"Amnesia", 
"Nightmares", 
"Terrifying thoughts", 
"Derealization", 
"Depersonalization", 
"Disorganized thinking", 
"Disordered perception", 
"Insanity", 
"Schizophrenic tendencies", 
"Chronic insomnia", 
"Sleep deprivation", 
"Hypnagogic hallucinations", 
"Sleepwalking", 
"Rapid heart rate", 
"High blood pressure", 
"Gastrointestinal distress", 
"Panic disorder", 
"Claustrophobia", 
"Agoraphobia", 
"Obsessive-compulsive disorder", 
"Social anxiety disorder", 
"Post-traumatic stress disorder", 
"Generalized anxiety disorder", 
"Dissociative identity disorder", 
"Borderline personality disorder", 
"Depersonalization disorder", 
"Dissociative amnesia", 
"Neurosis", 
"Psychosomatic disorder", 
"Psychomotor agitation", 
"Cognitive distortion"]