export default ["0010x0010", 
"1476", 
"156", 
"Θ (Theta)", 
"Abruptum", 
"Abu Lahab", 
"Adonxs", 
"AeTopus", 
"Agalloch", 
"Alchemy of the 20th Century", 
"Giulio Aldinucci", 
"Alio Die", 
"Allerseelen", 
"All Hail the Transcending Ghost", 
"Altar of Plagues", 
"Alva Noto", 
"Ambeon", 
"Amber Asylum", 
"Anastasia", 
"Kristian Eidnes Andersen", 
"Martin Stig Andersen", 
"Peter Andersson", 
"Anenzephalia", 
"The Anti-Group", 
"Antimatter", 
"Aphex Twin", 
"Apollon", 
"Arcana", 
"Arditi", 
"Art Zoyd", 
"Ascension of the Watchers", 
"Asche", 
"Asriel", 
"Astral Social Club", 
"Freya Aswynn", 
"Ataraxia", 
"aTelecine", 
"Atrax Morgue", 
"Atrium Carceri", 
"Attrition", 
"Aube", 
"Audra", 
"Austere", 
"Autopsia", 
"Autumn Tears", 
"Daniel Avery", 
"The Axis of Perdition", 
"Nigel Ayers", 
"Christoph de Babalon", 
"Angelo Badalamenti", 
"Bad Sector", 
"Kelly Bailey", 
"Aidan Baker", 
"Annie Anxiety Bandez", 
"Barathrum", 
"Blixa Bargeld", 
"Bark Psychosis", 
"Barn Owl", 
"Geoff Barrow", 
"William Basinski", 
"Bass Communion", 
"Bastard Noise", 
"Tyler Bates", 
"Destini Beard", 
"Beatsystem", 
"Bobby Beausoleil", 
"Beequeen", 
"Michael Begg", 
"Beherit", 
"Bell Witch", 
"Belong", 
"John Bergin", 
"Eraldo Bernocchi", 
"Harry Bertoia", 
"Maurizio Bianchi", 
"Big City Orchestra", 
"Billain", 
"Biosphere", 
"Birchville Cat Motel", 
"Richie Birkenhead", 
"Joseph Bishara", 
"Raoul Björkenheim", 
"Black Dice", 
"The Black Dog", 
"Blackhouse", 
"Black Leather Jesus", 
"Black Rain", 
"Black Tape for a Blue Girl", 
"Blam Honey", 
"Blood Axis", 
"Blood Incantation", 
"Bloodyminded", 
"Blut Aus Nord", 
"Der Blutharsch", 
"The Body", 
"The Body Lovers / The Body Haters", 
"Bohren & der Club of Gore", 
"Boris", 
"Ben Lukas Boysen", 
"Brighter Death Now", 
"Eric Brosius", 
"Browning Mummery", 
"Harold Budd", 
"Bull of Heaven", 
"Burial", 
"Burial Chamber Trio", 
"Carter Burwell", 
"Burzum", 
"Cabaret Voltaire", 
"Ethel Cain", 
"Marc Canham", 
"Carbon Based Lifeforms", 
"The Caretaker", 
"John Carpenter", 
"Kim Cascone", 
"Stijn Van Cauter", 
"Nick Cave", 
"Celer", 
"A Challenge of Honour", 
"Chandeen", 
"Richard Chartier", 
"Ben Chatwin", 
"Cheerleader 69", 
"Chthonic Force", 
"Cindytalk", 
"Cisfinitum", 
"Cities Last Broadcast", 
"Clan Balache", 
"Clark", 
"Climax Golden Twins", 
"Clock DVA", 
"Charlie Clouser", 
"Cocteau Twins", 
"Coil", 
"Faith Coloccia", 
"Continuum", 
"Controlled Bleeding", 
"Controlled Death", 
"Coph Nia", 
"Corrupted", 
"Alessandro Cortini", 
"Council of Nine", 
"Clayton Counts", 
"Cousin Silas", 
"Covenant", 
"CTI", 
"Cultus Sabbati", 
"Current 93", 
"Cyclobe", 
"Dälek", 
"Dargaard", 
"Dark Sanctuary", 
"Darkspace", 
"David Darling", 
"Sarah Davachi", 
"Dead Can Dance", 
"Dead Voices on Air", 
"Death Ambient", 
"Death Cube K", 
"Death in June", 
"Deathprod", 
"Decree", 
"Delerium", 
"Deleyaman", 
"Demdike Stare", 
"Gitane DeMone", 
"Dernière Volonté", 
"Desiderii Marginis", 
"Deutsch Nepal", 
"Disasterpeace", 
"Disembowelment", 
"Displacer", 
"Djam Karet", 
"Dolorian", 
"Donis", 
"Dragged into Sunlight", 
"dreamSTATE", 
"Kevin Drumm", 
"John Duncan", 
"Earth", 
"Einstürzende Neubauten", 
"Eleh", 
"Elend", 
"Matt Elliott", 
"Warren Ellis", 
"Eluvium", 
"Alec Empire", 
"Endura", 
"Lawrence English", 
"Enigma", 
"Brian Eno", 
"Equimanthorn", 
"Tommie Eriksson", 
"Esoteric", 
"Evoken", 
"Experimental Audio Research (E.A.R.)", 
"Expo '70", 
"Yamantaka Eye", 
"Faith and the Muse", 
"Falling You", 
"Florian-Ayala Fauna", 
"Joel Fausto", 
"Jeffrey Fayman", 
"Cedrik Fermont", 
"Dominick Fernow", 
"Fever Ray", 
"Final", 
"Robin Finck", 
"Finite Automata", 
"Fluxion", 
"Le Forbici di Manitù", 
"Michael W. Ford", 
"Die Form", 
"Robert Fripp", 
"Peter Frohmader", 
"Front Line Assembly", 
"Ben Frost", 
"Jun Fukamachi", 
"The Future Sound of London", 
"Runhild Gammelsæter", 
"Roopam Garg", 
"Gas", 
"Gazelle Twin", 
"GéNIA", 
"The Gerogerigegege", 
"Lisa Gerrard", 
"Scott Gibbons", 
"Bruce Gilbert", 
"Gnaw Their Tongues", 
"Godspeed You! Black Emperor", 
"Mick Gordon", 
"Mathias Grassow", 
"Gravehill Paris Witch", 
"Graveland", 
"Jason Graves", 
"Martin Grech", 
"Michael Gregor", 
"Randy Greif", 
"Jeff Greinke", 
"Hildur Guðnadóttir", 
"The Hafler Trio", 
"Haiku Funeral", 
"Halo Manash", 
"James Hannigan", 
"Kurt Harland", 
"Mick Harris", 
"Paul Haslinger", 
"Hate Forest", 
"Andrea Haugen", 
"John Haughm", 
"Anna von Hausswolff", 
"Carl Michael von Hausswolff", 
"Have a Nice Life", 
"The Haxan Cloak", 
"Hazard", 
"Simon Heath", 
"Hecate", 
"Tim Hecker", 
"Christoph Heemann", 
"Heimkveld Kunst", 
"Sven Helbig", 
"Hell", 
"Hieronymus Bosch", 
"Higher Intelligence Agency", 
"Vladimír Hirsch", 
"Aubrey Hodges", 
"Nicolas Horvath", 
"House of Low Culture", 
"How to Destroy Angels", 
"Dean Hurley", 
"Hwyl Nofio", 
"", 
"I, J", 
"", 
"ICE", 
"Ice Ages", 
"Das Ich", 
"If, Bwana", 
"Ildjarn", 
"In Death It Ends", 
"Tetsu Inoue", 
"In Slaughter Natives", 
"In the Nursery", 
"Rafael Anton Irisarri", 
"Mark Isham", 
"Jacaszek", 
"David Jackman", 
"Jarboe", 
"Jesu", 
"JK Flesh", 
"Job Karma", 
"Jóhann Jóhannsson", 
"Maurice de Jong", 
"Juno Reactor", 
"GX Jupitter-Larsen", 
"Caroline K", 
"Edward Ka-Spel", 
"Yuki Kajiura", 
"Kammarheit", 
"Karjalan Sissit", 
"Khanate", 
"Khlyst", 
"The Kilimanjaro Darkjazz Ensemble", 
"Jacob Kirkegaard", 
"Romke Kleefstra", 
"Klein", 
"Klinik", 
"The Knife", 
"Knurl", 
"Thomas Köner", 
"Konstruktivits", 
"Hermann Kopp", 
"Mark Korven", 
"Bettina Köster", 
"kREEPA", 
"Kreng", 
"Kreuzweg Ost", 
"David Kristian", 
"Kroda", 
"KTL", 
"Jesper Kyd", 
"Labradford", 
"Lab Report", 
"Laibach", 
"Alan Lamb", 
"Bill Laswell", 
"Leæther Strip", 
"Richard Lederer", 
"Thomas Leer", 
"The Legendary Pink Dots", 
"Les Légions Noires", 
"Leviathan", 
"Lifelover", 
"Lightwave", 
"Andrew Liles", 
"Lilith", 
"Lingua Ignota", 
"Locrian", 
"Locust", 
"Francisco López", 
"Lord Wind", 
"Lorn", 
"Loscil", 
"Lotus Eaters", 
"Lull", 
"Lunar Womb", 
"Tor Lundvall", 
"Lustmord", 
"Lustre", 
"Lycia", 
"David LynchM", 
"", 
"m2 (Squaremeter)", 
"Machinefabriek", 
"Maeror Tri", 
"Main", 
"Mama Baer", 
"Mamiffer", 
"Manetheren", 
"Maniac", 
"Clint Mansell", 
"Lasse Marhaug", 
"Cliff Martinez", 
"Bear McCreary", 
"Drew McDowall", 
"Melvins", 
"Daniel Menche", 
"Mentallo and the Fixer", 
"Merzbow", 
"Mesektet", 
"MGR", 
"Midnight Syndicate", 
"Militia Christi", 
"Mistigo Varggoth Darkestra", 
"Moby", 
"Mogwai", 
"The Moon Lay Hidden beneath a Cloud", 
"Steve Moore", 
"Mike Morasky", 
"Mark Morgan", 
"Morgenstern", 
"Morthound", 
"Mortiis", 
"Moss", 
"The Mount Fuji Doomjazz Corporation", 
"Moz", 
"Murcof", 
"John Murphy", 
"Muslimgauze", 
"Mz.412", 
"Nadja", 
"Naked City", 
"Pete Namlook", 
"Narqath", 
"Nattramn", 
"Nebulon", 
"Necromantia", 
"Necrophorus", 
"Negură Bunget", 
"Neptune Towers", 
"Loren Nerell", 
"Nest", 
"Phill Niblock", 
"Nightmare Lodge", 
"B. J. Nilsen", 
"Nine Inch Nails", 
"Nocturnal Emissions", 
"Noisegate", 
"NON", 
"Nordvargr", 
"Nortt", 
"Not Your Average Hippy", 
"Nox Arcana", 
"K.K. Null", 
"Nurse with Wound", 
"Stephen O'Malley", 
"Of the Wand & the Moon", 
"ohGr", 
"Pauline Oliveros", 
"Ombient", 
"Oneiroid Psychosis", 
"Oneohtrix Point Never", 
"Oniric", 
"oOoOO", 
"Oöphoi", 
"Oranssi Pazuzu", 
"Ordo Equilibrio", 
"Ordo Equitum Solis", 
"Orphx", 
"Cezary Ostrowski", 
"Otto Dix", 
"O Yuki Conjugate", 
"", 
"P, Q", 
"", 
"Genesis P-Orridge", 
"Painkiller", 
"Charlemagne Palestine", 
"The Panacea", 
"Pan American", 
"Balázs Pándi", 
"Pantha du Prince", 
"Karin Park", 
"Parzival", 
"Paysage d'Hiver", 
"PBK", 
"Daniel Pemberton", 
"Carlos Perón", 
"Sandro Perri", 
"PGR", 
"Pharmakon", 
"Phonothek", 
"Pimentola", 
"James Plotkin", 
"Popol Vuh", 
"Portal", 
"Post Scriptvm", 
"Premature Ejaculation", 
"Steven Price", 
"Primitve Man", 
"Profane Grace", 
"Psychick Warriors ov Gaia", 
"Psychic TV", 
"Puce Mary", 
"Puissance", 
"PureH", 
"Fatima Al Qadiri", 
"Éliane Radigue", 
"Radio Werewolf", 
"Raison d'être", 
"Richard Ramirez", 
"Rapoon", 
"Redshift", 
"Reformed Faction", 
"Brian Reitzell", 
"The Residents", 
"The Resonance Association", 
"Graeme Revell", 
"Trent Reznor", 
"Rhythm & Noise", 
"Robert Rich", 
"John Richards", 
"Bill Rieflin", 
"Robin Rimbaud", 
"Tapani Rinne", 
"Steve Roach", 
"Steve Roden", 
"Rome", 
"Yuval Ron", 
"Sam Rosenthal", 
"Rosetta", 
"Atticus Ross", 
"Anthony Rother", 
"Rude 66", 
"Ruptured World", 
"Paul Ruskay", 
"Sabled Sun", 
"Gjøran Sæther", 
"Ryuichi Sakamoto", 
"Salem", 
"Ben Salisbury", 
"Sällskapet", 
"Karl Sanders", 
"Satyricon", 
"Janek Schaefer", 
"Conrad Schnitzler", 
"Zeena Schreck", 
"Matthew Schultz", 
"Klaus Schulze", 
"Paul Schütze", 
"Scorn", 
"Tony Scott", 
"Seefeel", 
"Seirom", 
"Sema", 
"Angela Seo", 
"Steven Severin", 
"Shackleton", 
"Shape of Despair", 
"Shinjuku Thief", 
"Howard Shore", 
"The Sight Below", 
"Sigillum S", 
"Sigur Rós", 
"Silencaeon", 
"Sixth Comm", 
"Richard Skelton", 
"Skepticism", 
"Skinny Puppy (briefly in 1984)", 
"Skrika", 
"Sleep Chamber", 
"SleepResearch_Facility", 
"Sleep Token", 
"Mark Snow", 
"Soap&Skin", 
"Socìetas Raffaello Sanzio", 
"Socionic", 
"Soiled", 
"Solar Fields", 
"Soma", 
"Sophia", 
"SpaceGhostPurrp", 
"Specimens", 
"Spektr", 
"SPK", 
"Alan Splet", 
"Stalnoy Pakt", 
"Steven Stapleton", 
"Stars of the Lid", 
"Michael Stearns", 
"Michael Stein & Kyle Dixon", 
"Colin Stetson", 
"Storm Corrosion", 
"Stratvm Terror", 
"Striborg", 
"Summoning", 
"Sunn O)))", 
"Swans", 
"David Sylvian", 
"Synæsthesia", 
"Craig Taborn", 
"Tangerine Dream", 
"Mikko Tarmia", 
"Tear Ceremony", 
"The Tear Garden", 
"Teargas & Plateglass", 
"Techno Animal", 
"Teeth of Lions Rule the Divine", 
"Tenhi", 
"Test Dept", 
"François Tétaz", 
"Terre Thaemlitz", 
"Thighpaulsandra", 
"The Third Eye Foundation", 
"Robert Scott Thompson", 
"Thou", 
"Thou Shalt Suffer", 
"Throbbing Gristle", 
"David Thrussell", 
"David Tibet", 
"Asmus Tietchens", 
"TISM (briefly in the 1980s)", 
"Amon Tobin", 
"Toroidh", 
"Devin Townsend", 
"Jill Tracy", 
"Trance to the Sun", 
"Trepaneringsritualen", 
"Triangular Ascension", 
"Tribes of Neurot", 
"Troum", 
"Trust Obey", 
"Tuu", 
"Twice a Man", 
"", 
"U, V", 
"", 
"Uboa", 
"Mirko Uhlig", 
"Ulver", 
"Unto Ashes", 
"V/Vm", 
"Mika Vainio", 
"Mike VanPortfleet", 
"Christina Vantzou", 
"Velvet Cacoon", 
"Die Verbannten Kinder Evas", 
"Darrin Verhagen", 
"Vidna Obmana", 
"Franck Vigroux", 
"Vindensång", 
"Violence", 
"VNV Nation", 
"Voice of Eye", 
"Vromb", 
"Kanon Wakeshima", 
"Scott Walker", 
"Wapstan", 
"Wardruna", 
"Warning Light", 
"Norman Westberg", 
"Westwind", 
"Whitehouse", 
"White Ring", 
"Guy Whitmore", 
"Klaus Wiese", 
"Simon Wilkinson", 
"Will", 
"Steven Wilson", 
"Windy & Carl", 
"A Winged Victory for the Sullen", 
"Witchman", 
"Chelsea Wolfe", 
"Wolves in the Throne Room", 
"Wongraven", 
"Woob", 
"Worriedaboutsatan", 
"Wrekmeister Harmonies", 
"Wumpscut", 
"Xasthur", 
"Xiu Xiu", 
"X Marks the Pedwalk", 
"Akira Yamaoka", 
"Year of No Light", 
"Yellow Swans", 
"Christopher Young", 
"David Yow", 
"Luca Yupanqui", 
"Z'EV", 
"Za Frûmi", 
"Eric Zann", 
"John Zewizz", 
"Adrian von Ziegler", 
"Hans Zimmer", 
"Zoar", 
"Zonal", 
"John Zorn", 
"Zos Kia", 
"Zoviet France"];