export default [
  'Paper clips',
  'Stapler',
  'Scissors',
  'Pens',
  'Pencils',
  'Highlighters',
  'Markers',
  'Correction tape',
  'Tape dispenser',
  'Sticky notes',
  'Rubber bands',
  'Binder clips',
  'Notebooks',
  'Folders',
  'File folders',
  'Index cards',
  'Envelopes',
  'Push pins',
  'Binder',
  'Whiteboard',
  'Dry erase markers',
  'Calculator',
  'Desk organizer',
  'Paper shredder',
  'Hole puncher',
  'Paper cutter',
  'Post-it pads',
  'Desk lamp',
  'Monitor stand',
  'Desk calendar',
  'Paperweight',
  'USB flash drive',
  'External hard drive',
  'Mouse pad',
  'Desk chair',
  'Desk mat',
  'Desk drawer organizer',
  'Keyboard',
  'Desk fan',
  'Desk clock',
  'Desk phone',
  'Desk nameplate',
  'Desk plant',
  'Printer',
  'Scanner',
  'Fax machine',
  'Laminator',
  'Shredder bags',
  'Paper towel dispenser',
  'Hand sanitizer',
  'Ink cartridges',
  'Toner cartridges',
  'Writing pad',
  'Desk blotter',
  'Desk caddy',
  'Desk tray',
  'Business card holder',
  'Letter opener',
  'Stamps',
  'Mail scale',
  'Badge holder',
  'Lanyard',
  'Whiteboard eraser',
  'Magnets',
  'Bulletin board',
  'Pencil sharpener',
  'Correction fluid',
  'Binder dividers',
  'Postage labels',
  'Shipping tape',
  'Presentation remote',
  'Laser pointer',
  'Meeting agenda template',
  'Expanding file folder',
  'Desk grommet',
  'USB hub',
  'Desk pen holder',
  'Desk file organizer',
  'Wireless mouse',
  'Desk drawer lock',
  'Monitor riser',
  'Desk name tags',
  'Desk cable management',
  'Keyboard wrist rest',
  'Desk power strip',
  'Staple remover',
  'Document tray',
  'Scanner software',
  'Wireless headset',
  'Desk privacy panel',
  'Multi-function printer',
  'Desk corner sleeve',
  'Cable clips',
  'Desk monitor mount',
  'Desk footrest',
  'Wireless keyboard',
  'Desk cable grommet',
  'Desk cable cover',
  'Desk-mounted power outlet',
  'Laptop stand',
  'Ergonomic keyboard',
  'Desk drawer slide'
];