export default [  
"ankle pants",  
"baggy pants",  
"beach pants",  
"bell bottoms",  
"biker pants",  
"bootcut pants",  
"boyfriend pants",  
"cargo pants",  
"carrot pants",  
"chinos",  
"clamdiggers",  
"culottes",  
"cutoffs",  
"denim pants",  
"disco pants",  
"dungarees",  
"flare pants",  
"fleece pants",  
"gaucho pants",  
"harem pants",  
"high-waisted pants",  
"hiking pants",  
"jeggings",  
"jeans",  
"jodhpur pants",  
"joggers",  
"khakis",  
"knickers",  
"leggings",  
"linen pants",  
"loose pants",  
"low rise pants",  
"maternity pants",  
"MC Hammer pants",  
"mom jeans",  
"palazzo pants",  
"paper bag pants",  
"pegged pants",  
"pinstripe pants",  
"pleated pants",  
"ponte pants",  
"riding pants",  
"sailor pants",  
"satin pants",  
"short pants",  
"skinny pants",  
"slacks",  
"slim pants",  
"sweatpants",  
"tapered pants",  
"track pants",  
"trousers",  
"twill pants",  
"wide leg pants",  
"wind pants",  
"wool pants",  
"yoga pants",  
"zipper pants",  
"acid wash jeans",  
"athletic pants",  
"balloon pants",  
"cargo joggers",  
"cargo trousers",  
"corduroys",  
"crop pants",  
"cuffed pants",  
"dress pants",  
"drawstring pants",  
"embellished pants",  
"faux leather pants",  
"fitted pants",  
"flowy pants",  
"gym pants",  
"hiking trousers",  
"hot pants",  
"jumper pants",  
"kick flare pants",  
"lace pants",  
"leather pants",  
"legging pants",  
"linen trousers",  
"loose fit pants",  
"midi pants",  
"military pants",  
"paperbag waist pants",  
"peg leg pants",  
"plaid pants",  
"puffer pants",  
"rain pants",  
"ribbed pants",  
"safari pants",  
"seamless leggings",  
"shredded jeans",  
"skater pants",  
"skinny cargo pants",  
"slim-fit trousers",  
"smocked waist pants",  
"snakeskin pants",  
"snow pants",  
"straight-leg pants",  
"stripe pants",  
"suit pants",  
"tailored pants",  
"tapered trousers",  
"tartan pants",  
"thermal pants",  
"treggings",  
"tropical pants",  
"tuxedo pants",  
"utility pants",  
"velvet pants",  
"wide waistband pants",  
"wool trousers"]
