export default ["Acid-free paper",
  "Adhesive paper",
  "Art paper",
  "Bank paper",
  "Baryta paper",
  "Bible paper",
  "Blotting paper",
  "Bond paper",
  "Book paper",
  "Bristol paper",
  "Butcher paper",
  "C1S and C2S paper",
  "Carbonless copy paper",
  "Cardboard",
  "Cast-coated paper",
  "Cellophane",
  "Chalk paper",
  "Chiyogami paper",
  "Chrome paper",
  "Coated paper",
  "Construction paper",
  "Contour paper",
  "Copy paper",
  "Corrugated fiberboard",
  "Cotton paper",
  "Cotton rag paper",
  "Craft paper",
  "Crepe paper",
  "Crisp paper",
  "Curtain paper",
  "Deckle edge paper",
  "Delicate tissue paper",
  "Demy paper",
  "Diploma paper",
  "Drawing paper",
  "Eggshell paper",
  "Embossed paper",
  "Enamel paper",
  "Engineering paper",
  "Filter paper",
  "Fine art paper",
  "Foamcore",
  "Foil paper",
  "Glossy paper",
  "Greaseproof paper",
  "Gummed paper",
  "Handmade paper",
  "Heat transfer paper",
  "Hemp paper",
  "Holographic paper",
  "Index paper",
  "Ingres paper",
  "Japanese paper",
  "Joss paper",
  "Kraft paper",
  "Laid paper",
  "Laser paper",
  "Leather paper",
  "Letterpress paper",
  "Lightweight paper",
  "Linen paper",
  "Litho paper",
  "Luster paper",
  "Machine-made paper",
  "Manila paper",
  "Marbled paper",
  "Metallic paper",
  "Mold-made paper",
  "Moth-resistant paper",
  "Mulberry paper",
  "Music paper",
  "Newsprint",
  "Notebook paper",
  "Offset paper",
  "Onion skin paper",
  "Opaque paper",
  "Oxford paper",
  "Parchment paper",
  "Patterned paper",
  "Perforated paper",
  "Photo paper",
  "Plastic paper",
  "Plywood",
  "Pondicherry paper",
  "Poster paper",
  "Printing paper",
  "Pulp paper",
  "Quilling paper",
  "Rag paper",
  "Recycled paper",
  "Red rosin paper",
  "Reprographic paper",
  "Rice paper",
  "Rifle paper",
  "Roofing felt",
  "Saddle-stitched paper",
  "Satin paper",
  "Sculpting paper",
  "Seed paper",
  "Semi-gloss paper",
  "Sewing pattern paper",
  "Shoji paper",
  "Slick paper",
  "Smooth paper",
  "Soy paper",
  "Suede paper",
  "Tear-resistant paper",
  "Text paper",
  "Tissue paper",
  "Tracing paper",
  "Transfer paper",
  "Translucent paper",
  "Transparent paper",
  "Tweed paper",
  "Typewriter paper",
  "Vellum",
  "Wallpaper",
  "Watercolor paper",
  "Waxed paper",
  "Wedding invitation paper"]