export default [
"Henry David Thoreau", 
"Mary Baker Eddy ", 
"Paramahansa Yogananda", 
"Wallace D. Wattles", 
"Edgar Cayce", 
"Marianne Williamson", 
"Deepak Chopra", 
"Carl Jung", 
"Timothy Leary ", 
"Ram Dass", 
"Aldous Huxley", 
"Krishnamurti ", 
"Graham Hancock", 
"Robert Anton Wilson", 
"Bill Hicks", 
"Terence McKenna", 
"Allan Watts", 
"Socrates ", 
"Plato ", 
"Aristotle ", 
"Immanuel Kant ", 
"Nietzsche ", 
"Rousseau ", 
"Descartes ", 
"Thomas Hobbes", 
"John Stuart Mill", 
"David Hume", 
"Hypatia of Alexandria", 
"Mary Wollstonecraft", 
"Simone de Beauvoir", 
"Hannah Arendt", 
"Martha Nussbaum", 
"Judith Butler", 
"Angela Davis", 
"Elizabeth Anscombe", 
"Susan Sontag", 
"Iris Murdoch", 
"Martin Luther King Jr.", 
"Malcolm X", 
"Rosa Parks", 
"Nelson Mandela", 
"Mahatma Gandhi", 
"W.E.B. Du Bois", 
"Angela Davis", 
"Ruby Bridges", 
"Cesar Chavez", 
"James Baldwin", 
"Tony Robbins", 
"Dale Carnegie", 
"Napoleon Hill", 
"Louise Hay", 
"Wayne Dyer", 
"Eckhart Tolle", 
"Deepak Chopra", 
"Brené Brown", 
"Stephen Covey", 
"Jen Sincero", 
"Richard Rorty", 
"Martha Nussbaum", 
"Noam Chomsky", 
"Cornel West", 
"Judith Butler", 
"Daniel Dennett", 
"Mark Twain",
"John Searle", 
"Robert Brandom", 
"Alva Noë", 
"Charles Taylor", 
"Democritus", 
"Epicurus", 
"Diagoras of Melos", 
"Lucretius", 
"Baruch Spinoza", 
"Denis Diderot", 
"Percy Bysshe Shelley", 
"Friedrich Nietzsche", 
"Bertrand Russell", 
"Madalyn Murray O'Hair"/*, 
"Rachel Maddow", 
"Chris Hayes", 
"Lawrence O'Donnell", 
"Joy Reid", 
"Keith Olbermann", 
"Stephanie Miller", 
"Cenk Uygur", 
"Ana Kasparian", 
"John Stewart", 
"Sam Seder", 
"Bill Maher", 
"William F. Buckley Jr.", 
"Rush Limbaugh", 
"Ann Coulter", 
"Ben Shapiro", 
"Mark Levin", 
"Laura Ingraham", 
"Sean Hannity", 
"Tucker Carlson", 
"Glenn Beck", 
"Dennis Prager"*/];