export default [
  "Portrait",
  "Landscape",
  "Street",
  "Nature",
  "Sports",
  "Wildlife",
  "Fashion",
  "Macro",
  "Product",
  "Black and White",
  "Abstract",
  "Astrophotography",
  "Architecture",
  "Aerial",
  "Underwater",
  "Wedding",
  "Food",
  "Night",
  "Pet",
  "Travel",
  "Fine Art",
  "Concert",
  "Documentary",
  "Maternity",
  "Boudoir",
  "Event",
  "Real Estate",
  "Photojournalism",
  "Historic",
  "Panorama",
  "HDR",
  "Time-lapse",
  "Long Exposure",
  "Infrared",
  "360-Degree",
  "Abstract Expressionism",
  "Action",
  "Adventure",
  "Architecture",
  "Artistic",
  "Astro",
  "Bird",
  "Candid",
  "Cityscape",
  "Close-up",
  "Cloudscape",
  "Conceptual",
  "Creative",
  "Culinary",
  "Culture",
  "Dance",
  "Dramatic",
  "Environmental",
  "Experimental",
  "Extreme Sports",
  "Family",
  "Film",
  "Floral",
  "Glamour",
  "High-Speed",
  "Infrared",
  "Lifestyle",
  "Low-Light",
  "Melancholy",
  "Monochrome",
  "Music",
  "Nautical",
  "Nighttime",
  "Nude",
  "Ocean",
  "Offbeat",
  "Old-Fashioned",
  "Perspective",
  "Pet",
  "Photojournalistic",
  "Pictorialism",
  "Pinhole",
  "Portraiture",
  "Reflection",
  "Regional",
  "Romantic",
  "Satirical",
  "Science",
  "Seascape",
  "Silhouette",
  "Snapshot",
  "Social Documentary",
  "Spiritual",
  "Still Life",
  "Stock",
  "Street",
  "Sublime",
  "Surrealism",
  "Tilt-Shift",
  "Timelapse",
  "Traditional",
  "Travel",
  "Underwater",
  "Urban",
  "Vintage",
  "War",
  "Wedding",
  "Wide-Angle",
  "Wildlife",
  "Shot reverse shot",
  "Pan",
  "Tilt",
  "Tracking shot",
  "Crane shot",
  "Aerial shot",
  "Handheld camera",
  "Steadicam",
  "Dolly zoom",
  "Close-up",
  "Extreme close-up",
  "Medium shot",
  "Extreme long shot",
  "Over the shoulder shot",
  "Point of view shot",
  "Low angle shot",
  "High angle shot",
  "Dutch angle",
  "Rack focus",
  "Split diopter",
  "Zoom",
  "Vertigo effect",
  "Shotgun shot",
  "Two-shot",
  "Three-shot",
  "Group shot",
  "Single shot",
  "Establishing shot",
  "Cutaway shot",
  "Reaction shot",
  "Insert shot",
  "Bridging shot",
  "Cross-cutting",
  "Parallel editing",
  "Montage",
  "Long take",
  "One shot",
  "Single take",
  "Stitching",
  "SnorriCam",
  "Crash zoom",
  "Focus pulling",
  "Racking focus",
  "Panning shot",
  "Pedestal shot",
  "Handheld tracking shot",
  "Crash pan",
  "Match cut",
  "Swish pan",
  "Whip pan",
  "360 degree shot",
  "180 degree shot",
  "Wide shot",
  "Full shot",
  "Long shot",
  "Medium long shot",
  "Medium close-up",
  "Two shot",
  "Choker shot",
  "Medium two shot",
  "Cowboy shot",
  "Extreme wide shot",
  "Point of view reverse shot",
  "Medium close up",
  "Low angle",
  "Omniscient point of view shot",
  "Fourth wall break",
  "Top shot",
  "Bird's eye view",
  "Down shot",
  "Crab shot",
  "Slanted shot",
  "Dolly shot",
  "Trolley shot",
  "Roundabout shot",
  "Spiral shot",
  "Trick shot",
  "Canted shot",
  "Static shot",
  "Freeze-frame",
  "Slow motion",
  "Fast motion",
  "Reverse motion",
  "Split screen",
  "Triple split screen",
  "Morphing",
  "Animation",
  "Green screen",
  "Matte painting",
  "Motion control",
  "Stop motion",
  "Time-lapse",
  "Hitchcock zoom",
  "Birdman shot",
  "Goodfellas shot",
  "Tarantino shot",
  "Touch of Evil shot",
  "Matrix bullet time",
  "Snake cam",
  "Superimposition",
  "Overcrank",
  "Undercrank",
  "Dutch tilt",
  "Low mode",
  "Overhead shot",
  "Crab dolly",
  "Helicopter shot",
  "Octocopter shot",
  "Cablecam shot",
  "Drone shot"
];
