export default ["Standing straight with arms at sides",
  "Standing straight with hands on hips",
  "Standing with one hand on hip",
  "Standing with one hand on head",
  "Standing with one hand on waist",
  "Standing with crossed arms",
  "Standing with one arm raised above head",
  "Standing with both arms raised above head",
  "Standing with hands clasped in front",
  "Standing with hands in pockets",
  "Standing with one foot slightly in front of the other",
  "Standing with one foot crossed over the other",
  "Standing with weight on one leg",
  "Sitting with legs crossed",
  "Sitting with legs straight out",
  "Sitting with one leg bent and one leg straight",
  "Sitting with both legs bent and feet on floor",
  "Sitting with both legs bent and feet on chair",
  "Sitting with one knee up and one knee down",
  "Sitting with legs tucked to one side",
  "Sitting with one foot on chair",
  "Lying on back with arms stretched overhead",
  "Lying on stomach with chin resting on hands",
  "Lying on side with arm propped up",
  "Lying on side with one leg bent",
  "Leaning against a wall with one foot up",
  "Leaning against a wall with arms crossed",
  "Leaning against a wall with one hand on hip",
  "Leaning against a wall with both hands on wall",
  "Leaning against a wall with one foot on wall",
  "Leaning forward with hands on knees",
  "Leaning forward with hands on thighs",
  "Leaning forward with arms crossed on table",
  "Leaning back with arms behind head",
  "Leaning back with hands behind back",
  "Leaning back with hands on hips",
  "Leaning to one side with one hand on hip",
  "Leaning to one side with both hands on hips",
  "Bending forward to touch toes",
  "Bending forward with hands on floor",
  "Bending forward with one leg bent and one leg straight",
  "Bending forward with arms extended in front",
  "Bending backward with arms extended overhead",
  "Bending backward with hands on hips",
  "Bending sideways with one arm reaching overhead",
  "Bending sideways with both arms reaching overhead",
  "Jumping with arms extended overhead",
  "Jumping with knees bent and arms extended in front",
  "Jumping with one leg extended behind",
  "Jumping with one knee up and arms extended overhead",
  "Walking forward with one foot in front of the other",
  "Walking forward with one foot behind the other",
  "Walking forward with arms swinging at sides",
  "Walking forward with hands in pockets",
  "Walking forward with one hand on hip",
  "Walking forward with both hands on hips",
  "Walking forward with hands clasped in front",
  "Walking backward with one foot in front of the other",
  "Walking backward with one foot behind the other",
  "Walking backward with arms swinging at sides",
  "Walking backward with hands in pockets",
  "Walking backward with one hand on hip",
  "Walking backward with both hands on hips",
  "Walking backward with hands clasped in front",
  "Walking sideways with one hand on hip",
  "Walking sideways with both hands on hips",
  "Walking sideways with arms extended",
  "Walking sideways with one arm reaching overhead",
  "Running with arms swinging at sides",
  "Running with hands clasped in front",
"Running with one hand on hip",
"Running with both hands on hips",
"Running with arms extended overhead",
"Running with one arm reaching forward",
"Running with one arm reaching overhead",
"Running with one arm behind back",
"Running with one leg bent and one leg straight",
"Running with one knee up and one arm extended forward",
"Running with one knee up and both arms extended overhead",
"Running with one knee up and both hands on hips",
"Running with both knees up and both arms extended overhead",
"Jumping with one leg forward and one leg back",
"Jumping with both legs forward",
"Jumping with both legs back",
"Jumping with one leg extended to the side",
"Jumping with both legs extended to the side",
"Jumping with one knee up and one leg extended behind",
"Jumping with one knee up and one arm extended forward",
"Jumping with both knees up and both arms extended forward",
"Jumping with both knees up and both arms extended overhead",
"Crouching down with arms around knees",
"Crouching down with one hand on knee",
"Crouching down with both hands on floor",
"Squatting with arms crossed in front",
"Squatting with arms extended overhead",
"Squatting with hands on hips",
"Squatting with one leg extended behind",
"Squatting with one leg bent and one leg extended behind",
"Squatting with both legs bent and feet on floor",
"Squatting with both legs bent and feet on tiptoes",
"Standing on one leg with arms extended to the side",
"Standing on one leg with one arm reaching overhead",
"Standing on one leg with both arms extended overhead",
"Standing on tiptoes with arms extended overhead",
"Standing on tiptoes with one arm reaching overhead",
"Standing on tiptoes with both arms extended to the side",
"Sitting on floor with legs extended in front",
"Sitting on floor with one leg bent and one leg extended",
"Sitting on floor with legs crossed in front",
"Sitting on floor with one leg tucked to side",
"Sitting on floor with both knees up and feet on floor",
"Sitting on floor with both knees up and feet on tiptoes"
];