export default ["Purr-fect match",
"Sweet dreams",
"Berry nice",
"Love bug",
"Happy camper",
"Fizz-ical attraction",
"Honey bee",
"Taco 'bout love",
"Olive you",
"Donut worry",
"You rock",
"Cuddle buddy",
"French kiss",
"Top dog",
"Pretty penny",
"Love birds",
"Carrot crazy",
"Cool cat",
"Dough nut",
"Cutie pie",
"Party animal",
"Cheese please",
"Spice it up",
"Butterfly kisses",
"Bae goals",
"Apple of my eye",
"Fishy business",
"Panda-monium",
"Peanut buttered",
"Star gazer",
"Lemon drop",
"Smart cookie",
"Cupcake cutie",
"Bee happy",
"Fancy pants",
"Love struck",
"Chirp chirp",
"Dream team",
"Jelly belly",
"Hug me",
"Panda bear",
"Cinnamon bun",
"Snuggle bug",
"Hot stuff",
"Monkey business",
"Fancy feast",
"Sweetheart deal",
"Pig out",
"Honey dew",
"Bear hug",
"Happy feet",
"Peachy keen",
"Love seat",
"Smarty pants",
"Berry best",
"Sweet tooth",
"Cattywampus",
"Butterfly effect",
"Donut stop",
"Puppy love",
"Sweetie pie",
"Monkey around",
"Grape expectations",
"Love shack",
"Crazy cool",
"Cream of the crop",
"Pumpkin pie",
"Angel face",
"Buzz off",
"Eye candy",
"Koala-fications",
"Bear necessity",
"Cute as a button",
"Peas in a pod",
"Happy hour",
"Snuggle up",
"Cool beans",
"Furry friend",
"Cherry on top",
"Honey bunch",
"Sweet talk",
"Kangaroo crossing",
"Smarty pants",
"Bear-y cute",
"Butter me up",
"Lovely dovey",
"Smooch pooch",
"Owl always love you",
"Apple-y ever after",
"Pumpkin spice",
"Dream come true",
"Monkey see",
"Berry fun",
"Sugar rush",
"Starry night",
"Sun-kissed",
"Snicker doodle",
"Cuddle time",
"Dolphinately cute",
"Gouda vibes"];