export default [
  'Freddie Mercury', 'David Bowie', 'Elvis Presley', 'Mick Jagger', 'Keith Richards', 'John Lennon',
  'Paul McCartney', 'George Harrison', 'Ringo Starr', 'Jimi Hendrix', 'Eric Clapton', 'Jimmy Page', 'Jim Morrison',
  'Robert Plant', 'John Bonham', 'Paul Simon', 'Art Garfunkel', 'Roger Waters', 'David Gilmour',
  'Syd Barrett', 'Roger Daltrey', 'Pete Townshend', 'Keith Moon', 'Ronnie Wood', 'Mick Taylor',
  'Brian Jones', 'Charlie Watts', 'Bill Wyman', 'Sting', 'Andy Summers', 'Stevie Nicks', 'Lindsey Buckingham',
  'Mick Fleetwood', 'Christine McVie', 'John McVie', 'Tom Petty', 'Bruce Springsteen', 'Steve Perry',
  'Journey', 'Bon Jovi', 'Richie Sambora', 'Eddie Vedder', 'Kurt Cobain', 'Dave Grohl', 'Krist Novoselic',
  'Axl Rose', 'Slash', 'Izzy Stradlin', 'Duff McKagan', 'Steven Adler', 'Brian Wilson', 'Mike Love',
  'Al Jardine', 'Bruce Johnston', 'David Lee Roth', 'Eddie Van Halen', 'Alex Van Halen', 'Michael Anthony',
  'Sammy Hagar', 'Neil Young', 'Bob Dylan', 'Tom Waits', 'Joe Strummer', 'Mick Jones', 'Paul Simonon',
  'Topper Headon', 'Joe Elliott', 'Steve Clark', 'Rick Allen', 'Phil Collen', 'Rick Savage',
  'Glenn Frey', 'Don Henley', 'Joe Walsh', 'Timothy B. Schmit', 'Randy Meisner', 'Bernie Leadon',
  'Joan Jett', 'David Byrne', 'Chris Frantz', 'Tina Weymouth', 'Jerry Garcia', 'Bob Weir', 'Phil Lesh',
  'Pigpen', 'Keith Emerson', 'Greg Lake', 'Carl Palmer', 'Axl Rose', 'Slash', 'Izzy Stradlin', 'Duff McKagan',
  'Steven Adler', 'David Coverdale', 'Ritchie Blackmore', 'Jon Lord', 'Ian Gillan', 'Roger Glover',
  'Phil Lynott', 'Gary Moore', 'Scott Gorham', 'Brian Downey', 'Eric Carr', 'Peter Criss', 'Gene Simmons',
  'Paul Stanley', 'Ace Frehley', 'Vinnie Vincent', 'Bruce Kulick', 'Tommy Thayer', 'Eric Singer',
  'Rob Halford', 'Glenn Tipton', 'K.K. Downing', 'Ian Hill', 'Scott Travis', 'Steve Harris', 'Bruce Dickinson',
  'Dave Murray', 'Adrian Smith', 'Janis Joplin', 'Jimi Hendrix', 'Neil Peart', 'Geddy Lee', 'Alex Lifeson',
  'Eddie Vedder', 'Chris Cornell', 'Layne Staley', 'Jerry Cantrell', 'Mike McCready', 'Stone Gossard',
  'Eddie Vedder', 'Jack White', 'Billy Corgan', 'Dave Matthews', 'Tom Morello', 'Zack de la Rocha',
  'Chris Robinson', 'Rich Robinson', 'Jimmy Chamberlin', 'James Iha', 'Darcy Wretzky', 'Billy Joel',
  'Jim Morrison', 'Janis Joplin', 'Jimi Hendrix', 'Kurt Cobain', 'Chris Cornell', 'Layne Staley',
  'Eddie Vedder', 'Robert Plant', 'Freddie Mercury', 'Axl Rose', 'Steven Tyler', 'Ozzy Osbourne',
  'Ian Curtis', 'Morrissey', 'Jeff Buckley', 'David Bowie', 'Thom Yorke', 'Nick Cave', 'Iggy Pop',
  'Mick Jagger', 'Roger Daltrey', 'Bruce Springsteen', 'Patti Smith', 'Grace Slick', 'Stevie Nicks',
  'Ann Wilson', 'Robert Smith', 'Bjork', 'Annie Lennox', 'PJ Harvey', 'Siouxsie Sioux',
  'Joan Jett', 'Debbie Harry', 'Tina Turner', 'Cher', 'Donna Summer', 'Whitney Houston',
  'Mariah Carey', 'Christina Aguilera', 'Beyoncé', 'Adele', 'Lady Gaga', 'Rihanna', 'Taylor Swift',
  'Ariana Grande', 'Billie Eilish', 'Katy Perry', 'Miley Cyrus', 'Britney Spears', 'Madonna',
  'Celine Dion', 'Carrie Underwood', 'Shania Twain', 'Kelly Clarkson', 'Gwen Stefani',
  'Alanis Morissette', 'Fiona Apple', 'Norah Jones', 'Sia', 'Amy Winehouse', 'Lana Del Rey',
  'Lorde', 'Florence Welch', 'Christina Perri', 'Halsey', 'Dua Lipa', 'Selena Gomez',
  'Jennifer Lopez', 'Demi Lovato', 'Alicia Keys', 'Pink', 'Jessie J', 'Rita Ora',
  'Camila Cabello', 'Bebe Rexha', 'Anne-Marie', 'Ava Max', 'Doja Cat', 'Olivia Rodrigo',
  'Megan Thee Stallion', 'Cardi B', 'Lizzo', 'Billie Joe Armstrong', 'Tom DeLonge',
  'Brandon Flowers', 'Jared Leto', 'Gerard Way', 'Chris Martin', 'Matt Bellamy', 'Thom Yorke',
  'Eddie Vedder', 'Dave Grohl', 'Anthony Kiedis', 'Billy Corgan', 'Scott Weiland',
  'Gavin Rossdale', 'Mark Hoppus', 'Travis Barker', 'Billie Joe Armstrong', 'Bono', 'Bruce Dickinson',
  'Steve Perry', 'Phil Collins', 'Robert Smith', 'Dave Matthews', 'John Mayer', 'Ed Sheeran',
  'Bruno Mars', 'Justin Timberlake', 'Michael Jackson', 'Prince', 'Elton John', 'Billy Joel',
  'Stevie Wonder', 'Barry Gibb', 'Brian Wilson', 'John Lennon', 'Paul McCartney', 'George Harrison',
  'Frank Sinatra', 'Dean Martin', 'Elvis Presley', 'Johnny Cash', 'Roy Orbison', 'Buddy Holly',
  'Little Richard', 'Chuck Berry', 'Fats Domino', 'Jerry Lee Lewis', 'Ray Charles', 'James Brown',
  'Sam Cooke', 'Otis Redding', 'Marvin Gaye', 'Stevie Wonder', 'Al Green', 'Curtis Mayfield',
  'Isaac Hayes', 'Donny Hathaway', 'Roberta Flack', 'Aretha Franklin',  'Toni Braxton', 'Ace of Base', 'Boyz II Men',
    'Wu-Tang Clan', 'Public Enemy', 'N.W.A', 'Run-DMC', 'A Tribe Called Quest', 'The Pharcyde',
  'Outkast', 'De La Soul', 'EPMD', 'Cypress Hill', 'The Roots', 'Gang Starr',
  'Beastie Boys', 'Naughty By Nature', 'Salt-N-Pepa', 'Boogie Down Productions',
  'The Fugees', 'Geto Boys', 'UGK', 'Blackalicious', 'The Roots', 'Jurassic 5',
  'Mobb Deep', 'Bone Thugs-N-Harmony', 'Digital Underground', 'Hieroglyphics',
  'The Beatnuts', 'Pete Rock & C.L. Smooth', 'People Under The Stairs',
  'The Jungle Brothers', 'Nice & Smooth', 'The Alkaholiks', 'Eric B. & Rakim',
  'Ghetto Boys', 'EPMD', 'Deltron 3030', 'J Dilla & Madlib', 'Run The Jewels',
  'Little Brother', 'Atmosphere', 'The Coup', 'The Cool Kids', 'Dilated Peoples',
  'The Dogg Pound', 'M.O.P.', 'Reflection Eternal', 'Mos Def & Talib Kweli',
  'The Hieroglyphics', 'Company Flow', 'Dead Prez', 'Slum Village', 'Black Star',
  'Public Enemy', 'N.W.A', 'A Tribe Called Quest', 'The Pharcyde', 'Wu-Tang Clan',
  'Gang Starr', 'Outkast', 'De La Soul', 'Cypress Hill', 'Boogie Down Productions',
  'Beastie Boys', 'Naughty By Nature', 'Salt-N-Pepa', 'Run-DMC', 'The Fugees',
  'UGK', 'Mobb Deep', 'Bone Thugs-N-Harmony', 'Digital Underground', 'The Roots',
  'Eric B. & Rakim', 'Kool G Rap & DJ Polo', 'Big Daddy Kane', 'LL Cool J',
  'Ice Cube', 'Ice-T', 'Dr. Dre & Snoop Dogg', '2 Live Crew', 'Scarface',
  'Biggie Smalls', 'Tupac Shakur', 'Jay-Z', 'Nas', 'Eminem', 'Lauryn Hill',
  'Kanye West', 'Common', 'Ghostface Killah', 'Raekwon', 'ODB', 'Inspectah Deck',
  'GZA', 'Method Man', 'Redman', 'Big Punisher', 'Ludacris', 'Missy Elliott',
  'The Neptunes', 'Clipse', 'The Diplomats', 'G-Unit', 'The Game', '50 Cent',
  'T.I.', 'Rick Ross', 'Drake', 'Lil Wayne', 'Young Jeezy', 'Busta Rhymes',
  'Black Star', 'MF DOOM', 'Aesop Rock', 'KRS-One', 'RZA', 'Ghostface Killah',
  'Method Man & Redman', 'Redman', 'Lil Kim', 'Mase', 'The Notorious B.I.G.',
  'Ice Cube', 'Nas', 'Jay-Z', 'Lauryn Hill', 'Eminem', 'Tupac Shakur',
  'The Roots', 'Mos Def', 'Talib Kweli', 'Common', 'A Tribe Called Quest']
