export default [
  "Sunset duel, 'The Good, The Bad, The Ugly' - tension and release.",
  "Citizen Kane's snowglobe - innocence lost.",
  "Blade Runner's neon skyline - futurism meets decay.",
  "E.T.'s bike flight silhouetted - magic in the mundane.",
  "Apocalypse Now's flares and shadows - war's hellish chaos.",
  "Floating bag in 'American Beauty' - beauty in the overlooked.",
  "Beach landing in 'Saving Private Ryan' - war's horrifying reality.",
  "Nostalgic sepia in 'O Brother' - old-timey Americana.",
  "Fire-lit faces in 'Barry Lyndon' - 18th-century painting come alive.",
  "Moonlit ballet in 'La La Land' - romance and dreams.",
  "Silhouettes in 'Lawrence of Arabia' - isolation in vastness.",
  "Golden cornfield in 'Gladiator' - afterlife serenity.",
  "Titanic's iceberg - impending doom.",
  "Blue hue in 'The Matrix' - digital coldness.",
  "Forest fight in 'Crouching Tiger' - grace amid chaos.",
  "Spotlights in 'All That Jazz' - ego and vulnerability.",
  "Color change in 'Pleasantville' - awakening and change.",
  "Casablanca's foggy goodbye - mystery and sorrow.",
  "Backlit dance in 'Pulp Fiction' - unexpected romance.",
  "Eerie green in 'Alien' - impending horror.",
  "Mirror maze in 'The Lady from Shanghai' - moral confusion.",
  "Fog in 'The Exorcist' - evil lurking.",
  "Candlelight in 'The Witch' - supernatural dread.",
  "Starry night in 'Moana' - endless possibility.",
  "Car lights in 'No Country' - danger approaches.",
  "Green and red in 'Vertigo' - psychological tension.",
  "Breaking wave in 'The Truman Show' - breaking illusion.",
  "Rain in 'Schindler’s List' - relentless sorrow.",
  "Animated shadows in 'Nosferatu' - otherworldly terror.",
  "Opening dolly in 'Touch of Evil' - brewing chaos.",
  "Golden arches in 'The Founder' - capitalism incarnate.",
  "Clocktower in 'Back to the Future' - time's fluidity.",
  "Twilight in 'Blue is the Warmest Color' - emotional spectrum.",
  "Fiery landscape in 'Mad Max' - nihilistic beauty.",
  "Black and white in 'Roma' - stark reality.",
  "Reflections in 'Parasite' - layered deceit.",
  "Mountain vista in 'The Shining' - isolating grandeur.",
  "Surreal hues in 'Suspiria' - unsettling atmosphere.",
  "Red sunset in 'Gone with the Wind' - despair and beauty.",
  "Trench run in 'Star Wars' - heroism visualized.",
  "Fast zooms in 'Jaws' - immediate danger.",
  "Underwater blue in 'The Shape of Water' - ethereal love.",
  "Burning car in 'Thelma & Louise' - rebellion.",
  "Field of flowers in 'Big Fish' - imaginative wonder.",
  "Golden wheat in 'Days of Heaven' - natural splendor.",
  "Flames in 'Stalker' - existential danger.",
  "Prison bars in 'The Shawshank Redemption' - oppressive system.",
  "Ominous skyline in 'Children of Men' - dystopian reality.",
  "Rain-soaked streets in 'Sin City' - grimy underworld.",
  "Final duel in 'Harakiri' - fatal honor.",
  "Purple haze in 'Joker' - descent into madness.",
  "Dazzling city in 'Coco' - vibrancy of afterlife.",
  "Sunrise in 'The Lion King' - circle of life.",
  "Bleak landscape in 'Fargo' - cold amorality.",
  "Lonely road in 'Nocturnal Animals' - moral crossroads.",
  "Cherry blossoms in 'Mulan' - fleeting beauty.",
  "Blinding white in 'Birdman' - ego’s trap.",
  "Muddy trenches in '1917' - unending struggle.",
  "Snowy wilderness in 'The Revenant' - unforgiving nature.",
  "Reflective helmet in '2001' - existential wonder.",
  "Ornate ballroom in 'Beauty and the Beast' - romance visualized.",
  "Empty chairs in 'Les Misérables' - haunting loss.",
  "Smeared lens in 'The Wrestler' - broken reality.",
  "Spiral staircase in 'Psycho' - descent into madness.",
  "Lanterns in 'Tangled' - dreams take flight.",
  "Isolated lighthouse in 'Annihilation' - unknown terror.",
  "Red door in 'Don't Look Now' - ominous foreshadowing.",
  "Draped fabric in 'Hero' - political complexity.",
  "City ruins in 'A.I.' - lost humanity.",
  "Epic scale in 'Ben-Hur' - grand ambition.",
  "Burning mansion in 'Rebecca' - consuming guilt.",
  "Cliffside duel in 'Princess Bride' - swashbuckling tension.",
  "Red room in 'Twin Peaks' - surreal mystery.",
  "Rooftop in 'The Departed' - pending betrayal.",
  "Dark forest in 'Pan's Labyrinth' - fairytale horror.",
  "Glowing briefcase in 'Pulp Fiction' - enigmatic allure.",
  "Crumbling castle in 'The Fall' - tragic grandiosity.",
  "Ghostly ship in 'Pirates of the Caribbean' - cursed beauty."
]
