export default [
  "Linux",
  "Windows Server",
  "Ubuntu Server",
  "CentOS",
  "Red Hat Enterprise Linux",
  "Debian",
  "FreeBSD",
  "Solaris",
  "IBM AIX",
  "SUSE Linux Enterprise Server",
  "HP-UX",
  "VMware ESXi",
  "Oracle Linux",
  "Cisco UCS",
  "Dell PowerEdge",
  "HPE ProLiant",
  "IBM Power Systems",
  "Supermicro",
  "Lenovo ThinkSystem",
  "Fujitsu Primergy",
  "Web Server",
  "Database Server",
  "File Server",
  "Mail Server",
  "Virtualization Server",
  "DNS Server",
  "FTP Server",
  "Proxy Server",
  "Application Server",
  "Cache Server",
  "Game Server",
  "Alibaba Cloud ECS",
  "Amazon EC2",
  "Microsoft Azure VM",
  "Google Compute Engine",
  "Oracle Cloud Infrastructure",
  "Rack Server",
  "Blade Server",
  "Tower Server",
  "Mainframe",
  "Mini Server",
  "ARM Server",
  "High-Density Server",
  "VPS",
  "Bare Metal Server",
  "Colocation Server",
  "Raspberry Pi Server",
  "Cloud Server",
  "Container Server",
  "OpenStack",
  "CoreOS",
  "ClearOS",
  "Slackware",
  "Arch Linux",
  "Gentoo",
  "Alpine Linux",
  "Fedora Server",
  "NethServer",
  "Zentyal",
  "VyOS",
  "pfSense",
  "Endian Firewall",
  "Untangle NG Firewall",
  "Smoothwall",
  "Sophos UTM",
  "Unix",
  "QNAP",
  "Synology",
  "Asustor",
  "TerraMaster",
  "Buffalo TeraStation",
  "WD My Cloud",
  "LaCie",
  "TrueNAS",
  "Seagate",
  "OpenMediaVault",
  "Amahi",
  "Rockstor",
  "Nexenta",
  "Gluster",
  "Ceph",
  "SwiftStack",
  "Quobyte",
  "Minio",
  "Cloudian HyperStore",
  "SoftNAS",
  "Exablox",
  "DDN Storage",
  "Scality",
  "Infinidat",
  "Drobo",
  "Hitachi Vantara",
  "NetApp",
  "Huawei FusionServer",
  "Inspur",
  "NEC",
  "Cray",
  "SGI",
  "Tyan",
  "ZT Systems",
  "Boston Limited",
  "Ciara Technologies",
  "Iron Systems"
]
