export default [
  "Circle",
  "Square",
  "Triangle",
  "Rectangle",
  "Pentagon",
  "Hexagon",
  "Heptagon",
  "Octagon",
  "Nonagon",
  "Decagon",
  "Hendecagon",
  "Dodecagon",
  "Tridecagon",
  "Tetradecagon",
  "Pentadecagon",
  "Hexadecagon",
  "Heptadecagon",
  "Octadecagon",
  "Enneadecagon",
  "Icosagon",
  "Ellipse",
  "Oval",
  "Parallelogram",
  "Rhombus",
  "Trapezoid",
  "Kite",
  "Scalene Triangle",
  "Isosceles Triangle",
  "Equilateral Triangle",
  "Right Triangle",
  "Acute Triangle",
  "Obtuse Triangle",
  "Cube",
  "Sphere",
  "Cylinder",
  "Cone",
  "Pyramid",
  "Torus",
  "Frustum",
  "Ellipsoid",
  "Tetrahedron",
  "Octahedron",
  "Dodecahedron",
  "Icosahedron",
  "Annulus",
  "Crescent",
  "Heart",
  "Cross",
  "Star",
  "Arrow",
  "Trapezium",
  "Hemisphere",
  "Prism",
  "Paraboloid",
  "Hyperboloid",
  "Helix",
  "Astroid",
  "Deltoid",
  "Lemniscate",
  "Capsule",
  "Lune",
  "Reuleaux Triangle",
  "Sector",
  "Semicircle",
  "Spiral",
  "Wave",
  "Quadrilateral",
  "Pentagram",
  "Hexagram",
  "Heptagram",
  "Octagram",
  "Nonagram",
  "Decagram",
  "Squircle",
  "Teardrop",
  "Cuboid",
  "Antiprism",
  "Twistoid",
  "Hypotrochoid",
  "Epitrochoid",
  "Möbius Strip",
  "Klein Bottle",
  "Trefoil Knot",
  "Figure-Eight Knot",
  "Saddle",
  "Horn Torus",
  "Spindle Torus",
  "Ring Torus",
  "Clifford Torus",
  "Dupin Cyclide",
  "Concave Polygon",
  "Convex Polygon",
  "Regular Polygon",
  "Irregular Polygon",
  "Simple Polygon",
  "Complex Polygon",
  "Star-Shaped Polygon",
  "Self-Intersecting Polygon",
  "Equiangular Polygon",
  "Equilateral Polygon",
  "Isotoxal Polygon",
  "Isogonal Polygon",
  "Quasiregular Polygon",
  "Right Kite",
  "Oblique Kite",
  "Isosceles Trapezoid",
  "Scalene Trapezoid"
]
