export default [
  "Athletic shorts",
  "Bermuda shorts",
  "Boardshorts",
  "Bloomer shorts",
  "Booty shorts",
  "Boxer shorts",
  "Camo shorts",
  "Cargo shorts",
  "Chino shorts",
  "Cuffed shorts",
  "Culottes shorts",
  "Cut-off shorts",
  "Denim shorts",
  "Dolphin shorts",
  "Drawstring shorts",
  "Drop-crotch shorts",
  "Dungaree shorts",
  "Fleece shorts",
  "Floral shorts",
  "High-waisted shorts",
  "Hot pants",
  "Jean shorts",
  "Jogger shorts",
  "Khaki shorts",
  "Lace shorts",
  "Leather shorts",
  "Legging shorts",
  "Linen shorts",
  "Loose shorts",
  "Low-rise shorts",
  "Mesh shorts",
  "Metallic shorts",
  "Mom shorts",
  "Pajama shorts",
  "Paper bag shorts",
  "Pencil shorts",
  "Pleated shorts",
  "Printed shorts",
  "Retro shorts",
  "Ripped shorts",
  "Running shorts",
  "Sailor shorts",
  "Satin shorts",
  "Scalloped shorts",
  "Sequin shorts",
  "Shiny shorts",
  "Short shorts",
  "Skort",
  "Slit shorts",
  "Sport shorts",
  "Studded shorts",
  "Sweat shorts",
  "Tailored shorts",
  "Tassel shorts",
  "Tennis shorts",
  "Tie-dye shorts",
  "Tie-front shorts",
  "Tulip shorts",
  "Velour shorts",
  "Velvet shorts",
  "Vintage shorts",
  "Washed shorts",
  "Wrap shorts",
  "Yoga shorts",
  "Zebra shorts",
  "Basketball shorts",
  "Beach shorts",
  "Bubble shorts",
  "Camo cargo shorts",
  "Capri shorts",
  "Chambray shorts",
  "Comfy shorts",
  "Cotton shorts",
  "Crochet shorts",
  "Cycling shorts",
  "Daisy dukes",
  "Distressed denim shorts",
  "Elastic waist shorts",
  "Embroidered shorts",
  "Faux leather shorts",
  "Flowy shorts",
  "Frilly shorts",
  "Gauze shorts",
  "Gingham shorts",
  "Gym shorts",
  "Harem shorts",
  "High-waisted denim shorts",
  "Houndstooth shorts",
  "Kangaroo pocket shorts",
  "Knit shorts",
  "Laced shorts",
  "Lamé shorts",
  "Laser cut shorts",
  "Lounge shorts",
  "Maternity shorts",
  "Military shorts",
  "Mini shorts",
  "Multicolor shorts",
  "Neon shorts",
  "Overall shorts",
  "Paisley shorts",
  "Patchwork shorts",
  "Pleather shorts",
  "Pocketed shorts",
  "Polo shorts",
  "Print shorts",
  "Puffy shorts",
  "Rainbow shorts",
  "Ribbon shorts",
  "Ripped denim shorts",
  "Safari shorts",
  "Sailor button shorts",
  "Scallop hem shorts",
  "Shortall shorts",
  "Silk shorts",
  "Skate shorts",
  "Slim fit shorts",
  "Striped shorts",
  "Surf shorts",
  "Swim shorts"]