export default [
  "A-line skirt",
  "Accordion skirt",
  "Asymmetrical skirt",
  "Ballerina skirt",
  "Bell skirt",
  "Box pleat skirt",
  "Bubble skirt",
  "Circle skirt",
  "Dirndl skirt",
  "Draped skirt",
  "Fishtail skirt",
  "Flared skirt",
  "Full skirt",
  "Gored skirt",
  "Godet skirt",
  "Gypsy skirt",
  "Handkerchief skirt",
  "Hobble skirt",
  "Hoop skirt",
  "Inverted pleat skirt",
  "Jean skirt",
  "Jersey skirt",
  "Kilt",
  "Knife pleat skirt",
  "Layered skirt",
  "Leather skirt",
  "Maxi skirt",
  "Mermaid skirt",
  "Micro-mini skirt",
  "Midi skirt",
  "Mini skirt",
  "Pencil skirt",
  "Petticoat",
  "Pleated skirt",
  "Poodle skirt",
  "Princess line skirt",
  "Qipao skirt",
  "Rah-rah skirt",
  "Sarong",
  "Skater skirt",
  "Slip skirt",
  "Straight skirt",
  "T-skirt",
  "Tulip skirt",
  "Wraparound skirt",
  "Yoke skirt",
  "Balloon skirt",
  "Broomstick skirt",
  "Cargo skirt",
  "Cascading skirt",
  "Chiton skirt",
  "Crinoline",
  "Dhoti skirt",
  "Flamenco skirt",
  "Flutter skirt",
  "Godets skirt",
  "Handkerchief hem skirt",
  "Harem skirt",
  "Hula skirt",
  "Layered tulle skirt",
  "Lined skirt",
  "Pannier skirt",
  "Paneled skirt",
  "Paperbag waist skirt",
  "Pareo",
  "Peasant skirt",
  "Pintuck skirt",
  "Pouf skirt",
  "Prairie skirt",
  "Sailor skirt",
  "Tiered skirt",
  "Toga skirt",
  "Tutu",
  "Wrap skirt",
  "African skirt",
  "Bandage skirt",
  "Belted skirt",
  "Broomstick lace skirt",
  "Calico skirt",
  "Cargo denim skirt",
  "Chiffon skirt",
  "Convertible skirt",
  "Cotton skirt",
  "Culottes",
  "Dotted skirt",
  "Embroidered skirt",
  "Fitted skirt",
  "Gothic skirt",
  "Grecian skirt",
  "Hanky hem skirt",
  "High-waisted skirt",
  "Jacquard skirt",
  "Khaki skirt",
  "Knit skirt",
  "Lace skirt",
  "Lambada skirt",
  "Leopard print skirt",
  "Maxi wrap skirt",
  "Mesh skirt",
  "Metallic skirt",
  "Mini leather skirt",
  "Net skirt",
  "Organza skirt",
  "Pencil mini skirt",
  "Peplum skirt",
  "Pleather skirt",
  "Polka dot skirt",
  "Prairie maxi skirt",
  "Ruffled skirt",
  "Satin skirt",
  "Scuba skirt",
  "Sequin skirt",
  "Shirred skirt",
  "Suede skirt",
  "Swing skirt",
  "Taffeta skirt",
  "Tie-front skirt",
  "Velvet skirt",
  "Western skirt"]