export default [ "sleeplessness",
  "restlessness",
  "tossing",
  "turning",
  "wakefulness",
  "fatigue",
  "exhaustion",
  "drowsiness",
  "daytime drowsiness",
  "difficulty sleeping",
  "nighttime awakenings",
  "sleep deprivation",
  "sleep disturbance",
  "trouble falling asleep",
  "trouble staying asleep",
  "sleep problems",
  "sleeplessness",
  "insomniac",
  "awake",
  "restless",
  "anxiety",
  "stress",
  "depression",
  "mood swings",
  "irritability",
  "difficulty concentrating",
  "memory problems",
  "headaches",
  "muscle tension",
  "gastrointestinal problems",
  "heart palpitations",
  "night sweats",
  "hot flashes",
  "chills",
  "fatigue",
  "chronic fatigue",
  "lack of energy",
  "poor concentration",
  "poor memory",
  "loss of appetite",
  "overeating",
  "weight gain",
  "weight loss",
  "restless legs",
  "leg cramps",
  "cognitive impairment",
  "poor work performance",
  "daytime fatigue",
  "daytime sleepiness",
  "brain fog",
  "poor judgment",
  "irrational behavior",
  "hallucinations",
  "delusions",
  "anxiety attacks",
  "panic attacks",
  "depressive episodes",
  "suicidal thoughts",
  "social isolation",
  "relationship problems",
  "family conflicts",
  "work stress",
  "financial stress",
  "poor sleep hygiene",
  "sleep apnea",
  "snoring",
  "restless sleep",
  "insomnia",
  "REM sleep",
  "light sleep",
  "deep sleep",
  "dreams",
  "nightmares",
  "sleep talking",
  "sleepwalking",
  "sleep paralysis",
  "hypnagogic hallucinations",
  "bedtime routine",
  "sleep aids",
  "medication",
  "herbal remedies",
  "melatonin",
  "sleep therapy",
  "sleep counseling",
  "sleep education",
  "CBT for insomnia",
  "mindfulness meditation",
  "relaxation techniques",
  "sleep diary",
  "sleep tracking",
  "sleep environment",
  "darkness",
  "quiet",
  "comfort",
  "temperature",
  "mattress",
  "pillow",
  "blanket",
  "bedroom",
  "napping"];