export default [
"8-Bit Art",
"Abstract Expressionism",
"Abstract Expressionist Sculpture",
"Abstract Figurative",
"Abstract Geometric",
"Abstract Landscapes",
"Abstract Typography",
"Abstract",
"Abstracted Architecture",
"Abstracted Cityscapes",
"Abstracted Figures",
"Abstracted Nature",
"Abstracted Seascapes",
"Absurdism",
"Action Painting",
"Action Photography",
"Adult Comic Book",
"Aestheticism",
"Analytical Cubism",
"Anime",
"Arabesque",
"Architectural Illustration",
"Architectural Photography",
"Architectural Rendering",
"Art Brut",
"Art Deco",
"Art Informel",
"Art Nouveau Revival",
"Art Nouveau",
"Art Povera",
"Artistic Realism",
"ASCII Art",
"Ashcan School",
"Automatism",
"Aztec Art",
"Barbizon School",
"Bauhaus",
"Biomorphic Sculpture",
"Body Art",
"Body Painting Art",
"Body Painting",
"Boho Style",
"Book Cover",
"Botanical Illustration",
"Calligraphy Art",
"Canvas",
"Capriccio",
"Carolingian Art",
"Ceramic Sculpture",
"Charcoal",
"Chiaroscuro",
"Chinese Painting",
"Cinematic Photography",
"Classical Art",
"Classical Realism",
"Classicism",
"CoBrA",
"Collage Painting",
"Collage Photography",
"Collage",
"Color Field Painting",
"Conceptual Art",
"Conceptual Photography",
"Concrete Art",
"Concrete Sculpture",
"Constructive Art",
"Constructivism",
"Contemporary Art",
"Contemporary Ceramic Art",
"Contemporary Collage",
"Contemporary Glass Art",
"Contemporary Landscape",
"Contemporary Paper Art",
"Contemporary Realism",
"Contemporary Textile Art",
"Coptic Art",
"Cubism",
"Cubist Landscapes",
"Cubist Realism",
"Cyberpunk",
"Dada",
"Dadaism",
"Danube School",
"Dark Evil",
"De Stijl",
"Der Blaue Reiter",
"Die Neue Sachlichkeit",
"Digital Art",
"Digital Collage",
"Digital Concept Art",
"Digital Landscapes",
"Digital Painting",
"Digital Pop Art",
"Digital Surrealism",
"Divisionism",
"Dot Art",
"Drip Painting",
"Dynamic Painting",
"Dystopian Art",
"Eclecticism",
"Egyptian Art",
"Encaustic Art",
"Environmental Art",
"Environmental Drawing",
"Environmental Land Art",
"Environmental Sculpture",
"Etruscan Art",
"Experimental Film",
"Experimental Printmaking",
"Experimental Video Art",
"Expressionism",
"Expressionistic Portraits",
"Fantastic Realism",
"Fantasy Illustration",
"Fashion Brand",
"Fashion Illustration",
"Fat Sloppy Lines",
"Fauvism",
"Fiber Art",
"Figuration Libre",
"Figurative Art",
"Fluxus",
"Folk Art",
"Found Object Assemblage",
"Fresco",
"Futurism",
"Futurist Manifesto",
"Geometric Abstraction",
"Geometric Art",
"Golden Gold on Gold",
"Gothic Art",
"Gothic Revival",
"Graffiti Art",
"Graffiti Murals",
"Greek Art",
"Haboku",
"Hard-edge Painting",
"Harlem Renaissance",
"Hat Design",
"Hellenistic Art",
"High Renaissance",
"Hindu Art",
"Horror",
"Horrorcore",
"Hudson River School",
"Hyperrealism",
"Hyperrealistic Sculpture",
"Idealism",
"Impressionism",
"Impressionistic Landscapes",
"Impressionistic Seascapes",
"Indian Art",
"Indian Miniature Painting",
"Infrared Photography",
"Installation Art",
"Installation Photography",
"Installation",
"Interactive Installation",
"Invisible Art",
"Italian Renaissance",
"Kinetic Art",
"Kinetic Installation",
"Kinetic Sculpture",
"Kitsch",
"Land Art",
"Landscapes in Pastels",
"Les Nabis",
"Letterism",
"Light and Space",
"Logo Art",
"Luminism",
"Lyrical Abstraction",
"M.C. Escher",
"Macro Photography",
"Magic Realism",
"Mail Art",
"Maniera",
"Mannerism",
"Massurrealism",
"Mathematical Art",
"Maximalism",
"Medieval Art",
"Metaphysical Art",
"Metaphysical Painting",
"Mexican Art",
"Mexican Muralism",
"Minimalism",
"Minimalist Sculpture",
"Mixed Media Abstract",
"Mixed Media Assemblage",
"Mixed Media Collage",
"Mixed Media Portraits",
"Monochrome Painting",
"Mosaic Art",
"Movie Poster",
"Muralism",
"Nabis",
"Naive Art",
"Narrative Art",
"Neo-Dada",
"Neo-Expressionism",
"Neo-Figurative Art",
"Neo-Impressionism",
"Neo-Plasticism",
"Neo-Pop Art",
"Neo-Pop Sculpture",
"Neon Light Sculpture",
"New Media Art",
"New Objectivity",
"Nightmare",
"Northern Renaissance",
"Nouveau Réalisme",
"Olympianism",
"Op Art",
"Organic Abstraction",
"Orientalism",
"Ornamentalism",
"Orphism",
"Outsider Art",
"Paper Cut-Outs",
"Pattern Painting",
"Pen and Ink Drawings",
"Performance Art",
"Performance",
"Photographic",
"Photorealism",
"Photorealistic Cityscapes",
"Photorealistic Portraits",
"Photorealistic Still Life",
"Pixel",
"Pixelated Art",
"Plein Air",
"Plique-à-jour Enameling Technique",
"Pointillism",
"Political Art",
"Polychrome Sculpture",
"Pop Art",
"Pop Surrealism",
"Pop Surrealist",
"Post-Impressionism",
"Post-Impressionist Landscapes",
"Post-Minimalism",
"Post-Painterly Abstraction",
"Posterized",
"Postmodern Sculpture",
"Postmodernism",
"Pre-Raphaelite Brotherhood",
"Precisionism",
"Prehistoric Art",
"Primitive Art",
"Primitivism",
"Proto-Cubism",
"Psychological Realism",
"Punk Art",
"Purism",
"Pyrography",
"Rastafarian",
"Rayonism",
"Realism",
"Realistic Botanical Art",
"Realistic Pet Portraits",
"Realistic Still Life",
"Realistic Watercolor",
"Realistic Wildlife Art",
"Renaissance",
"Rococo",
"Romanesque Art",
"Romanticism",
"Shodo",
"Social Realism",
"Socialist Realism",
"Solarized Painting",
"Sots Art",
"Soviet Nonconformist Art",
"Spatialism",
"Stencil Art",
"Still Life Photography",
"Stop-Motion",
"Straight Lines",
"Street Art Installations",
"Street Art",
"Street Fashion Photography",
"Street Photography",
"Street Portraiture",
"Stuckism",
"Suprematism",
"Surrealism",
"Surrealist Landscapes",
"Surrealist Sculpture",
"Surrealistic Portraits",
"Symbiotic Art",
"Symbolic Realism",
"Symbolism",
"Synchromism",
"Synthetism",
"Synthwave",
"T-Shirt Art",
"T-Shirt Design",
"Tachisme",
"Tactile Art",
"Tenebrism",
"Terra-cotta",
"Textured Abstract",
"Toyism",
"Traditional Chinese Painting",
"Transgressive Art",
"Trompe-l'oeil",
"Ukiyo-e",
"Urban Sketching",
"Vector Art",
"Verism",
"Veristic Surrealism",
"Vibrant Pop Art",
"Video Art",
"Visual Poetry",
"Vorticism",
"Western Art",
"Wire Sculpture",
"Wireframe Art",
"YBA (Young British Artists)",
"Zimbabwean Sculpture"
];