export default ['Superman',
  'Batman',
  'Spider-Man',
  'Iron Man',
  'Captain America',
  'Wonder Woman',
  'Thor',
  'The Flash',
  'Green Lantern',
  'Black Widow',
  'Hulk',
  'Wolverine',
  'Cyclops',
  'Storm',
  'Aquaman',
  'Supergirl',
  'Doctor Strange',
  'Deadpool',
  'Green Arrow',
  'Daredevil',
  'Robin',
  'Batgirl',
  'Nightwing',
  'Hawkeye',
  'Black Panther',
  'Ant-Man',
  'The Wasp',
  'Vision',
  'Scarlet Witch',
  'Luke Cage',
  'Iron Fist',
  'Jessica Jones',
  'Captain Marvel',
  'Shazam',
  'Spider-Woman',
  'She-Hulk',
  'Gambit',
  'Rogue',
  'Beast',
  'Angel',
  'Iceman',
  'Human Torch',
  'Invisible Woman',
  'Mr. Fantastic',
  'The Thing',
  'Jean Grey',
  'Professor X',
  'Magneto',
  'Juggernaut',
  'Doctor Doom',
  'Namor',
  'Silver Surfer',
  'Deadman',
  'Swamp Thing',
  'The Phantom',
  'Zatanna',
  'Green Hornet',
  'The Shadow',
  'The Spirit',
  'The Rocketeer',
  'The Tick',
  'Hellboy',
  'Spawn',
  'V for Vendetta',
  'Watchmen',
  'Rorschach',
  'Nite Owl',
  'Ozymandias',
  'Silk Spectre',
  'Dr. Manhattan',
  'The Comedian',
  'Batman Beyond',
  'Red Hood',
  'Birds of Prey',
  'Batwoman',
  'Catwoman',
  'Huntress',
  'Black Canary',
  'Oracle',
  'Starfire',
  'Raven',
  'Beast Boy',
  'Cyborg',
  'Deathstroke',
  'Harley Quinn',
  'Bane',
  'Two-Face',
  'Poison Ivy',
  'Penguin',
  'Riddler',
  'Scarecrow']