export default [
  "Apple Pie",
  "Banana Split",
  "Baked Alaska",
  "Baklava",
  "Banoffee Pie",
  "Black Forest Cake",
  "Blondies",
  "Blueberry Cheesecake",
  "Bread Pudding",
  "Brownies",
  "Buttercream Frosting",
  "Cannoli",
  "Carrot Cake",
  "Cheesecake",
  "Cherry Pie",
  "Chiffon Cake",
  "Chocolate Cake",
  "Chocolate Chip Cookies",
  "Chocolate Mousse",
  "Chocolate Pudding",
  "Cinnamon Rolls",
  "Coconut Macaroons",
  "Coffee Cake",
  "Cookies and Cream Ice Cream",
  "Creme Brulee",
  "Cupcakes",
  "Eclairs",
  "Flan",
  "Fruit Salad",
  "Fudge",
  "Gelato",
  "German Chocolate Cake",
  "Gingerbread Cookies",
  "Ice Cream Sandwiches",
  "Key Lime Pie",
  "Lemon Bars",
  "Lemon Meringue Pie",
  "Macarons",
  "Mango Sorbet",
  "Maple Syrup Cake",
  "Marshmallow Fluff",
  "Meringues",
  "Mille-Feuille",
  "Molten Chocolate Cake",
  "Neapolitan Ice Cream",
  "Oatmeal Raisin Cookies",
  "Pavlova",
  "Peach Cobbler",
  "Pecan Pie",
  "Pineapple Upside-Down Cake",
  "Poached Pears",
  "Popsicles",
  "Pound Cake",
  "Pralines",
  "Profiteroles",
  "Pumpkin Pie",
  "Red Velvet Cake",
  "Rice Pudding",
  "Rocky Road Ice Cream",
  "S'mores",
  "Shortbread Cookies",
  "Snickerdoodles",
  "Sorbet",
  "Souffle",
  "Strawberry Shortcake",
  "Sugar Cookies",
  "Tarte Tatin",
  "Tiramisu",
  "Toffee",
  "Trifle",
  "Vanilla Bean Ice Cream",
  "Vanilla Cupcakes",
  "Waffles",
  "White Chocolate Macadamia Nut Cookies",
  "Whoopie Pies",
  "Yogurt Parfait",
  "Zabaglione",
  "Zeppole",
  "Zucchini Bread",
  "Almond Biscotti",
  "Anzac Biscuits",
  "Biscotti",
  "Black and White Cookies",
  "Butter Cookies",
  "Caramel Shortbread",
  "Chai Cookies",
  "Chewy Chocolate Chip Cookies",
  "Chocolate Crinkle Cookies",
  "Chocolate Dipped Cookies",
  "Chocolate Hazelnut Biscotti",
  "Chocolate Kiss Cookies",
  "Chocolate Macarons",
  "Chocolate Peanut Butter Cookies",
  "Chocolate Peppermint Cookies",
  "Chocolate Sugar Cookies",
  "Cinnamon Sugar Cookies",
  "Coconut Macaroons",
  "Coffee Cookies",
  "Cornmeal Cookies",
  "Cranberry Orange Cookies",
  "Cream Cheese Cookies",
  "Dark Chocolate Cookies",
  "Double Chocolate Chip Cookies",
  "Fig Newtons",
  "Fortune Cookies",
  "Frosted Sugar Cookies",
  "Fruitcake Cookies",
  "Gingerbread Cookies",
  "Gluten-Free Chocolate Chip Cookies",
  "Hazelnut Shortbread Cookies",
  "Heart-Shaped Cookies",
  "Iced Oatmeal Cookies",
  "Jam Thumbprint Cookies",
  "Lace Cookies",
  "Lemon Butter Cookies",
  "Lemon Crinkle Cookies",
  "Linzer Cookies",
  "M&M Cookies",
  "Macadamia Nut Cookies",
  "Meringue Cookies",
  "Mexican Wedding Cookies",
  "Molasses Cookies",
  "Monster Cookies",
  "Oatmeal Chocolate Chip Cookies",
  "Oatmeal Raisin Cookies",
  "Peanut Butter Blossom Cookies",
  "Peanut Butter Cookies",
  "Pecan Sandies",
  "Peppermint Bark Cookies",
  "Pistachio Shortbread Cookies",
  "Pumpkin Cookies",
  "Red Velvet Cookies",
  "Rolo Cookies",
  "Russian Tea Cakes",
  "Salted Caramel Chocolate Chip Cookies",
  "Shortbread Cookies",
  "Snickerdoodle Cookies",
  "Spice Cookies",
  "Spritz Cookies",
  "Sugar Cookies",
  "Thumbprint Cookies",
  "Toffee Cookies",
  "Triple Chocolate Cookies",
  "Vanilla Bean Shortbread Cookies",
  "Walnut Snowball Cookies",
  "White Chocolate Chip Cookies",
  "White Chocolate Macadamia Nut Cookies",
  "Whole Wheat Chocolate Chip Cookies",
  "Zimtsterne (Cinnamon Stars)",
  "Zucchini Cookies",
  "Oreo Cookies",
  "Nutter Butter Cookies",
  "Famous Amos Cookies",
  "Keebler Fudge Stripe Cookies",
  "Lorna Doone Shortbread Cookies",
  "Fig Newtons",
  "Nilla Wafers",
  "Pirouette Cookies",
  "Speculoos Cookies",
  "Stella D'oro Breakfast Treats",
  "Tate's Bake Shop Cookies",
  "Walkers Shortbread Cookies",
  "Angel Food Cake",
  "Apple Cake",
  "Baba au Rhum",
  "Baumkuchen",
  "Black Forest Cake",
  "Blueberry Cake",
  "Boston Cream Pie",
  "Bundt Cake",
  "Carrot Cake",
  "Cheesecake",
  "Chiffon Cake",
  "Chocolate Cake",
  "Christmas Cake",
  "Coconut Cake",
  "Coffee Cake",
  "Devil's Food Cake",
  "Dobos Torte",
  "Eccles Cake",
  "Esterhazy Torte",
  "Fruitcake",
  "Galette des Rois",
  "Genoise Cake",
  "German Chocolate Cake",
  "Gingerbread Cake",
  "Hazelnut Cake",
  "Hummingbird Cake",
  "Ice Cream Cake",
  "Kiev Cake",
  "King Cake",
  "Lamington",
  "Lemon Cake",
  "Madeira Cake",
  "Mango Cake",
  "Marble Cake",
  "Mille-Feuille",
  "Mocha Cake",
  "Mooncake",
  "Opera Cake",
  "Pancake Cake",
  "Pavlova",
  "Peach Upside-Down Cake",
  "Pineapple Upside-Down Cake",
  "Pound Cake",
  "Princess Cake",
  "Red Velvet Cake",
  "Rum Cake",
  "Sachertorte",
  "Savarin",
  "Shortcake",
  "Sponge Cake",
  "St. Honore Cake",
  "Strawberry Cake",
  "Swiss Roll",
  "Tarte Tatin",
  "Tiramisu Cake",
  "Torta Caprese",
  "Tres Leches Cake",
  "Upside-Down Cake",
  "Vanilla Cake",
  "Victoria Sponge Cake",
  "Walnut Cake",
  "White Cake",
  "Yellow Cake",
  "Zebra Cake",
  "Almond Cake",
  "Apricot Cake",
  "Avocado Cake",
  "Banana Cake",
  "Blue Velvet Cake",
  "Caramel Cake",
  "Chai Cake",
  "Cherry Cake",
  "Chestnut Cake",
  "Cinnamon Roll Cake",
  "Coconut Milk Cake",
  "Date and Walnut Cake",
  "Earl Grey Tea Cake",
  "Fig Cake",
  "Ginger Cake",
  "Grapefruit Cake",
  "Honey Cake",
  "Lavender Cake",
  "Mandarin Cake",
  "Maple Pecan Cake",
  "Matcha Cake",
  "Orange Cake",
  "Peanut Butter Cake",
  "Pecan Pie Cake",
  "Pineapple Coconut Cake",
  "Pistachio Cake",
  "Pomegranate Cake",
  "Poppy Seed Cake",
  "Pumpkin Cake",
  "Raspberry Cake",
  "Rose Cake",
  "Salted Caramel Cake",
  "Sesame Cake",
  "Spice Cake",
  "Sweet Potato Cake",
  "Toffee Cake",
  "Turmeric Cake",
  "Watermelon Cake",
  "White Chocolate Raspberry Cake",
  "Zucchini Cake",
  "Glazed Donut",
  "Jelly Donut",
  "Boston Cream Donut",
  "Cinnamon Sugar Donut",
  "Powdered Donut",
  "Old Fashioned Donut",
  "Maple Bar Donut",
  "Chocolate Glazed Donut",
  "Bear Claw Donut",
  "Apple Fritter Donut",
  "Blueberry Cake Donut",
  "Raspberry Filled Donut",
  "Chocolate Sprinkle Donut",
  "Coconut Donut",
  "Strawberry Frosted Donut",
  "Lemon Filled Donut",
  "Peanut Butter Cup Donut",
  "Caramel Apple Donut",
  "Red Velvet Donut",
  "Salted Caramel Donut",
  "S'mores Donut",
  "Cookie Dough Donut",
  "Mint Chocolate Chip Donut",
  "Pineapple Fritter Donut",
  "Key Lime Donut",
  "Banana Cream Donut",
  "Pecan Praline Donut",
  "Cherry Filled Donut",
  "Tiramisu Donut",
  "Mocha Donut",
  "Pistachio Donut",
  "Blueberry Glazed Donut",
  "Chocolate Coconut Donut",
  "Pumpkin Spice Donut",
  "Cranberry Orange Donut",
  "Eggnog Donut",
  "Peppermint Bark Donut",
  "Gingerbread Donut",
  "Nutella Donut",
  "Oreo Donut",
  "Creme Brulee Donut",
  "Raspberry Cheesecake Donut",
  "Peanut Butter and Jelly Donut",
  "Rocky Road Donut",
  "Almond Joy Donut",
  "Butterscotch Donut",
  "Carrot Cake Donut",
  "Chai Donut",
  "Cheesecake Donut",
  "Chocolate Mint Donut",
  "Coffee Cake Donut",
  "Creamsicle Donut",
  "Dulce de Leche Donut",
  "Fruit Loop Donut",
  "Honey Glazed Donut",
  "Lavender Donut",
  "Lemon Blueberry Donut",
  "Matcha Donut",
  "Mango Donut",
  "Marble Donut",
  "S'mores Donut",
  "Snickers Donut",
  "Strawberry Shortcake Donut",
  "Vanilla Cream Donut",
  "White Chocolate Raspberry Donut",
  "Cinnamon Roll Donut",
  "Pineapple Upside-Down Donut",
  "Blueberry Lemon Donut",
  "Orange Creamsicle Donut",
  "Peach Cobbler Donut",
  "Pumpkin Cheesecake Donut",
  "Raspberry Lemonade Donut",
  "Root Beer Float Donut",
  "Strawberry Milkshake Donut",
  "Tangerine Creamsicle Donut",
  "Toasted Marshmallow Donut",
  "Tropical Punch Donut",
  "Watermelon Donut",
  "Mango Sticky Rice Donut",
  "Coconut Cream Pie Donut",
  "Lemon Meringue Pie Donut",
  "Pina Colada Donut",
  "Tropical Fruit Donut",
  "Passionfruit Donut",
  "Dragonfruit Donut",
  "Blood Orange Donut",
  "Lychee Donut",
  "Champagne Donut"
];
