export default [
"Analog clock",
"Digital clock",
"Wall clock",
"Wristwatch",
"Pocket watch",
"Smartphone",
"Tablet",
"Computer",
"Radio alarm clock",
"Kitchen timer",
"Hourglass",
"Sundial",
"Water clock",
"Candle clock",
"Incense clock",
"Astrolabe",
"Quadrant",
"Sextant",
"Chronometer",
"Atomic clock",
"GPS system",
"Chronograph",
"Stopwatch",
"Pendulum clock",
"Grandfather clock",
"Hour strike clock",
"Moon dial",
"Digital hourglass",
"Projection clock",
"Desk clock",
"Mantel clock",
"Pocket sundial",
"Pulsar clock",
"Regulator clock",
"Skeleton clock",
"Tower clock",
"World time clock",
"Flight chronograph",
"Stoplight clock",
"Binary clock",
"Word clock",
"Flip clock",
"Gear clock",
"Nixie tube clock",
"LED clock",
"VFD clock",
"Torsion pendulum clock",
"Chronophage clock",
"Kukulcan pyramid clock",
"Calendar clock",
"Perpetual calendar",
"Moon phase clock",
"Sunrise and sunset clock",
"Tide clock",
"Chronos clock",
"Smart home device",
"Smart speaker",
"Smart thermostat",
"Smart lighting system",
"Smart security camera",
"Smart doorbell",
"Smart lock",
"Smart scale",
"Smart mirror",
"Smart fridge",
"Smart coffee maker",
"Smart oven",
"Smart air purifier",
"Smart humidifier",
"Smart fan",
"Smart vacuum cleaner",
"Smart washing machine",
"Smart dryer",
"Smart exercise equipment",
"Fitness tracker",
"Smart watch",
"Heart rate monitor",
"Blood pressure monitor",
"Sleep tracker",
"Activity tracker",
"Egg timer",
"Tea timer",
"Coffee timer",
"Pizza timer",
"Microwave timer",
"Oven timer",
"Laundry timer",
"Parking meter"];