export default [
    "glowing",
    "with a huge face",
    "growing fangs",
    "hunting for prey",
    "shooting lazers",
    "flying away",
    "with long legs",
    "with sharp claws",
    "with a million dollars",
    "with a million cellphones",
    "with a million laptops",
    "with glowing eyes",
    "Albino skin",
    "Webbed fingers",
    "Six fingers",
    "Unibrow",
    "Heterochromia eyes",
    "Bald patch",
    "Piercing scars",
    "Cauliflower ear",
    "Nose bridge dent",
    "Double-jointed thumbs",
    "Flat feet",
    "High arches",
    "Cleft chin",
    "Dimples",
    "Freckle patterns",
    "Gapped teeth",
    "Long eyelashes",
    "Moles",
    "Muscular calves",
    "Pigeon-toed",
    "Vitiligo patches",
    "Pointy ears",
    "Raspy voice",
    "Rosacea",
    "Sallow skin",
    "Scarification",
    "Snaggletooth",
    "Uneven nostrils",
    "Widow's peak",
    "Multiple earlobes",
    "Anisocoria",
    "Bee-stung lips",
    "Birthmarks",
    "Bow-legged",
    "Bushy eyebrows",
    "Cowlick",
    "Crooked nose",
    "Curly eyelashes",
    "Deep-set eyes",
    "Elfin face",
    "Gingival overgrowth",
    "Hairy knuckles",
    "Hitchhiker's thumb",
    "Hyperextended joints",
    "Jagged scar",
    "Knobby knees",
    "Mutton chops",
    "Protruding Adam's apple",
    "Roman nose",
    "Ruddy cheeks",
    "Skin tags",
    "Square jaw",
    "Stork bite",
    "Sunken eyes",
    "Supernumerary nipple",
    "Tall forehead",
    "Tiny ears",
    "Tongue-tied",
    "Underbite",
    "Wavy hair",
    "Widely spaced teeth",
    "Xanthodontous",
    "Angular jawline",
    "Blunt fingernails",
    "Concave chest",
    "Crooked smile",
    "Droopy eyelid",
    "Fair eyelashes",
    "Furrowed brow",
    "Hooked nose",
    "Long torso",
    "Monolid eyes",
    "Narrow waist",
    "Oversized ears",
    "Pallor",
    "Receding gums",
    "Short limbs",
    "Skeletal fingers",
    "Tapered fingers",
    "Veiny arms",
    "Winged scapula",
    "Almond eyes",
    "Asymmetrical face",
    "Bronzed skin",
    "Chubby cheeks",
    "Crow's feet",
    "Duck feet",
    "Fish lips",
    "Goosebumps",
    "High cheekbones",
    "In-turned knees",
    "Knock knees",
    "Low-set ears",
    "Outie belly button",
    "Peaked eyebrow",
    "Rounded shoulders",
    "Ski-jump nose",
    "Tilted eyes",
    "Upturned nose",
    "Waifish frame",
    "Wrist freckles",
    "Zigzag hairline"
];