export default [
"Bicycle",
"Electric bicycle",
"Kick scooter",
"Electric scooter",
"Skateboard",
"Longboard",
"Inline skates",
"Roller skates",
"Unicycle",
"Electric unicycle",
"Tricycle",
"Electric tricycle",
"Handcycle",
"Wheelchair",
"Segway",
"Hoverboard",
"Electric hoverboard",
"Electric skateboard",
"Electric longboard",
"Electric scooter bike",
"Electric moped",
"Electric motorcycle",
"Electric car",
"Hybrid car",
"Electric bus",
"Hybrid bus",
"Electric train",
"Maglev train",
"Bullet train",
"High-speed train",
"Subway",
"Light rail",
"Tram",
"Trolleybus",
"Electric boat",
"Sailboat",
"Rowboat",
"Kayak",
"Canoe",
"Paddleboard",
"Raft",
"Ferry",
"Water taxi",
"Zip line",
"Cable car",
"Gondola",
"Chairlift",
"Ski lift",
"Escalator",
"Elevator",
"Stairlift",
"Moving sidewalk",
"Bike share",
"Electric bike share",
"Scooter share",
"Electric scooter share",
"Car share",
"Electric car share",
"Rideshare",
"Carpool",
"Walking",
"Running",
"Hiking",
"Climbing",
"Snowshoeing",
"Cross-country skiing",
"Downhill skiing",
"Snowboarding",
"Ice skating",
"Horseback riding",
"Donkey or mule riding",
"Elephant riding",
"Camel riding",
"Dog sledding",
"Glider",
"Hang gliding",
"Paragliding",
"Hot air balloon",
"Small plane",
"Gyrocopter",
"Ultralight aircraft",
"Helicopter",
"Drone",
"Jetpack",
"Jet ski",
"Sea scooter",
"Underwater scooter",
"Submarine",
"RV",
"Motorhome",
"Camper van",
"Caravan",
"Bicycle camper",
"Tiny home",
"Mobile office",
"Electric skateboard with handles",
"Electric one-wheel",
"Electric unicycle with seat"]