export default [
  "Oak tree",
  "Maple tree",
  "Birch tree",
  "Ash tree",
  "Elm tree",
  "Pine tree",
  "Spruce tree",
  "Cedar tree",
  "Redwood tree",
  "Sequoia tree",
  "Magnolia tree",
  "Cherry tree",
  "Dogwood tree",
  "Cypress tree",
  "Fir tree",
  "Hemlock tree",
  "Juniper tree",
  "Yew tree",
  "Beech tree",
  "Sycamore tree",
  "Willow tree",
  "Poplar tree",
  "Chestnut tree",
  "Walnut tree",
  "Hickory tree",
  "Ginkgo tree",
  "Gum tree",
  "Larch tree",
  "Locust tree",
  "Mimosa tree",
  "Osage Orange tree",
  "Red Bud tree",
  "Serviceberry tree",
  "Silverbell tree",
  "Tulip Tree tree",
  "White Pine tree",
  "Yellowwood tree",
  "Bald Cypress tree",
  "Black Cherry tree",
  "Black Gum tree",
  "Butternut tree",
  "Chinquapin tree",
  "Eastern Red Cedar tree",
  "Hackberry tree",
  "Holly tree",
  "Hornbeam tree",
  "Ironwood tree",
  "Katsura tree",
  "Kentucky Coffee Tree tree",
  "Lombardy Poplar tree",
  "Mountain Ash tree",
  "Paper Birch tree",
  "Persimmon tree",
  "Pignut Hickory tree",
  "Red Maple tree",
  "River Birch tree",
  "Scarlet Oak tree",
  "Shagbark Hickory tree",
  "Sugar Maple tree",
  "Sweetgum tree",
  "Sassafras tree",
  "White Oak tree",
  "Wild Cherry tree",
  "Yellow Birch tree",
  "American Hornbeam tree",
  "Black Oak tree",
  "Black Walnut tree",
  "Eastern Hemlock tree",
  "Eastern White Pine tree",
  "Flowering Dogwood tree",
  "Giant Sequoia tree",
  "Grand Fir tree",
  "Japanese Maple tree",
  "Loblolly Pine tree",
  "Longleaf Pine tree",
  "Noble Fir tree",
  "Northern Red Oak tree",
  "Norway Spruce tree",
  "Ponderosa Pine tree",
  "Red Mulberry tree",
  "Red Pine tree",
  "Rocky Mountain Juniper tree",
  "Siberian Elm tree",
  "Southern Magnolia tree",
  "Swamp White Oak tree",
  "Tamarack tree",
  "White Ash tree",
  "White Spruce tree",
  "Witch Hazel tree",
  "American Beech tree",
  "American Chestnut tree",
  "Black Locust tree",
  "Black Tupelo tree",
  "Blue Spruce tree",
  "Bur Oak tree",
  "Catalpa tree",
  "Douglas Fir tree",
  "English Oak tree",
  "Gambel Oak tree",
  "Ghost Gum tree",
  "Golden Chain Tree tree",
  "Green Ash tree",
  "Kousa Dogwood tree",
  "Lacebark Pine tree",
  "Maidenhair Tree tree",
  "Mediterranean Cypress tree",
  "Montezuma Cypress tree",
  "Mountain Hemlock tree",
  "Natchez Crape Myrtle tree",
  "Osmanthus tree",
  "Paperbark Maple tree",
  "Pin Oak tree",
  "Quaking Aspen tree",
  "Royal Empress Tree tree",
  "Sassafras Albidum tree",
  "Sourwood tree",
  "Southern Red Oak tree",
  "Tulip Poplar tree",
  "Vine Maple tree",
  "Western Hemlock tree",
  "White Mulberry tree",
  "Whitebark Pine tree",
];
