export default [
"Car", 
"Bus", 
"Train", 
"Subway", 
"Bicycle", 
"Motorcycle", 
"Scooter", 
"Boat", 
"Airplane", 
"Helicopter", 
"Toyota Camry", 
"Honda Civic", 
"Ford F-150", 
"Chevrolet Silverado", 
"Nissan Altima", 
"Dodge Charger", 
"Jeep Wrangler", 
"BMW 3 Series", 
"Mercedes-Benz E-Class", 
"Tesla Model S", 
"Boeing 747", 
"Airbus A380", 
"Cessna 172", 
"Beechcraft Bonanza", 
"Embraer E-Jet", 
"Bombardier CRJ", 
"Boeing 737", 
"Airbus A320", 
"McDonnell Douglas MD-80", 
"Gulfstream G650", 
"Sailboat", 
"Motorboat", 
"Yacht", 
"Cruise ship", 
"Fishing boat", 
"Pontoon boat", 
"Jet ski", 
"Canoe", 
"Kayak", 
"Raft"];