export default [
  'Super Mario Bros.',
  'The Legend of Zelda',
  'Metroid',
  'Kirby\'s Dream Land',
  'Punch-Out!!',
  'Ice Climber video game',
  'Excitebike',
  'Balloon Fight video game',
  'Kid Icarus video game',
  'Yoshi\'s Cookie',
  'Dr. Mario',
  'Mario Bros.',
  'Donkey Kong',
  'Mario Kart 64',
  'Super Smash Bros.',
  'Star Fox 64',
  'F-Zero X',
  'Wave Race 64',
  'Mario Party',
  'Paper Mario',
  'Mario Tennis',
  'Mario Golf',
  'Yoshi\'s Story',
  'The Legend of Zelda: Ocarina of Time',
  'The Legend of Zelda: Majora\'s Mask',
  'Pokemon Stadium',
  'Pokemon Snap',
  'Pokemon Puzzle League',
  'Hey You, Pikachu!',
  'Pilotwings 64',
  '1080° Snowboarding',
  'Harvest Moon 64',
  'Bomberman 64',
  'Mega Man 64',
  'Rayman 2: The Great Escape',
  'Banjo-Kazooie',
  'Banjo-Tooie',
  'Perfect Dark',
  'GoldenEye 007',
  'Turok: Dinosaur Hunter',
  'Turok 2: Seeds of Evil',
  'Diddy Kong Racing',
  'Conker\'s Bad Fur Day',
  'Star Wars: Shadows of the Empire',
  'Star Wars: Rogue Squadron',
  'Star Wars: Episode I Racer',
  'Star Wars: Battle for Naboo',
  'Star Wars: Episode I Jedi Power Battles',
  'Star Wars: Episode I: The Phantom Menace',
  'Super Mario 64',
  'Super Mario Sunshine',
  'Super Mario Galaxy',
  'Super Mario Galaxy 2',
  'New Super Mario Bros.',
  'New Super Mario Bros. Wii',
  'New Super Mario Bros. U',
  'Super Mario 3D World',
  'Super Mario Odyssey',
  'The Legend of Zelda: A Link to the Past',
  'The Legend of Zelda: Link\'s Awakening',
  'The Legend of Zelda: Oracle of Ages',
  'The Legend of Zelda: Oracle of Seasons',
  'The Legend of Zelda: Four Swords Adventures',
  'The Legend of Zelda: The Wind Waker',
  'The Legend of Zelda: Four Swords Adventures',
  'The Legend of Zelda: Twilight Princess',
  'The Legend of Zelda: Skyward Sword',
  'The Legend of Zelda: Breath of the Wild',
  'Metroid Prime',
  'Metroid Prime 2: Echoes',
  'Metroid Prime 3: Corruption',
  'Metroid Fusion',
  'Metroid: Zero Mission',
  'Super Metroid',
  'Kirby Super Star',
  'Kirby\'s Dream Course',
  'Kirby\'s Avalanche',
  'Kirby\'s Dream Land 2',
  'Kirby\'s Dream Land 3',
  'Kirby 64: The Crystal Shards',
  'Kirby & The Amazing Mirror',
  'Kirby: Nightmare in Dream Land',
  'Kirby: Canvas Curse',
  'Punch-Out!!',
  'Super Punch-Out!!',
  'Mike Tyson\'s Punch-Out!!',
  'StarTropics',
  'Zoda\'s Revenge: StarTropics II',
  'EarthBound video game',
  'Mother video game',
  'Journey video game',
  'Flower video game',
  'Abzu video game',
  'Shadow of the Colossus',
  'The Last Guardian',
  'Okami video game',
  'The Legend of Zelda: Breath of the Wild',
  'Super Mario Odyssey',
  'Celeste video game',
  'Gris video game',
  'Ori and the Will of the Wisps',
  'Ori and the Blind Forest',
  'Cuphead video game',
  'Inside video game',
  'Limbo video game',
  'Little Nightmares video game',
  'What Remains of Edith Finch',
  'Firewatch video game',
  'The Witness video game',
  'The Vanishing of Ethan Carter',
  'Dear Esther video game',
  'Gone Home video game',
  'SOMA video game',
  'Subnautica video game',
  'No Man\'s Sky',
  'Assassin\'s Creed Origins',
  'Assassin\'s Creed Odyssey',
  'Red Dead Redemption 2',
  'Horizon Zero Dawn',
  'Death Stranding',
  'Final Fantasy XV',
  'NieR: Automata',
  'The Witcher 3: Wild Hunt',
  'Bloodborne',
  'Dark Souls III',
  'God of War',
  'Uncharted 4: A Thief\'s End',
  'The Last of Us Part II',
  'Gran Turismo Sport',
  'Forza Horizon 4',
  'Driveclub',
  'Need for Speed Heat',
  'Project Cars 2',
  'Frostpunk',
  'Kingdom Come: Deliverance',
  'Dishonored 2',
  'Doom (2016)',
  'Wolfenstein II: The New Colossus',
  'Metro Exodus',
  'Resident Evil 2 (2019)',
  'Resident Evil 3 (2020)',
  'Fallout 4',
  'Fallout 76',
  'The Elder Scrolls V: Skyrim',
  'The Elder Scrolls Online',
  'Guild Wars 2',
  'World of Warcraft',
  'Final Fantasy XIV',
  'Destiny 2',
  'Overwatch video game',
  'Apex Legends video game',
  'League of Legends',
  'Dota 2',
  'Counter-Strike: Global Offensive',
  'Rainbow Six Siege',
  'Titanfall 2',
  'Battlefield 1',
  'Battlefield V',
  'Call of Duty: Modern Warfare',
  'Call of Duty: Warzone',
  'Valorant',
  'Fortnite',
  'PlayerUnknown\'s Battlegrounds',
  'Escape from Tarkov',
  'Halo 5: Guardians',
  'Halo: The Master Chief Collection',
  'Gears 5 video game',
  'Gears of War 4',
  'For Honor video game',
  'Mortal Kombat 11',
  'Street Fighter V',
  'Dragon Ball FighterZ']