export default [  
"Vert",  
"Mega ramp",  
"Halfpipe",  
"Quarterpipe",  
"Spine",  
"Step-up",  
"Step-down",  
"Roll-in",  
"Drop-in",  
"Gap",  
"Rail",  
"Grind",  
"Slide",  
"Flip",  
"Spin",  
"Grab",  
"Whip",  
"No-handed",  
"No-footed",  
"Bar spin",  
"Tail whip",  
"Flair",  
"Alley-oop",  
"Transfer",  
"Cab",  
"360",  
"540",  
"720",  
"900",  
"1080",  
"Backflip",  
"Front flip",  
"Cork",  
"Misty",  
"Rodeo",  
"Switch",  
"Regular",  
"Goofy",  
"Fakie",  
"Nollie",  
"Ollie",  
"Manual",  
"Nose manual",  
"Tail manual",  
"One-footed",  
"One-handed",  
"Tuck",  
"Superman",  
"Indian air",  
"Stalefish",  
"Melon",  
"Method",  
"Chicken wing",  
"Saran wrap",  
"Japan",  
"Lien",  
"Sad",  
"Madonna",  
"Crail",  
"Benihana",  
"Varial",  
"Heelflip",  
"Kickflip",  
"Hardflip",  
"Impossible",  
"Late flip",  
"Double flip",  
"Triple flip",  
"Heelflip 540",  
"Nosegrind",  
"Bluntslide",  
"Crooked grind",  
"50-50",  
"Boardslide",  
"Lipslide",  
"Smith grind",  
"Feeble grind",  
"Nose slide",  
"Tail slide",  
"Backside air",  
"Frontside air",  
"McTwist",  
"Rodeo flip",  
"Backside rodeo",  
"Frontside rodeo",  
"Nose grab",  
"Tail grab",  
"Seat grab",  
"Rocket air",  
"Airwalk",  
"Nuclear grab",  
"Christ air",  
"Double grab",  
"Triple grab",  
"Backside grab",  
"Frontside grab",  
"Slob air",  
"Candygrind",  
"Nose blunt",  
"Tail blunt",  
"Invert",
"360 flip",
  "540 flip",
  "720 flip",
  "900 flip",
  "1080 flip",
  "Fakie flip",
  "Nollie flip",
  "Late flip",
  "Hardflip late flip",
  "Inward heelflip",
  "Bigspin",
  "360 shuvit",
  "540 shuvit",
  "Heelflip indy grab",
  "Kickflip mute grab",
  "Frontside 180",
  "Backside 180",
  "Caballerial",
  "Switch frontside 180",
  "Switch backside 180",
  "Switch caballerial",
  "Laser flip",
  "Pressure flip",
  "Casper flip",
  "Boneless",
  "No-comply",
  "Handplant",
  "El Gato",
  "Varial heelflip",
  "360 hardflip",
  "Body varial",
  "Fingerflip",
  "Ghetto bird",
  "Frontside Smith grind",
  "Backside 50-50",
  "Nosegrind to fakie",
  "Crooked grind to fakie",
  "Switch lipslide",
  "Boardslide to fakie",
  "Tailslide to fakie",
  "Blunt fakie",
  "Overcrook",
  "Feeble grind to fakie",
  "Backside noseblunt",
  "Frontside noseblunt",
  "Switch 50-50",
  "Nose manual",
  "Tail manual",
  "Noseblunt slide",
  "Switch backside 5-0",
  "Frontside hurricane",
  "Backside hurricane",
  "Switch frontside hurricane",
  "Bluntslide to fakie",
  "Smith grind to fakie",
  "Backside feeble grind",
  "Frontside feeble grind",
  "Switch crooked grind",
  "Nose slide shove-it",
  "Tail slide shove-it",
  "Smith grind shove-it",
  "Crooked grind shove-it",
  "Nosegrind shove-it",
  "Tailslide bigspin",
  "Frontside airwalk",
  "Backside airwalk",
  "Christ air",
  "One-footed invert",
  "Slob air",
  "Stalefish air",
  "Roastbeef grab",
  "Nuclear grab",
  "Crailslide",
  "Andrecht grab",
  "Mute grab",
  "Lien air",
  "Seatbelt grab",
  "Roast beef air",
  "Tailfish grab",
  "Method air",
  "Indy nosebone",
  "Japan air",
  "Stiffy grab",
  "Sad plant",
  "Blindside air",
  "Tailgrab nosebone",
  "Rocket air",
  "Backflip mute grab",
  "Front flip indy grab",
  "Mute front flip",
  "Lien back flip",
  "Frontside rodeo 540",
  "Backside rodeo 540",
  "Switch rodeo 720",
  "Frontside cork 900",
  "Backside cork 900",
  "Switch double cork 1080",
  "Frontside double cork 1080",
  "Backside double cork 1080"];