export default [
	"Canine", "Feline", "Avian", "Bovine", "Equine", 
    "Piscine", "Porcine", "Vulpine", "Leporine", "Ovine", 
    "Caprine", "Serpentine", "Ursine", "Cervine", "Murine", 
    "Simian", "Asinine", "Lupine", "Ailurine", "Anserine", 
    "Apian", "Arachnid", "Bubaline", "Cameline", "Cancrine", 
    "Castorine", "Cetacean", "Colubrine", "Columbine", "Corvine", 
    "Cricetine", "Crocodilian", "Culicine", "Cunicular", "Delphine", 
    "Elephantine", "Elapine", "Erian", "Erucine", "Falconnine", 
    "Feliform", "Formicine", "Galline", "Hircine", "Hyaenine", 
    "Lacertine", "Lagomorph", "Lamellibranch", "Larval", "Lepidine", 
    "Leporid", "Lutrine", "Macropod", "Melesine", "Melittine", 
    "Mephitine", "Moscine", "Musteline", "Myrmecine", "Nasal", 
    "Noctilucent", "Octopine", "Odonate", "Ornithological", "Pantherine", 
    "Papilionaceous", "Pardine", "Passerine", "Pavonine", "Phasianine", 
    "Phocine", "Psittacine", "Pteropine", "Raccoonlike", "Ranine", "Reptilian",
    "Ratelike", "Rhinocerotic", "Ruminant", "Salamandrine", "Saurian", 
    "Sciuromorph", "Sciurine", "Scolopendrine", "Selachian", "Soricine", 
    "Strigine", "Talpine", "Tarsal", "Taurean", "Testudinal", 
    "Theropod", "Tigrine", "Troglodytic", "Ungulate", "Vermine",
    "Insectoid", "Crustacean", 
]
